#!/usr/bin/env node
/* ═════════════════════════════════════════════════════════════════
   tests/n16-migration-sequence-advancement.test.js
   -------------------------------------------------------------------
   N-16 — tools/migrate-to-pg.js loaded explicit id values into
   `GENERATED BY DEFAULT AS IDENTITY` columns with
   `INSERT ... ON CONFLICT (id) DO UPDATE`. A GENERATED BY DEFAULT insert
   NEVER advances the identity sequence, so after migration every sequence
   still sat at its initial value while the table held seeded rows up to
   MAX(id). The application allocates new ids with ids.nextId →
   nextval(pg_get_serial_sequence(col,'id')) (server/ids.js:66-70), which
   returned 1 for the first post-migration create: the new row landed on
   the seeded id=1 row and ON CONFLICT (id) DO UPDATE silently OVERWROTE
   it while the API answered 201.

   Fix: after the data load the tool now advances every loaded table's
   sequence past its seeded MAX(id) with the same idiom migration 012 and
   the F1 bootstrap (server/index.js:279) already use.

   Scenarios (a fix is not accepted until it survives 5 full runs):
     N16-1  the generated SQL advances the sequence of EVERY collection
            that carries rows, with the canonical setval form
     N16-2  each setval runs AFTER its table's INSERT block and AFTER the
            data COMMIT (a setval before the load would read an empty MAX)
     N16-3  live PostgreSQL: after the full migration, nextval() for every
            populated table is strictly greater than MAX(id)
     N16-4  live PostgreSQL: the defect itself — an explicit-ID insert does
            not advance the sequence (nextval collides), and the exact
            statement the tool emits repairs it
     N16-5  live PostgreSQL: the app's real ids.nextId path against the
            migrated database cannot return an id that already exists
     N16-6  live PostgreSQL: re-running the migration is idempotent and
            the sequences stay correct
   ═════════════════════════════════════════════════════════════════ */
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const REAL_STORE = path.join(ROOT, 'server', 'data', 'payesh.json');

/* The tool reads PAYESH_STORE at require time. */
process.env.PAYESH_STORE = REAL_STORE;
const { generateMigrationSQL } = require('../tools/migrate-to-pg.js');

/* Test instance: a throwaway PostgreSQL initialised by the audit harness
   with trust auth. Edit this constant to point at another instance. */
const PG_URL = 'postgresql://postgres@127.0.0.1:5433/payesh_n16';

let pass = 0, fail = 0, skipped = 0;
async function test(name, fn) {
  try { await fn(); pass++; console.log('  ✅ ' + name); }
  catch (err) { fail++; console.error('  ❌ ' + name + '\n     ' + err.message); }
}

/* Every table name interpolated into SQL below originates from the trusted
   authz model / seed store, never from user input. Validate it as a plain
   identifier before it touches a query string — defense in depth. */
function safeIdent(name) {
  assert.ok(/^[A-Za-z_][A-Za-z0-9_]*$/.test(name), 'refusing to interpolate unsafe identifier: ' + name);
  return name;
}

/* ── structural helpers (no PostgreSQL needed) ──────────────────── */

function statementBlocks(sql) {
  return sql.split(';\n').map(s => s.trim()).filter(s => s.length > 0);
}

function populatedCollections(store) {
  return Object.keys(store)
    .filter(k => Array.isArray(store[k]) && store[k].length > 0)
    .map(k => ({ name: safeIdent(k), rows: store[k] }));
}

/* ── PostgreSQL helpers ─────────────────────────────────────────── */

let pool = null;
async function pg() {
  if (pool) return pool;
  const mod = require('pg');
  pool = new mod.Pool({ connectionString: PG_URL, query_timeout: 180000 });
  return pool;
}

async function pgReachable() {
  try {
    const p = await pg();
    const c = await p.connect();
    await c.query('SELECT 1');
    c.release();
    return true;
  } catch (e) { return false; }
}

async function resetSchema() {
  const p = await pg();
  const c = await p.connect();
  try {
    /* the migration uses bare table names → public schema; drop it wholesale
       so CREATE TABLE IF NOT EXISTS cannot inherit a stale definition */
    await c.query('DROP SCHEMA IF EXISTS public CASCADE');
    await c.query('CREATE SCHEMA public');
  } finally { c.release(); }
}

async function main() {
  console.log('\n🔍 N-16 regression: migration advances identity sequences');

  const store = JSON.parse(fs.readFileSync(REAL_STORE, 'utf8'));
  const { sql, totalRows } = generateMigrationSQL(store);
  const blocks = statementBlocks(sql);
  const populated = populatedCollections(store);
  console.log('  store: ' + populated.length + ' populated collections, ' + totalRows + ' rows, ' + Math.round(sql.length / 1024) + ' KB SQL');

  /* ── N16-1: a setval for every populated collection, canonical form ─ */
  await test('N16-1: generated SQL advances the sequence of every populated collection with the canonical setval form', () => {
    assert.ok(populated.length > 0, 'seed store should have populated collections');
    let canonical = 0;
    for (const col of populated) {
      const re = new RegExp("SELECT setval\\(pg_get_serial_sequence\\('" + col.name + "', 'id'\\),\\s*\\n\\s*COALESCE\\(\\(SELECT MAX\\(id\\) FROM " + col.name + "\\), 0\\) \\+ 1, false\\);");
      assert.ok(re.test(sql), 'missing or malformed setval for ' + col.name);
      canonical++;
    }
    assert.strictEqual(canonical, populated.length, 'only ' + canonical + ' of ' + populated.length + ' populated collections got a canonical setval');
    /* empty collections must NOT get a setval (nothing to collide with, and
       the COALESCE(+1) path is meaningless there) */
    const setvalTables = (sql.match(/SELECT setval\(pg_get_serial_sequence\('([^']+)', 'id'\)/g) || [])
      .map(m => m.match(/'([^']+)'/)[1]);
    for (const t of setvalTables) {
      assert.ok(Array.isArray(store[t]) && store[t].length > 0, 'setval emitted for unpopulated collection ' + t);
    }
  });

  /* ── N16-2: setval comes after the load, not before it ──────────── */
  await test('N16-2: every setval statement appears after its table INSERT block and after the data COMMIT', () => {
    const firstSetval = blocks.findIndex(b => b.indexOf('N-16: advance identity sequences') !== -1);
    assert.ok(firstSetval !== -1, 'N-16 sequence-advancement block is missing from the generated SQL');
    /* the setval block must come after the outer data COMMIT */
    const dataCommit = blocks.findIndex(b => /^COMMIT$/.test(b));
    assert.ok(dataCommit !== -1 && firstSetval > dataCommit, 'setval block must follow the data COMMIT');
    /* and for a sample of tables, the INSERT must precede its setval */
    for (const col of populated.slice(0, 12)) {
      const insertIdx = blocks.findIndex(b => b.indexOf('INSERT INTO ' + col.name + ' (') !== -1);
      const setvalIdx = blocks.findIndex(b => b.indexOf("setval(pg_get_serial_sequence('" + col.name + "', 'id')") !== -1);
      assert.ok(insertIdx !== -1, 'no INSERT block found for ' + col.name);
      assert.ok(setvalIdx > insertIdx, 'setval for ' + col.name + ' must follow its INSERT (got ' + setvalIdx + ' vs ' + insertIdx + ')');
    }
  });

  /* ── live PostgreSQL scenarios ───────────────────────────────────── */
  const reachable = await pgReachable();
  if (!reachable) {
    console.log('  ⏭️ N16-3..N16-6 skipped: no PostgreSQL at ' + PG_URL);
    skipped += 4;
  } else {
    console.log('  live PostgreSQL at ' + PG_URL);

    /* ── N16-3: nextval > MAX(id) for every populated table ───────── */
    await test('N16-3: after the full migration, nextval() for every populated table is strictly greater than MAX(id)', async () => {
      await resetSchema();
      const p = await pg();
      const c = await p.connect();
      try {
        await c.query(sql); /* DDL + data + setval + OCC backfill */
        let checked = 0;
        for (const col of populated) {
          const t = col.name;
          const maxRes = await c.query('SELECT COALESCE((SELECT MAX(id) FROM ' + t + '), 0) AS max_id');
          const maxId = Number(maxRes.rows[0].max_id);
          if (maxId === 0) continue; /* ids were not integers here */
          const seqRes = await c.query('SELECT pg_get_serial_sequence($1, $2) AS seq', [t, 'id']);
          const seq = seqRes.rows[0].seq;
          assert.ok(seq, 'no identity sequence found on ' + t);
          const nv = await c.query('SELECT nextval($1) AS nid', [seq]);
          const nid = Number(nv.rows[0].nid);
          assert.ok(nid > maxId, t + ': nextval ' + nid + ' is not greater than seeded MAX(id) ' + maxId);
          checked++;
        }
        assert.ok(checked > 10, 'expected to check dozens of tables, checked ' + checked);
      } finally { c.release(); }
    });

    /* ── N16-4: the defect itself, and that the emitted SQL repairs it */
    await test('N16-4: an explicit-ID insert does not advance the sequence (collision) and the tool setval repairs it', async () => {
      const p = await pg();
      const c = await p.connect();
      try {
        await c.query('DROP TABLE IF EXISTS n16_scratch');
        await c.query('CREATE TABLE n16_scratch (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT)');
        /* exactly what migrate-to-pg does: explicit ids on a GENERATED
           BY DEFAULT column. A seeded table always owns id=1..MAX. */
        await c.query('INSERT INTO n16_scratch (id, name) VALUES (1,$1),(2,$1),(3,$1),(4,$1),(5,$1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name', ['seeded']);
        const seqRes = await c.query('SELECT pg_get_serial_sequence($1, $2) AS seq', ['n16_scratch', 'id']);
        const seq = seqRes.rows[0].seq;
        /* the defect: the sequence was never advanced by the explicit ids,
           so the first id the app allocates is 1 — the seeded id=1 row */
        const before = await c.query('SELECT nextval($1) AS nid', [seq]);
        const beforeId = Number(before.rows[0].nid);
        assert.ok(beforeId <= 5, 'DEFECT NOT REPRODUCED: nextval ' + beforeId + ' should be <= seeded MAX(id) 5');
        assert.strictEqual(Number((await c.query('SELECT COUNT(*) AS n FROM n16_scratch WHERE id = $1', [beforeId])).rows[0].n), 1,
          'the defect: the id the app would allocate (' + beforeId + ') already holds a seeded row');
        /* the exact statement the tool now emits, applied to this table */
        await c.query("SELECT setval(pg_get_serial_sequence('n16_scratch', 'id'), COALESCE((SELECT MAX(id) FROM n16_scratch), 0) + 1, false)");
        const after = await c.query('SELECT nextval($1) AS nid', [seq]);
        const afterId = Number(after.rows[0].nid);
        assert.strictEqual(afterId, 6, 'after setval the next id must be MAX(id)+1 = 6');
        assert.strictEqual(Number((await c.query('SELECT COUNT(*) AS n FROM n16_scratch WHERE id = $1', [afterId])).rows[0].n), 0,
          'after the fix the allocated id must be free');
      } finally {
        try { await c.query('DROP TABLE IF EXISTS n16_scratch'); } catch (_) {}
        c.release();
      }
    });

    /* ── N16-5: the app's ids.nextId path cannot return an existing id ─ */
    await test('N16-5: ids.nextId semantics (pg_get_serial_sequence + nextval) never returns an existing seeded id', async () => {
      await resetSchema();
      const p = await pg();
      const c = await p.connect();
      try {
        await c.query(sql);
        /* replicate server/ids.js pgNext() exactly */
        const cores = ['users', 'grades', 'attendance', 'classes', 'subjects', 'discipline'];
        for (const col of cores) {
          const t = safeIdent(col);
          const seqRes = await c.query('SELECT pg_get_serial_sequence($1, $2) AS seq', [t, 'id']);
          const seq = seqRes.rows[0].seq;
          assert.ok(seq, 'no identity sequence on ' + t);
          const r = await c.query('SELECT nextval($1) AS nid', [seq]);
          const nid = Number(r.rows[0].nid);
          const clash = await c.query('SELECT COUNT(*) AS n FROM ' + t + ' WHERE id = $1', [nid]);
          assert.strictEqual(Number(clash.rows[0].n), 0, t + ': ids.nextId would return existing id ' + nid + ' → ON CONFLICT overwrite');
        }
      } finally { c.release(); }
    });

    /* ── N16-6: idempotent re-run keeps sequences correct ──────────── */
    await test('N16-6: re-running the migration is idempotent and the sequences stay past MAX(id)', async () => {
      await resetSchema();
      const p = await pg();
      const c = await p.connect();
      try {
        await c.query(sql);
        await c.query(sql); /* second run: pure ON CONFLICT DO UPDATE + setval */
        for (const col of ['users', 'grades', 'attendance']) {
          const t = safeIdent(col);
          const seqRes = await c.query('SELECT pg_get_serial_sequence($1, $2) AS seq', [t, 'id']);
          const seq = seqRes.rows[0].seq;
          const r = await c.query('SELECT nextval($1) AS nid', [seq]);
          const nid = Number(r.rows[0].nid);
          const maxRes = await c.query('SELECT COALESCE((SELECT MAX(id) FROM ' + t + '), 0) AS max_id');
          assert.ok(nid > Number(maxRes.rows[0].max_id), t + ': nextval ' + nid + ' <= MAX(id) after re-run');
        }
      } finally { c.release(); }
    });
  }

  console.log('\nN-16 regression tests: ' + pass + '/' + (pass + fail) + ' passed' + (skipped ? ' (' + skipped + ' skipped)' : ''));
  if (pool) try { await pool.end(); } catch (_) {}
  process.exit(fail === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error('suite crashed:', e);
  if (pool) { try { pool.end(); } catch (_) {} }
  process.exit(2);
});
