#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   N-17 / N-18 regression — durable tombstones + SMS wallet compare-and-write
   ───────────────────────────────────────────────────────────────────
   N-17 (HIGH): deletions were recorded only in the in-memory
   store.__deleted_records ring (capped 5000, smaller than the 7-day delta
   window) while the prepared server_tombstones table was never wired and was
   created by no migration. In PG mode the JSON store is deliberately not
   persisted, so a restart — or a second instance — dropped every tombstone
   and a hard-deleted row re-emerged as live data.

   N-18 (HIGH): the SMS wallet was decremented in RAM and written with an
   unconditional UPDATE (no base_version ⇒ no CAS), so two concurrent sends
   for one school lost a debit; and the mirror failure was swallowed, so the
   request answered 200 while PG never saw the debit or the log rows.

   Five scenarios each, run 5× by the caller.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const { Pool } = require('pg');

const ROOT = path.join(__dirname, '..');
const PG_URL = process.env.N17_PG_URL || 'postgresql://postgres@127.0.0.1:5433/payesh_n16';

let pass = 0, fail = 0;
const test = async (name, fn) => {
  try { await fn(); pass++; console.log('  ✅ ' + name); }
  catch (e) { fail++; console.log('  ❌ ' + name + '\n     ' + (e && e.message ? e.message : String(e))); }
};

console.log('🔍 N-17/N-18 regression: durable tombstones + SMS wallet CAS');

(async () => {
  const pool = new Pool({ connectionString: PG_URL });
  const query = (text, params) => pool.query(text, params);

  /* fresh scratch tables + migration 023 applied — its statements inline
     (static DDL, so the gate can audit them) rather than read from disk
     into a query argument */
  await query('DROP TABLE IF EXISTS n17_items');
  await query('DROP TABLE IF EXISTS n18_wallet');
  await query('CREATE TABLE n17_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, school_id INTEGER, name TEXT, version INTEGER NOT NULL DEFAULT 1)');
  await query('CREATE TABLE n18_wallet (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, school_id INTEGER, balance NUMERIC(12,2), version INTEGER NOT NULL DEFAULT 1)');
  /* scratch tombstones from a previous run share the recycled identity ids
     (DROP TABLE resets the sequence) — clear them so counts are exact */
  await query('DELETE FROM server_tombstones WHERE collection IN ($1, $2)', ['n17_items', 'n18_wallet']);
  await query('BEGIN');
  await query('CREATE TABLE IF NOT EXISTS server_tombstones (id BIGSERIAL PRIMARY KEY, "collection" VARCHAR(64) NOT NULL, record_id INTEGER NOT NULL, school_id INTEGER, deleted_by INTEGER, deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), reason VARCHAR(255))');
  await query('CREATE INDEX IF NOT EXISTS idx_server_tombstones_deleted_at ON server_tombstones (deleted_at)');
  await query('CREATE INDEX IF NOT EXISTS idx_server_tombstones_school_deleted_at ON server_tombstones (school_id, deleted_at)');
  await query('COMMIT');

  const dbMod = require('../server/db.js');
  dbMod.__setPoolForTests(pool);

  /* ── N-17 ────────────────────────────────────────────────────────── */

  await test('N17-1: a delete writes its tombstone to server_tombstones in the same transaction', async () => {
    const ins = await query('INSERT INTO n17_items (school_id, name) VALUES ($1, $2) RETURNING id, school_id, version', [7, 'alpha']);
    const row = ins.rows[0];
    await dbMod.transaction(async (client) => {
      await dbMod.persistOpWithClient(client, { c: 'n17_items', t: 'del', id: row.id, school_id: row.school_id });
    });
    const gone = await query('SELECT 1 FROM n17_items WHERE id = $1', [row.id]);
    assert.strictEqual(gone.rowCount, 0, 'the row must be deleted');
    const tb = await query('SELECT collection, record_id, school_id FROM server_tombstones WHERE record_id = $1 AND collection = $2', [row.id, 'n17_items']);
    assert.strictEqual(tb.rowCount, 1, 'exactly one durable tombstone for the deleted row');
    assert.strictEqual(tb.rows[0].collection, 'n17_items');
    assert.strictEqual(Number(tb.rows[0].record_id), Number(row.id));
    assert.ok(tb.rows[0].school_id != null && Number(tb.rows[0].school_id) === 7, 'the tombstone keeps the deleted row own school scope');
  });

  await test('N17-2: a rolled-back delete leaves NO tombstone (atomicity of the pair)', async () => {
    const ins = await query('INSERT INTO n17_items (school_id, name) VALUES ($1, $2) RETURNING id', [7, 'beta']);
    const id = ins.rows[0].id;
    let threw = null;
    try {
      await dbMod.transaction(async (client) => {
        await dbMod.persistOpWithClient(client, { c: 'n17_items', t: 'del', id, school_id: 7 });
        throw new Error('force_rollback');   /* after the delete + tombstone insert */
      });
    } catch (e) { threw = e; }
    assert.ok(threw && /force_rollback/.test(threw.message), 'the transaction must have rolled back');
    const still = await query('SELECT 1 FROM n17_items WHERE id = $1', [id]);
    assert.strictEqual(still.rowCount, 1, 'the delete must be undone');
    const tb = await query('SELECT 1 FROM server_tombstones WHERE record_id = $1 AND collection = $2', [id, 'n17_items']);
    assert.strictEqual(tb.rowCount, 0, 'no tombstone may survive a rolled-back delete — the pair is atomic');
  });

  await test('N17-3: migration 023 is paired, applies forward and rolls back cleanly', () => {
    const dir = path.join(ROOT, 'migrations');
    assert.ok(fs.existsSync(path.join(dir, '023_server_tombstones.sql')), 'forward migration exists');
    assert.ok(fs.existsSync(path.join(dir, '023_server_tombstones.down.sql')), 'N-14-style pairing: the down migration exists');
    const fwd = fs.readFileSync(path.join(dir, '023_server_tombstones.sql'), 'utf8');
    const dwn = fs.readFileSync(path.join(dir, '023_server_tombstones.down.sql'), 'utf8');
    assert.ok(/BEGIN/.test(fwd) && /COMMIT/.test(fwd), 'forward must be wrapped in a transaction');
    assert.ok(/server_tombstones/.test(fwd), 'creates the table');
    assert.ok(/CREATE INDEX IF NOT EXISTS idx_server_tombstones_school_deleted_at/.test(fwd), 'the school-scoped delta index is created');
    assert.ok(/DROP TABLE IF EXISTS server_tombstones/.test(dwn), 'down drops the table');
    assert.ok(/IF EXISTS/.test(dwn), 'down is guarded with IF EXISTS');
  });

  await test('N17-4: a missing server_tombstones table degrades gracefully instead of failing deletes', async () => {
    dbMod.__resetTombstoneFlagForTests();
    /* a client whose tombstone insert fails with "does not exist" */
    const calls = [];
    const fakeClient = {
      query: async (text) => {
        calls.push(text);
        if (/server_tombstones/i.test(text)) {
          const e = new Error('relation "server_tombstones" does not exist');
          e.code = '42P01';
          throw e;
        }
        return { rowCount: 1, rows: [] };
      }
    };
    await dbMod.recordTombstone(fakeClient, 'n17_items', 42, 7);
    assert.ok(/server_tombstones/i.test(calls.join(' ')), 'the tombstone insert must be attempted');
    /* the flag is now off — a second call must be a no-op that never throws */
    const before = calls.length;
    await dbMod.recordTombstone(fakeClient, 'n17_items', 43, 7);
    assert.strictEqual(calls.length, before, 'after the first absence the insert is skipped (degrade once)');
    dbMod.__resetTombstoneFlagForTests();
  });

  await test('N17-5: pull.js now reads BOTH sources and the inline SQL matches the canonical builder', () => {
    const pullSrc = fs.readFileSync(path.join(ROOT, 'server', 'pull.js'), 'utf8');
    assert.ok(/fetchDeltaTombstones/.test(pullSrc), 'pull must have a PG tombstone reader');
    assert.ok(/server_tombstones/.test(pullSrc), 'the reader targets the durable table');
    const callIdx = pullSrc.indexOf('const pgTombstones = await fetchDeltaTombstones(since');
    assert.ok(callIdx !== -1, 'the delta path must call fetchDeltaTombstones');
    /* the union: PG tombstones concatenated with the in-memory ring, deduped.
       Assert on the block that builds both sources, not the call site. */
    const unionIdx = pullSrc.indexOf('const pgTombstones = await fetchDeltaTombstones(since');
    assert.ok(unionIdx !== -1, 'pull must build a union of the two tombstone sources');
    const region = pullSrc.slice(unionIdx, unionIdx + 700);
    assert.ok(/pgTombstones/.test(region), 'the PG tombstones are a source');
    assert.ok(/__deleted_records/.test(region), 'the in-memory ring is still consulted (union, not replacement)');
    assert.ok(/seen/.test(region), 'the two sources are deduped');
    assert.ok(/deletedRecords = union/.test(pullSrc), 'the union is what the response carries');
    /* drift guard: the inline literals must equal the canonical builder output */
    const { tombstonesSql } = require('../server/syncdelta');
    const withSchool = tombstonesSql({ sinceISO: '2026-01-01T00:00:00Z', schoolId: 5 });
    assert.ok(/deleted_at > \$1 AND \(school_id IS NULL OR school_id = \$2\)/.test(withSchool.sql), 'builder scopes by school');
    assert.ok(/deleted_at > \$1 AND \(school_id IS NULL OR school_id = \$2\)/.test(pullSrc), 'pull\'s inline school-scoped SQL matches the builder');
    assert.ok(/FROM server_tombstones WHERE deleted_at > \$1 ORDER BY/.test(pullSrc), 'pull\'s inline unscoped SQL matches the builder');
  });

  /* ── N-18 ────────────────────────────────────────────────────────── */
  /* sms.js reads PAYESH_SMS_PROVIDER at module load and caches `configured`;
     set it before the first require so the mock gateway is active. */
  process.env.PAYESH_SMS_PROVIDER = 'mock';
  delete process.env.PAYESH_SMS_MOCK_FAIL;

  await test('N18-1: the wallet update is pinned on the row version (compare-and-write, not blind write)', () => {
    const src = fs.readFileSync(path.join(ROOT, 'server', 'sms.js'), 'utf8');
    const i = src.indexOf("c: 'sms_wallet'");
    assert.ok(i !== -1, 'the wallet mirror op exists');
    const region = src.slice(Math.max(0, i - 400), i + 400);
    assert.ok(/base_version/.test(region), 'the wallet upd must carry base_version (N-18 CAS)');
    assert.ok(/walletBaseVersion/.test(region), 'the pinned version must be captured before the debit');
    assert.ok(/prevBalance/.test(region), 'the pre-debit balance must be captured for rollback');
    assert.ok(/mirror_failed/.test(src), 'a failed mirror must be surfaced to the client (not swallowed)');
  });

  await test('N18-2: a concurrent wallet debit is rejected (occ_conflict) — no lost money', async () => {
    await query('DELETE FROM n18_wallet');
    const ins = await query('INSERT INTO n18_wallet (school_id, balance) VALUES ($1, $2) RETURNING id, version', [9, 100]);
    const w = ins.rows[0];
    /* first debit: base_version = the read version → succeeds, 100 → 80 */
    await dbMod.transaction((client) => dbMod.persistOpWithClient(client,
      { c: 'n18_wallet', t: 'upd', id: w.id, base_version: Number(w.version),
        data: { id: w.id, school_id: 9, balance: 80 } }));
    const after1 = await query('SELECT balance, version FROM n18_wallet WHERE id = $1', [w.id]);
    assert.strictEqual(Number(after1.rows[0].balance), 80, 'first debit applied');
    assert.strictEqual(Number(after1.rows[0].version), Number(w.version) + 1, 'version advanced');
    /* second debit using the STALE version → must conflict, balance unchanged */
    let conflict = null;
    try {
      await dbMod.transaction((client) => dbMod.persistOpWithClient(client,
        { c: 'n18_wallet', t: 'upd', id: w.id, base_version: Number(w.version),
          data: { id: w.id, school_id: 9, balance: 70 } }));
    } catch (e) { conflict = e; }
    assert.ok(conflict && conflict.code === 'occ_conflict', 'a stale-version debit must fail with occ_conflict');
    const after2 = await query('SELECT balance FROM n18_wallet WHERE id = $1', [w.id]);
    assert.strictEqual(Number(after2.rows[0].balance), 80, 'the losing debit must NOT change the balance — this is the lost-money case N-18 describes');
  });

  await test('N18-3: a failed mirror rolls the RAM mutation back and answers 503, not 200', async () => {
    const store = {
      users: [{ id: 50, phone: '09120000050', role: 'parent' }],
      notify_queue: [{ id: 77, school_id: 3, body: 'hi', status: 'pending', parts: 1, parent_ids: [50] }],
      sms_wallet: [{ id: 1, school_id: 3, balance: 100, version: 4 }],
      sms_log: []
    };
    const log = [];
    const sms = require('../server/sms.js').createSms({
      store,
      db: { persistOpsBatch: async () => { const e = new Error('PG is down'); e.code = 'occ_conflict'; throw e; } },
      audit: (ev) => log.push(ev),
      sessionFrom: async () => ({ id: 1, role: 'superadmin', school_id: 3 }),
      sendJson: (res, status, body) => { res.status = status; res.body = body; },
      markDirty: () => {}
    });
    delete process.env.PAYESH_SMS_MOCK_FAIL;
    const res = { status: null, body: null };
    await sms.apiSend({}, res, { queue_ids: [77] });
    assert.strictEqual(res.status, 503, 'a failed mirror must answer 503, not a 200 on RAM-only state');
    assert.ok(res.body && res.body.code === 'sms_mirror_failed', 'the failure code must be visible to the client');
    /* RAM rollback */
    assert.strictEqual(Number(store.sms_wallet[0].balance), 100, 'the debit must be rolled back');
    assert.strictEqual(Number(store.sms_wallet[0].version), 4, 'the version must be rolled back');
    assert.strictEqual(store.notify_queue[0].status, 'pending', 'the queue item must stay pending so a retry is safe');
    assert.strictEqual(store.sms_log.length, 0, 'no sms_log row may survive the rollback');
    assert.ok(log.indexOf('sms_send_rolled_back') !== -1, 'the rollback must be audited');
  });

  await test('N18-4: memory mode (no PG mirror) is unchanged — debit applied, 200, queue sent', async () => {
    const store = {
      users: [{ id: 51, phone: '09120000051', role: 'parent' }],
      notify_queue: [{ id: 78, school_id: 3, body: 'hi', status: 'pending', parts: 1, parent_ids: [51] }],
      sms_wallet: [{ id: 2, school_id: 3, balance: 100 }],
      sms_log: []
    };
    const sms = require('../server/sms.js').createSms({
      store,
      db: undefined,   /* memory mode: no pg mirror */
      audit: () => {},
      sessionFrom: async () => ({ id: 1, role: 'superadmin', school_id: 3 }),
      sendJson: (res, status, body) => { res.status = status; res.body = body; },
      markDirty: () => {}
    });
    delete process.env.PAYESH_SMS_MOCK_FAIL;
    const res = { status: null, body: null };
    await sms.apiSend({}, res, { queue_ids: [78] });
    assert.strictEqual(res.status, 200, 'memory mode must keep the legacy 200');
    assert.ok(res.body && res.body.ok === true && res.body.sent === 1, 'the send must be reported');
    assert.strictEqual(Number(store.sms_wallet[0].balance), 99, 'the debit is applied in memory');
    assert.strictEqual(store.notify_queue[0].status, 'sent', 'the queue item is marked sent');
  });

  await test('N18-5: a gateway failure records the failure WITHOUT debiting the wallet', async () => {
    const store = {
      users: [{ id: 52, phone: '09120000052', role: 'parent' }],
      notify_queue: [{ id: 79, school_id: 3, body: 'hi', status: 'pending', parts: 1, parent_ids: [52] }],
      sms_wallet: [{ id: 3, school_id: 3, balance: 100, version: 1 }],
      sms_log: []
    };
    const sms = require('../server/sms.js').createSms({
      store,
      db: { persistOpsBatch: async () => ({ ok: true }) },
      audit: () => {},
      sessionFrom: async () => ({ id: 1, role: 'superadmin', school_id: 3 }),
      sendJson: (res, status, body) => { res.status = status; res.body = body; },
      markDirty: () => {}
    });
    process.env.PAYESH_SMS_MOCK_FAIL = '09120000052';   /* gateway rejects this recipient */
    const res = { status: null, body: null };
    await sms.apiSend({}, res, { queue_ids: [79] });
    delete process.env.PAYESH_SMS_MOCK_FAIL;
    assert.strictEqual(res.status, 200, 'the batch answer is 200 (all-or-nothing item failure)');
    assert.ok(res.body && res.body.failed === 1 && res.body.sent === 0, 'the item is counted failed, not sent');
    assert.strictEqual(Number(store.sms_wallet[0].balance), 100, 'a failed send must never debit the wallet');
    assert.strictEqual(store.notify_queue[0].status, 'pending', 'the queue item stays pending');
    assert.ok(store.sms_log.some((r) => r.status === 'failed'), 'the failure is recorded in sms_log');
  });

  await pool.end();
  console.log('\nN-17/N-18 regression tests: ' + pass + '/' + (pass + fail) + ' passed');
  if (fail > 0) process.exit(1);
})().catch((e) => { console.error('FATAL', e); process.exit(2); });
