/* N-22 — hydration cap leaks server-internal columns and silently disables
 * authentication for users beyond the cap.
 *
 * DEFECT (shape): hydrateStoreFromPg's capped path assigned
 * reviveRows(res.rows) directly, bypassing stripInternalColumns — the one
 * function that removes chg_id from rows leaving the DB layer. So a boot with
 * PAYESH_PG_HYDRATE_LIMIT=u:5000 populated the in-memory mirror with chg_id on
 * every row of every capped table, while readCollection/readOne/delta reads
 * all strip it. The mirror is what auth's fallback lookups, the sync delta and
 * several route list endpoints serialize, so the client-visible row shape
 * silently diverged from memory mode — and chg_id could ride an op payload,
 * where validate.js rejects it as unknown_field.
 *
 * DEFECT (warning hole): hydrationUsersCapped() only inspected h.capped, so
 * PAYESH_PG_HYDRATE_SKIP=users — which empties the users mirror entirely, a
 * strictly worse cut — printed no boot warning at all.
 *
 * FIX: one pipe, one shape — the capped read now goes through
 * stripInternalColumns like every other read; hydrationUsersCapped() now
 * reports both cut paths.
 */
const assert = require('assert');
const path = require('path');
const fs = require('fs');
const os = require('os');

const ROOT = path.join(__dirname, '..');
const PG_HOST = '127.0.0.1';
const PG_PORT = '5433';
const PG_USER = 'postgres';
const PG_BIN = 'C:\\Program Files\\PostgreSQL\\16\\bin';
const TEST_DB = 'payesh_n22_hydrate';

let results = [];
let failures = 0;
function check(name, fn) {
  return Promise.resolve().then(fn).then(
    () => { results.push('  PASS  ' + name); },
    (e) => { failures++; results.push('  FAIL  ' + name + '\n          ' + String(e && e.message || e).split('\n').slice(0, 3).join('\n          ')); }
  );
}

function psql(db, sql) {
  const { execFile } = require('child_process');
  return new Promise((resolve, reject) => {
    execFile(path.join(PG_BIN, 'psql.exe'),
      ['-h', PG_HOST, '-p', PG_PORT, '-U', PG_USER, '-d', db, '-q', '-t', '-A', '-v', 'ON_ERROR_STOP=1', '-c', sql],
      { env: Object.assign({}, process.env, { PGPASSWORD: 'postgres' }) },
      (err, stdout, stderr) => err ? reject(new Error(String(stderr || err).split('\n').filter(l => /ERROR/i.test(l)).slice(0, 2).join(' | '))) : resolve(stdout));
  });
}

(async () => {
  /* The capped path is only reachable when PG is authoritative, so this test
     exercises the real hydrateStoreFromPg against a live scratch database.
     __setPoolForTests takes a real pg.Pool instance (not a connection
     string); isPostgres() is true only while pool !== null && isPgActive. */
  const db = require('../server/db.js');
  let pgLib = null;
  try { pgLib = require('pg'); } catch (e) { pgLib = null; }
  const mkPool = () => new pgLib.Pool({
    host: PG_HOST, port: Number(PG_PORT), user: PG_USER, password: 'postgres',
    database: TEST_DB, max: 2
  });
  let testPool = null;

  /* ── setup: one table with a chg_id-bearing row ------------------------ */
  await psql('postgres', 'DROP DATABASE IF EXISTS ' + TEST_DB + ';');
  await psql('postgres', 'CREATE DATABASE ' + TEST_DB + ';');
  await psql(TEST_DB, 'CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, phone VARCHAR(20), role VARCHAR(32), chg_id BIGINT);');
  await psql(TEST_DB, 'CREATE TABLE schools (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100), chg_id BIGINT);');
  for (let i = 1; i <= 6; i++) {
    await psql(TEST_DB, "INSERT INTO users (id, phone, role, chg_id) VALUES (" + i + ", '0912000000" + i + "', 'teacher', " + (i * 100) + ");");
  }
  await psql(TEST_DB, "INSERT INTO schools (id, name, chg_id) VALUES (1, 'N22 school', 7);");

  const OLD_PG = {};
  const OLD_ENV = {};
  const stash = () => {
    OLD_PG.DATABASE_URL = process.env.DATABASE_URL;
    OLD_ENV.PAYESH_PG_HYDRATE_LIMIT = process.env.PAYESH_PG_HYDRATE_LIMIT;
    OLD_ENV.PAYESH_PG_HYDRATE_SKIP = process.env.PAYESH_PG_HYDRATE_SKIP;
    OLD_ENV.PAYESH_FORCE_HYDRATION = process.env.PAYESH_FORCE_HYDRATION;
  };
  const restore = async () => {
    if (testPool) { try { await testPool.end(); } catch (e) { /* already closed */ } testPool = null; }
    db.__setPoolForTests(null);
    process.env.DATABASE_URL = OLD_PG.DATABASE_URL;
    delete process.env.PAYESH_PG_HYDRATE_LIMIT;
    delete process.env.PAYESH_PG_HYDRATE_SKIP;
    delete process.env.PAYESH_FORCE_HYDRATION;
    if (OLD_ENV.PAYESH_PG_HYDRATE_LIMIT) process.env.PAYESH_PG_HYDRATE_LIMIT = OLD_ENV.PAYESH_PG_HYDRATE_LIMIT;
    if (OLD_ENV.PAYESH_PG_HYDRATE_SKIP) process.env.PAYESH_PG_HYDRATE_SKIP = OLD_ENV.PAYESH_PG_HYDRATE_SKIP;
    if (OLD_ENV.PAYESH_FORCE_HYDRATION) process.env.PAYESH_FORCE_HYDRATION = OLD_ENV.PAYESH_FORCE_HYDRATION;
  };
  const attach = () => { testPool = mkPool(); db.__setPoolForTests(testPool); };

  /* ── N22-1: a capped hydration must not leak chg_id into the mirror ----- */
  await check('N22-1 a capped hydration leaves NO chg_id on mirrored rows (one pipe, one shape)', async () => {
    stash();
    try {
      process.env.DATABASE_URL = 'postgresql://postgres@127.0.0.1:5433/' + TEST_DB;
      process.env.PAYESH_PG_HYDRATE_LIMIT = 'users:3';
      process.env.PAYESH_FORCE_HYDRATION = '1';
      attach();
      const store = {};
      const h = await db.hydrateStoreFromPg(store, { force: true });
      assert.ok(Array.isArray(store.users) && store.users.length === 3,
        'expected the capped users mirror to hold exactly 3 rows, got ' + (store.users && store.users.length));
      const leaked = store.users.filter(r => r && ('chg_id' in r));
      assert.deepStrictEqual(leaked, [], 'capped hydration leaked chg_id into ' + leaked.length + ' mirrored row(s) — the capped path bypassed stripInternalColumns');
      /* the shape must equal what the uncapped readCollection path yields */
      const viaRead = await db.readCollection('users');
      const shapesEqual = store.users.every((r, i) => {
        const other = viaRead.find(x => x && Number(x.id) === Number(r.id));
        if (!other) return false;
        const ka = Object.keys(r).sort().join(',');
        const kb = Object.keys(other).sort().join(',');
        return ka === kb;
      });
      assert.ok(shapesEqual, 'capped mirror row shape differs from readCollection row shape');
      assert.ok(h.capped.indexOf('users:3') !== -1, 'hydrator must report the cap in out.capped');
      await restore();
    } finally { restore(); }
  });

  /* ── N22-2: the uncapped path is unchanged (no regression) -------------- */
  await check('N22-2 an uncapped hydration reads every row and strips too', async () => {
    stash();
    try {
      process.env.DATABASE_URL = 'postgresql://postgres@127.0.0.1:5433/' + TEST_DB;
      process.env.PAYESH_FORCE_HYDRATION = '1';
      attach();
      const store = {};
      const h = await db.hydrateStoreFromPg(store, { force: true });
      assert.deepStrictEqual(h.capped, [], 'no cap was set, out.capped must be empty');
      assert.ok(Array.isArray(store.users) && store.users.length === 6, 'uncapped hydration must read all 6 rows, got ' + (store.users && store.users.length));
      assert.deepStrictEqual(store.users.filter(r => r && ('chg_id' in r)), [], 'uncapped path must also strip chg_id');
      await restore();
    } finally { restore(); }
  });

  /* ── N22-3: the env-skip warning hole — SKIP=users must now be reported */
  await check('N22-3 hydrationUsersCapped() reports PAYESH_PG_HYDRATE_SKIP=users (previously silent)', async () => {
    assert.ok(db.hydrationUsersCapped({ capped: ['users:5000'] }), 'capped users must be reported');
    assert.ok(db.hydrationUsersCapped({ capped: [], env_skipped: ['users', 'notifications'] }), 'env-skipped users must ALSO be reported — this is the hole');
    assert.ok(!db.hydrationUsersCapped({ capped: ['schools:10'], env_skipped: ['notifications'] }), 'a cut that does not touch users must not warn');
    assert.ok(!db.hydrationUsersCapped({}), 'an uncut hydration must not warn');
  });

  /* ── N22-4: the capped path must still honour the cap (not read all) --- */
  await check('N22-4 the cap genuinely limits the row count (ORDER BY id, first N)', async () => {
    stash();
    try {
      process.env.DATABASE_URL = 'postgresql://postgres@127.0.0.1:5433/' + TEST_DB;
      process.env.PAYESH_PG_HYDRATE_LIMIT = 'users:2';
      process.env.PAYESH_FORCE_HYDRATION = '1';
      attach();
      const store = {};
      const h = await db.hydrateStoreFromPg(store, { force: true });
      assert.strictEqual(store.users.length, 2, 'the cap must limit the mirror to 2 rows');
      assert.deepStrictEqual(store.users.map(r => Number(r.id)), [1, 2], 'the cap must take the lowest ids in ORDER BY id order');
      assert.ok(h.capped.indexOf('users:2') !== -1, 'out.capped must name users:2');
      assert.ok(h.mirror_incomplete, 'a capped hydration must set mirror_incomplete so the trimmed snapshot is never written over the store file');
      await restore();
    } finally { restore(); }
  });

  /* ── N22-5: stripInternalColumns is the single chokepoint — no read path
       may emit chg_id, so a leaked column cannot re-enter anywhere. -------- */
  await check('N22-5 every DB read path strips chg_id (hydrate, readCollection, readOne)', async () => {
    stash();
    try {
      process.env.DATABASE_URL = 'postgresql://postgres@127.0.0.1:5433/' + TEST_DB;
      attach();
      const viaColl = await db.readCollection('users');
      assert.deepStrictEqual(viaColl.filter(r => r && ('chg_id' in r)), [], 'readCollection leaked chg_id');
      const one = await db.readOne('users', 3);
      assert.ok(one && one.id === 3, 'readOne must find the row');
      assert.ok(!('chg_id' in one), 'readOne leaked chg_id');
      /* the pure helper itself */
      const stripped = db.stripInternalColumns([{ id: 1, chg_id: 42, phone: 'x' }]);
      assert.deepStrictEqual(stripped, [{ id: 1, phone: 'x' }]);
      assert.deepStrictEqual(db.stripInternalColumns([{ id: 1, phone: 'x' }]), [{ id: 1, phone: 'x' }], 'rows without internal columns must pass through untouched');
      await restore();
    } finally { restore(); }
  });

  await psql('postgres', 'DROP DATABASE IF EXISTS ' + TEST_DB + ';');

  console.log('\n=== N-22 hydration cap shape leak + warning hole ===');
  console.log(results.join('\n'));
  console.log((failures ? '\nFAILED: ' + failures : '\nALL PASSED') + ' (' + results.length + ' checks)');
  process.exit(failures ? 1 : 0);
})().catch(e => { console.error('N-22 harness crashed:', e); process.exit(2); });
