-- Migration 002: indexes (per-table + composite)
-- NOTE: idx_sync_conflicts_school_status intentionally omitted — sync_conflicts
-- is not yet formalized in authz/model.json (tracked follow-up).
-- GENERATED from authz/model.json via tools/migrate-to-pg.js — FROZEN, do not edit.

-- Up Migration

CREATE INDEX IF NOT EXISTS idx_announcements_school_id ON announcements (school_id);
CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON announcements (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_settings_created_at ON app_settings (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assets_school_id ON assets (school_id);
CREATE INDEX IF NOT EXISTS idx_assets_created_at ON assets (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assoc_minutes_school_id ON assoc_minutes (school_id);
CREATE INDEX IF NOT EXISTS idx_assoc_minutes_created_at ON assoc_minutes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_school_id ON attendance (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_school_student ON attendance (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_school_class ON attendance (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_created_at ON attendance (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_modes_school_id ON attendance_modes (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_modes_created_at ON attendance_modes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bell_schedules_school_id ON bell_schedules (school_id);
CREATE INDEX IF NOT EXISTS idx_bell_schedules_created_at ON bell_schedules (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_events_school_id ON bus_events (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_events_school_student ON bus_events (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_events_created_at ON bus_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_followups_school_id ON bus_followups (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_followups_school_student ON bus_followups (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_followups_created_at ON bus_followups (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_locations_created_at ON bus_locations (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_needs_school_id ON bus_needs (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_needs_school_student ON bus_needs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_needs_created_at ON bus_needs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_routes_school_id ON bus_routes (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_routes_created_at ON bus_routes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bus_students_created_at ON bus_students (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_calendar_school_id ON calendar (school_id);
CREATE INDEX IF NOT EXISTS idx_calendar_created_at ON calendar (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_certificates_school_id ON certificates (school_id);
CREATE INDEX IF NOT EXISTS idx_certificates_school_student ON certificates (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_certificates_created_at ON certificates (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_class_subject_members_created_at ON class_subject_members (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_classes_school_id ON classes (school_id);
CREATE INDEX IF NOT EXISTS idx_classes_created_at ON classes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_corrections_school_id ON corrections (school_id);
CREATE INDEX IF NOT EXISTS idx_corrections_school_student ON corrections (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_corrections_created_at ON corrections (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_counselor_msgs_school_id ON counselor_msgs (school_id);
CREATE INDEX IF NOT EXISTS idx_counselor_msgs_school_student ON counselor_msgs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_msgs_created_at ON counselor_msgs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_counselor_refs_school_id ON counselor_refs (school_id);
CREATE INDEX IF NOT EXISTS idx_counselor_refs_school_student ON counselor_refs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_refs_created_at ON counselor_refs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_counties_created_at ON counties (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discipline_school_id ON discipline (school_id);
CREATE INDEX IF NOT EXISTS idx_discipline_school_student ON discipline (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_discipline_created_at ON discipline (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_districts_created_at ON districts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dojo_types_school_id ON dojo_types (school_id);
CREATE INDEX IF NOT EXISTS idx_dojo_types_created_at ON dojo_types (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dorm_assignments_school_id ON dorm_assignments (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_assignments_school_student ON dorm_assignments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_dorm_assignments_created_at ON dorm_assignments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dorm_meals_school_id ON dorm_meals (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_meals_created_at ON dorm_meals (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dorm_rooms_school_id ON dorm_rooms (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_rooms_created_at ON dorm_rooms (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_enrollments_school_id ON enrollments (school_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_school_student ON enrollments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_school_class ON enrollments (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_created_at ON enrollments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_exam_duties_school_id ON exam_duties (school_id);
CREATE INDEX IF NOT EXISTS idx_exam_duties_created_at ON exam_duties (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_exam_terms_school_id ON exam_terms (school_id);
CREATE INDEX IF NOT EXISTS idx_exam_terms_created_at ON exam_terms (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_exams_school_id ON exams (school_id);
CREATE INDEX IF NOT EXISTS idx_exams_school_class ON exams (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_exams_created_at ON exams (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_grades_school_id ON grades (school_id);
CREATE INDEX IF NOT EXISTS idx_grades_school_student ON grades (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_grades_school_class ON grades (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_grades_created_at ON grades (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hw_assignments_school_id ON hw_assignments (school_id);
CREATE INDEX IF NOT EXISTS idx_hw_assignments_school_class ON hw_assignments (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_hw_assignments_created_at ON hw_assignments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hw_submissions_created_at ON hw_submissions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_installments_school_id ON installments (school_id);
CREATE INDEX IF NOT EXISTS idx_installments_school_student ON installments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_installments_created_at ON installments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_internships_school_id ON internships (school_id);
CREATE INDEX IF NOT EXISTS idx_internships_school_student ON internships (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_internships_created_at ON internships (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leaves_school_id ON leaves (school_id);
CREATE INDEX IF NOT EXISTS idx_leaves_school_student ON leaves (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_leaves_created_at ON leaves (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lib_books_school_id ON lib_books (school_id);
CREATE INDEX IF NOT EXISTS idx_lib_books_created_at ON lib_books (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lib_loans_school_id ON lib_loans (school_id);
CREATE INDEX IF NOT EXISTS idx_lib_loans_school_student ON lib_loans (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_lib_loans_created_at ON lib_loans (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_makeup_classes_school_id ON makeup_classes (school_id);
CREATE INDEX IF NOT EXISTS idx_makeup_classes_created_at ON makeup_classes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meeting_slots_school_id ON meeting_slots (school_id);
CREATE INDEX IF NOT EXISTS idx_meeting_slots_school_student ON meeting_slots (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_meeting_slots_created_at ON meeting_slots (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_school_id ON messages (school_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_nid_conflicts_school_id ON nid_conflicts (school_id);
CREATE INDEX IF NOT EXISTS idx_nid_conflicts_school_nid ON nid_conflicts (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_nid_conflicts_created_at ON nid_conflicts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_school_id ON notifications (school_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notify_queue_school_id ON notify_queue (school_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_school_student ON notify_queue (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_school_class ON notify_queue (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_created_at ON notify_queue (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_nudges_school_id ON nudges (school_id);
CREATE INDEX IF NOT EXISTS idx_nudges_school_class ON nudges (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_nudges_created_at ON nudges (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_offices_created_at ON offices (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_parent_links_created_at ON parent_links (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_parent_subscriptions_created_at ON parent_subscriptions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_parent_verifications_created_at ON parent_verifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_id ON pre_enrollments (school_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_nid ON pre_enrollments (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_student ON pre_enrollments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_created_at ON pre_enrollments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_preapps_school_id ON preapps (school_id);
CREATE INDEX IF NOT EXISTS idx_preapps_created_at ON preapps (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provinces_created_at ON provinces (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reexams_school_id ON reexams (school_id);
CREATE INDEX IF NOT EXISTS idx_reexams_school_student ON reexams (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_reexams_created_at ON reexams (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_schedule_school_id ON schedule (school_id);
CREATE INDEX IF NOT EXISTS idx_schedule_school_class ON schedule (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_schedule_created_at ON schedule (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scholarships_school_id ON scholarships (school_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_school_student ON scholarships (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_created_at ON scholarships (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_school_years_created_at ON school_years (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_schools_created_at ON schools (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sedascores_school_id ON sedascores (school_id);
CREATE INDEX IF NOT EXISTS idx_sedascores_school_student ON sedascores (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_sedascores_created_at ON sedascores (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sms_log_school_id ON sms_log (school_id);
CREATE INDEX IF NOT EXISTS idx_sms_log_created_at ON sms_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sms_wallet_school_id ON sms_wallet (school_id);
CREATE INDEX IF NOT EXISTS idx_sms_wallet_created_at ON sms_wallet (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_student_archive_school_id ON student_archive (school_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_school_nid ON student_archive (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_school_student ON student_archive (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_created_at ON student_archive (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_student_transfers_created_at ON student_transfers (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subjects_school_id ON subjects (school_id);
CREATE INDEX IF NOT EXISTS idx_subjects_created_at ON subjects (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscription_payments_created_at ON subscription_payments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_substitutions_school_id ON substitutions (school_id);
CREATE INDEX IF NOT EXISTS idx_substitutions_created_at ON substitutions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_summer_classes_school_id ON summer_classes (school_id);
CREATE INDEX IF NOT EXISTS idx_summer_classes_created_at ON summer_classes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_school_id ON support_tickets (school_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_created_at ON support_tickets (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_teacher_notes_school_id ON teacher_notes (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_notes_school_student ON teacher_notes (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_teacher_notes_created_at ON teacher_notes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_teacher_schools_school_id ON teacher_schools (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_schools_created_at ON teacher_schools (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_teacher_sms_school_id ON teacher_sms (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_sms_created_at ON teacher_sms (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_school_id ON transactions (school_id);
CREATE INDEX IF NOT EXISTS idx_transactions_school_student ON transactions (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transfer_requests_created_at ON transfer_requests (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tuition_plans_school_id ON tuition_plans (school_id);
CREATE INDEX IF NOT EXISTS idx_tuition_plans_created_at ON tuition_plans (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tuitions_school_id ON tuitions (school_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_school_student ON tuitions (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_school_class ON tuitions (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_created_at ON tuitions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_school_id ON users (school_id);
CREATE INDEX IF NOT EXISTS idx_users_school_nid ON users (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vclass_attendance_created_at ON vclass_attendance (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vclass_links_created_at ON vclass_links (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vclass_questions_created_at ON vclass_questions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vclass_sessions_school_id ON vclass_sessions (school_id);
CREATE INDEX IF NOT EXISTS idx_vclass_sessions_school_class ON vclass_sessions (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_vclass_sessions_created_at ON vclass_sessions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitors_school_id ON visitors (school_id);
CREATE INDEX IF NOT EXISTS idx_visitors_created_at ON visitors (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_school_role ON users (school_id, role);
CREATE INDEX IF NOT EXISTS idx_attendance_school_class_date ON attendance (school_id, class_id, date);
CREATE INDEX IF NOT EXISTS idx_grades_school_student_subject ON grades (school_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_schedule_school_teacher_day ON schedule (school_id, teacher_id, day);
CREATE INDEX IF NOT EXISTS idx_parent_links_parent_student ON parent_links (parent_id, student_id);
CREATE INDEX IF NOT EXISTS idx_messages_to_from ON messages (to_id, from_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, read);
CREATE INDEX IF NOT EXISTS idx_schools_capabilities ON schools USING GIN (capabilities);

-- Down Migration

DROP INDEX IF EXISTS idx_schools_capabilities;
DROP INDEX IF EXISTS idx_notifications_user_read;
DROP INDEX IF EXISTS idx_messages_to_from;
DROP INDEX IF EXISTS idx_parent_links_parent_student;
DROP INDEX IF EXISTS idx_schedule_school_teacher_day;
DROP INDEX IF EXISTS idx_grades_school_student_subject;
DROP INDEX IF EXISTS idx_attendance_school_class_date;
DROP INDEX IF EXISTS idx_users_school_role;
DROP INDEX IF EXISTS idx_visitors_created_at;
DROP INDEX IF EXISTS idx_visitors_school_id;
DROP INDEX IF EXISTS idx_vclass_sessions_created_at;
DROP INDEX IF EXISTS idx_vclass_sessions_school_class;
DROP INDEX IF EXISTS idx_vclass_sessions_school_id;
DROP INDEX IF EXISTS idx_vclass_questions_created_at;
DROP INDEX IF EXISTS idx_vclass_links_created_at;
DROP INDEX IF EXISTS idx_vclass_attendance_created_at;
DROP INDEX IF EXISTS idx_users_created_at;
DROP INDEX IF EXISTS idx_users_school_nid;
DROP INDEX IF EXISTS idx_users_school_id;
DROP INDEX IF EXISTS idx_tuitions_created_at;
DROP INDEX IF EXISTS idx_tuitions_school_class;
DROP INDEX IF EXISTS idx_tuitions_school_student;
DROP INDEX IF EXISTS idx_tuitions_school_id;
DROP INDEX IF EXISTS idx_tuition_plans_created_at;
DROP INDEX IF EXISTS idx_tuition_plans_school_id;
DROP INDEX IF EXISTS idx_transfer_requests_created_at;
DROP INDEX IF EXISTS idx_transactions_created_at;
DROP INDEX IF EXISTS idx_transactions_school_student;
DROP INDEX IF EXISTS idx_transactions_school_id;
DROP INDEX IF EXISTS idx_teacher_sms_created_at;
DROP INDEX IF EXISTS idx_teacher_sms_school_id;
DROP INDEX IF EXISTS idx_teacher_schools_created_at;
DROP INDEX IF EXISTS idx_teacher_schools_school_id;
DROP INDEX IF EXISTS idx_teacher_notes_created_at;
DROP INDEX IF EXISTS idx_teacher_notes_school_student;
DROP INDEX IF EXISTS idx_teacher_notes_school_id;
DROP INDEX IF EXISTS idx_support_tickets_created_at;
DROP INDEX IF EXISTS idx_support_tickets_school_id;
DROP INDEX IF EXISTS idx_summer_classes_created_at;
DROP INDEX IF EXISTS idx_summer_classes_school_id;
DROP INDEX IF EXISTS idx_substitutions_created_at;
DROP INDEX IF EXISTS idx_substitutions_school_id;
DROP INDEX IF EXISTS idx_subscription_payments_created_at;
DROP INDEX IF EXISTS idx_subjects_created_at;
DROP INDEX IF EXISTS idx_subjects_school_id;
DROP INDEX IF EXISTS idx_student_transfers_created_at;
DROP INDEX IF EXISTS idx_student_archive_created_at;
DROP INDEX IF EXISTS idx_student_archive_school_student;
DROP INDEX IF EXISTS idx_student_archive_school_nid;
DROP INDEX IF EXISTS idx_student_archive_school_id;
DROP INDEX IF EXISTS idx_sms_wallet_created_at;
DROP INDEX IF EXISTS idx_sms_wallet_school_id;
DROP INDEX IF EXISTS idx_sms_log_created_at;
DROP INDEX IF EXISTS idx_sms_log_school_id;
DROP INDEX IF EXISTS idx_sedascores_created_at;
DROP INDEX IF EXISTS idx_sedascores_school_student;
DROP INDEX IF EXISTS idx_sedascores_school_id;
DROP INDEX IF EXISTS idx_schools_created_at;
DROP INDEX IF EXISTS idx_school_years_created_at;
DROP INDEX IF EXISTS idx_scholarships_created_at;
DROP INDEX IF EXISTS idx_scholarships_school_student;
DROP INDEX IF EXISTS idx_scholarships_school_id;
DROP INDEX IF EXISTS idx_schedule_created_at;
DROP INDEX IF EXISTS idx_schedule_school_class;
DROP INDEX IF EXISTS idx_schedule_school_id;
DROP INDEX IF EXISTS idx_reexams_created_at;
DROP INDEX IF EXISTS idx_reexams_school_student;
DROP INDEX IF EXISTS idx_reexams_school_id;
DROP INDEX IF EXISTS idx_provinces_created_at;
DROP INDEX IF EXISTS idx_preapps_created_at;
DROP INDEX IF EXISTS idx_preapps_school_id;
DROP INDEX IF EXISTS idx_pre_enrollments_created_at;
DROP INDEX IF EXISTS idx_pre_enrollments_school_student;
DROP INDEX IF EXISTS idx_pre_enrollments_school_nid;
DROP INDEX IF EXISTS idx_pre_enrollments_school_id;
DROP INDEX IF EXISTS idx_parent_verifications_created_at;
DROP INDEX IF EXISTS idx_parent_subscriptions_created_at;
DROP INDEX IF EXISTS idx_parent_links_created_at;
DROP INDEX IF EXISTS idx_offices_created_at;
DROP INDEX IF EXISTS idx_nudges_created_at;
DROP INDEX IF EXISTS idx_nudges_school_class;
DROP INDEX IF EXISTS idx_nudges_school_id;
DROP INDEX IF EXISTS idx_notify_queue_created_at;
DROP INDEX IF EXISTS idx_notify_queue_school_class;
DROP INDEX IF EXISTS idx_notify_queue_school_student;
DROP INDEX IF EXISTS idx_notify_queue_school_id;
DROP INDEX IF EXISTS idx_notifications_created_at;
DROP INDEX IF EXISTS idx_notifications_school_id;
DROP INDEX IF EXISTS idx_nid_conflicts_created_at;
DROP INDEX IF EXISTS idx_nid_conflicts_school_nid;
DROP INDEX IF EXISTS idx_nid_conflicts_school_id;
DROP INDEX IF EXISTS idx_messages_created_at;
DROP INDEX IF EXISTS idx_messages_school_id;
DROP INDEX IF EXISTS idx_meeting_slots_created_at;
DROP INDEX IF EXISTS idx_meeting_slots_school_student;
DROP INDEX IF EXISTS idx_meeting_slots_school_id;
DROP INDEX IF EXISTS idx_makeup_classes_created_at;
DROP INDEX IF EXISTS idx_makeup_classes_school_id;
DROP INDEX IF EXISTS idx_lib_loans_created_at;
DROP INDEX IF EXISTS idx_lib_loans_school_student;
DROP INDEX IF EXISTS idx_lib_loans_school_id;
DROP INDEX IF EXISTS idx_lib_books_created_at;
DROP INDEX IF EXISTS idx_lib_books_school_id;
DROP INDEX IF EXISTS idx_leaves_created_at;
DROP INDEX IF EXISTS idx_leaves_school_student;
DROP INDEX IF EXISTS idx_leaves_school_id;
DROP INDEX IF EXISTS idx_internships_created_at;
DROP INDEX IF EXISTS idx_internships_school_student;
DROP INDEX IF EXISTS idx_internships_school_id;
DROP INDEX IF EXISTS idx_installments_created_at;
DROP INDEX IF EXISTS idx_installments_school_student;
DROP INDEX IF EXISTS idx_installments_school_id;
DROP INDEX IF EXISTS idx_hw_submissions_created_at;
DROP INDEX IF EXISTS idx_hw_assignments_created_at;
DROP INDEX IF EXISTS idx_hw_assignments_school_class;
DROP INDEX IF EXISTS idx_hw_assignments_school_id;
DROP INDEX IF EXISTS idx_grades_created_at;
DROP INDEX IF EXISTS idx_grades_school_class;
DROP INDEX IF EXISTS idx_grades_school_student;
DROP INDEX IF EXISTS idx_grades_school_id;
DROP INDEX IF EXISTS idx_exams_created_at;
DROP INDEX IF EXISTS idx_exams_school_class;
DROP INDEX IF EXISTS idx_exams_school_id;
DROP INDEX IF EXISTS idx_exam_terms_created_at;
DROP INDEX IF EXISTS idx_exam_terms_school_id;
DROP INDEX IF EXISTS idx_exam_duties_created_at;
DROP INDEX IF EXISTS idx_exam_duties_school_id;
DROP INDEX IF EXISTS idx_enrollments_created_at;
DROP INDEX IF EXISTS idx_enrollments_school_class;
DROP INDEX IF EXISTS idx_enrollments_school_student;
DROP INDEX IF EXISTS idx_enrollments_school_id;
DROP INDEX IF EXISTS idx_dorm_rooms_created_at;
DROP INDEX IF EXISTS idx_dorm_rooms_school_id;
DROP INDEX IF EXISTS idx_dorm_meals_created_at;
DROP INDEX IF EXISTS idx_dorm_meals_school_id;
DROP INDEX IF EXISTS idx_dorm_assignments_created_at;
DROP INDEX IF EXISTS idx_dorm_assignments_school_student;
DROP INDEX IF EXISTS idx_dorm_assignments_school_id;
DROP INDEX IF EXISTS idx_dojo_types_created_at;
DROP INDEX IF EXISTS idx_dojo_types_school_id;
DROP INDEX IF EXISTS idx_districts_created_at;
DROP INDEX IF EXISTS idx_discipline_created_at;
DROP INDEX IF EXISTS idx_discipline_school_student;
DROP INDEX IF EXISTS idx_discipline_school_id;
DROP INDEX IF EXISTS idx_counties_created_at;
DROP INDEX IF EXISTS idx_counselor_refs_created_at;
DROP INDEX IF EXISTS idx_counselor_refs_school_student;
DROP INDEX IF EXISTS idx_counselor_refs_school_id;
DROP INDEX IF EXISTS idx_counselor_msgs_created_at;
DROP INDEX IF EXISTS idx_counselor_msgs_school_student;
DROP INDEX IF EXISTS idx_counselor_msgs_school_id;
DROP INDEX IF EXISTS idx_corrections_created_at;
DROP INDEX IF EXISTS idx_corrections_school_student;
DROP INDEX IF EXISTS idx_corrections_school_id;
DROP INDEX IF EXISTS idx_classes_created_at;
DROP INDEX IF EXISTS idx_classes_school_id;
DROP INDEX IF EXISTS idx_class_subject_members_created_at;
DROP INDEX IF EXISTS idx_certificates_created_at;
DROP INDEX IF EXISTS idx_certificates_school_student;
DROP INDEX IF EXISTS idx_certificates_school_id;
DROP INDEX IF EXISTS idx_calendar_created_at;
DROP INDEX IF EXISTS idx_calendar_school_id;
DROP INDEX IF EXISTS idx_bus_students_created_at;
DROP INDEX IF EXISTS idx_bus_routes_created_at;
DROP INDEX IF EXISTS idx_bus_routes_school_id;
DROP INDEX IF EXISTS idx_bus_needs_created_at;
DROP INDEX IF EXISTS idx_bus_needs_school_student;
DROP INDEX IF EXISTS idx_bus_needs_school_id;
DROP INDEX IF EXISTS idx_bus_locations_created_at;
DROP INDEX IF EXISTS idx_bus_followups_created_at;
DROP INDEX IF EXISTS idx_bus_followups_school_student;
DROP INDEX IF EXISTS idx_bus_followups_school_id;
DROP INDEX IF EXISTS idx_bus_events_created_at;
DROP INDEX IF EXISTS idx_bus_events_school_student;
DROP INDEX IF EXISTS idx_bus_events_school_id;
DROP INDEX IF EXISTS idx_bell_schedules_created_at;
DROP INDEX IF EXISTS idx_bell_schedules_school_id;
DROP INDEX IF EXISTS idx_attendance_modes_created_at;
DROP INDEX IF EXISTS idx_attendance_modes_school_id;
DROP INDEX IF EXISTS idx_attendance_created_at;
DROP INDEX IF EXISTS idx_attendance_school_class;
DROP INDEX IF EXISTS idx_attendance_school_student;
DROP INDEX IF EXISTS idx_attendance_school_id;
DROP INDEX IF EXISTS idx_assoc_minutes_created_at;
DROP INDEX IF EXISTS idx_assoc_minutes_school_id;
DROP INDEX IF EXISTS idx_assets_created_at;
DROP INDEX IF EXISTS idx_assets_school_id;
DROP INDEX IF EXISTS idx_app_settings_created_at;
DROP INDEX IF EXISTS idx_announcements_created_at;
DROP INDEX IF EXISTS idx_announcements_school_id;
