-- Payesh migration 008: Wave 23 — advanced reporting (report_logs)
-- Immutable forward migration. Rollback: 008_wave23_report_logs.down.sql
--
-- WHY: Wave 23 adds ministry-standard reports with offline-first generation.
-- A report generated offline is journaled client-side in the new
-- «report_logs» collection and synced when the device comes back online
-- (the sync surface is model-driven: authz/model.json gained report_logs,
-- so server/sync.js accepts it — this migration gives PG-live mode the
-- matching table). Columns mirror server/schema.sql / migrate-to-pg rules:
--   kind    : attendance | academic | finance | teachers
--   format  : csv | pdf | screen
--   meta    : JSONB free-form parameters (jy/jm/class_id/term…)
--   status  : generated | synced
--   generated_by: user id as text (mirror of registered_by in safety_drills)
--
-- CONCURRENTLY is deliberately NOT used (same policy as 004/005/006/007):
-- migrations run inside a transaction and CREATE INDEX CONCURRENTLY cannot.
-- Apply by hand with CONCURRENTLY on a production database with live traffic.
BEGIN;
CREATE TABLE IF NOT EXISTS report_logs (
  "created_at" TIMESTAMPTZ,
  "format" VARCHAR(255),
  "generated_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "meta" JSONB,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_report_logs_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS idx_report_logs_school_id ON report_logs (school_id);
CREATE INDEX IF NOT EXISTS idx_report_logs_created_at ON report_logs (created_at DESC);
-- delta-pull surface (same policy as migrations 005/006): updated_at index
CREATE INDEX IF NOT EXISTS idx_report_logs_updated_at ON report_logs (updated_at);
COMMIT;
