-- Payesh migration 009: partition grades + attendance (Wave 10 — Database Scale)
-- Immutable forward migration. Rollback: 009_partition_grades_attendance.down.sql
--
-- WHY: grades ≈ 288M rows/yr and attendance ≈ 50M rows/yr (docs/CAPACITY_MODEL.md)
--   are the largest per-school transactional tables and time-oriented. RANGE
--   partitioning on created_at (yearly + DEFAULT) bounds every index and lets
--   retention become DETACH/ARCHIVE instead of million-row DELETEs. Full design
--   and the blocker analysis: docs/WAVE10_DB_SCALE.md §3.
--
-- BLOCKER FIX (Phase A — app side, already merged): persistOp now uses
--   UPDATE-then-INSERT for tables listed in PAYESH_PARTITIONED_TABLES, because
--   ON CONFLICT (id) cannot target the new PK (id, created_at) and the
--   (id, created_at) form silently breaks idempotency. Enable the env var for
--   these two tables when this migration is applied:
--     PAYESH_PARTITIONED_TABLES=grades,attendance
--
-- STRUCTURE — the four zero-downtime phases, as executable statements:
--   Phase B (build):   new *_p partitioned tables + yearly partitions + DEFAULT
--                      + all indexes (temp *_p_* names) + FKs + chg triggers
--                      + batched copy (id-range, 50k) + identity setval
--   Phase C (swap):    one transaction — rename old tables to *_old, old
--                      indexes/sequences to *_old_*, new ones to final names
--   Phase D (verify + drop): NOT in this file — run tests/partitioning.js,
--                      keep *_old for the bake period, then DROP manually
--                      (runbook: docs/WAVE10_DB_SCALE.md §7).
--   On a production database with live traffic, run B's statements split
--   (build+copy first, swap in a short maintenance window). In one
--   transaction it is correct but holds locks for the whole copy — that is
--   acceptable only in a maintenance window (same policy note as 005).
--
-- DATA RULES:
--   * rows with NULL created_at land at the epoch partition via
--     COALESCE(created_at, updated_at, epoch) — retained verbatim otherwise;
--     the new column is NOT NULL DEFAULT now() so app inserts are always
--     partitionable.
--   * chg_id (008) and version (004) columns are carried over verbatim.
--   * id uniqueness is no longer constraint-enforced (partitioned PK is
--     (id, created_at)); it is preserved by the identity sequence + the
--     app's UPDATE-then-INSERT upsert + the non-unique (id) index.
--
-- RERUN POLICY (idempotency):
--   * Statements are individually guarded (IF [NOT] EXISTS) and the copy
--     blocks skip themselves when *_p already holds rows — so a rerun after
--     a PARTIAL failure (crash before the swap) is safe.
--   * A rerun AFTER a completed swap is intentionally rejected: the swap
--     guard raises because *_old exists (leftover from the first run).
--     Resolve via 009.down (full rollback) or drop the *_old remnants
--     manually — never re-copy over a live swapped table.
BEGIN;

-- ═══════════════ Phase B — attendance ═══════════════
CREATE TABLE IF NOT EXISTS attendance_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exit_at" TIMESTAMPTZ,
  "exit_minutes" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "late_at" TIMESTAMPTZ,
  "late_minutes" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "taken_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at),
  CONSTRAINT fk_attendance_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM attendance;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'attendance_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF attendance_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('attendance_default') IS NULL THEN
    CREATE TABLE attendance_default PARTITION OF attendance_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_attendance_p_school_id       ON attendance_p (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_student  ON attendance_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class    ON attendance_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class_date ON attendance_p (school_id, class_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_p_created_at      ON attendance_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_p_updated_at      ON attendance_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_date_id  ON attendance_p (school_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_student_date_id ON attendance_p (student_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_chg_id          ON attendance_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_id              ON attendance_p (id);

DROP TRIGGER IF EXISTS trg_attendance_chg ON attendance_p;
CREATE TRIGGER trg_attendance_chg BEFORE INSERT OR UPDATE ON attendance_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

DO $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT;
  batch CONSTANT BIGINT := 50000;
BEGIN
  /* rerun-safety: اگر کپیِ قبلی انجام شده، دوباره درج نکن (PK می‌شکند) */
  IF NOT EXISTS (SELECT 1 FROM attendance_p LIMIT 1) THEN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM attendance;
  lo := minid;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO attendance_p ("class_id", "created_at", "date", "exit_at", "exit_minutes", "id",
                              "late_at", "late_minutes", "note", "school_id", "source", "status",
                              "student_id", "taken_at", "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exit_at", "exit_minutes", "id", "late_at", "late_minutes", "note", "school_id", "source",
           "status", "student_id", "taken_at", "updated_at", "version", "chg_id"
    FROM attendance WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
  END LOOP;
  END IF;
END $$;

SELECT setval(pg_get_serial_sequence('attendance_p', 'id'),
              COALESCE((SELECT MAX(id) FROM attendance_p), 0) + 1, false);

-- ═══════════════ Phase B — grades ═══════════════
CREATE TABLE IF NOT EXISTS grades_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exam_type" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "kind" VARCHAR(255),
  "max_score" VARCHAR(255),
  "school_id" INTEGER,
  "score" NUMERIC(12, 2),
  "source" VARCHAR(255),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "teacher_id" INTEGER,
  "term" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at),
  CONSTRAINT fk_grades_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM grades;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'grades_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF grades_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('grades_default') IS NULL THEN
    CREATE TABLE grades_default PARTITION OF grades_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_grades_p_school_id        ON grades_p (school_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student   ON grades_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_subject ON grades_p (school_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_class     ON grades_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_created_at       ON grades_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_updated_at       ON grades_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_id_id     ON grades_p (school_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_id ON grades_p (school_id, student_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_chg_id           ON grades_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_id               ON grades_p (id);

DROP TRIGGER IF EXISTS trg_grades_chg ON grades_p;
CREATE TRIGGER trg_grades_chg BEFORE INSERT OR UPDATE ON grades_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

DO $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT;
  batch CONSTANT BIGINT := 50000;
BEGIN
  /* rerun-safety: اگر کپیِ قبلی انجام شده، دوباره درج نکن (PK می‌شکند) */
  IF NOT EXISTS (SELECT 1 FROM grades_p LIMIT 1) THEN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM grades;
  lo := minid;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO grades_p ("class_id", "created_at", "date", "exam_type", "id",
                          "kind", "max_score", "school_id", "score", "source",
                          "student_id", "subject_id", "teacher_id", "term",
                          "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exam_type", "id", "kind", "max_score", "school_id",
           "score", "source", "student_id", "subject_id", "teacher_id", "term",
           "updated_at", "version", "chg_id"
    FROM grades WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
  END LOOP;
  END IF;
END $$;

SELECT setval(pg_get_serial_sequence('grades_p', 'id'),
              COALESCE((SELECT MAX(id) FROM grades_p), 0) + 1, false);

-- ═══════════════ Phase C — swap (جدول‌ها، ایندکس‌ها، سکوئنس‌ها؛ یک تراکنش) ═══════════════
DO $$
BEGIN
  IF EXISTS (SELECT FROM pg_class WHERE relname = 'attendance_old')
     OR EXISTS (SELECT FROM pg_class WHERE relname = 'grades_old') THEN
    RAISE EXCEPTION 'partition swap: *_old already exists — previous swap not cleaned up';
  END IF;
END $$;

ALTER TABLE attendance RENAME TO attendance_old;
ALTER TABLE grades RENAME TO grades_old;

ALTER INDEX idx_attendance_school_id        RENAME TO idx_attendance_old_school_id;
ALTER INDEX idx_attendance_school_student   RENAME TO idx_attendance_old_school_student;
ALTER INDEX idx_attendance_school_class     RENAME TO idx_attendance_old_school_class;
ALTER INDEX idx_attendance_school_class_date RENAME TO idx_attendance_old_school_class_date;
ALTER INDEX idx_attendance_created_at       RENAME TO idx_attendance_old_created_at;
ALTER INDEX idx_attendance_updated_at       RENAME TO idx_attendance_old_updated_at;
ALTER INDEX idx_attendance_school_date_id   RENAME TO idx_attendance_old_school_date_id;
ALTER INDEX idx_attendance_student_date_id  RENAME TO idx_attendance_old_student_date_id;
ALTER INDEX idx_attendance_chg_id           RENAME TO idx_attendance_old_chg_id;
ALTER SEQUENCE attendance_id_seq            RENAME TO attendance_old_id_seq;

ALTER INDEX idx_grades_school_id            RENAME TO idx_grades_old_school_id;
ALTER INDEX idx_grades_school_student       RENAME TO idx_grades_old_school_student;
ALTER INDEX idx_grades_school_student_subject RENAME TO idx_grades_old_school_student_subject;
ALTER INDEX idx_grades_school_class         RENAME TO idx_grades_old_school_class;
ALTER INDEX idx_grades_created_at           RENAME TO idx_grades_old_created_at;
ALTER INDEX idx_grades_updated_at           RENAME TO idx_grades_old_updated_at;
ALTER INDEX idx_grades_school_id_id         RENAME TO idx_grades_old_school_id_id;
ALTER INDEX idx_grades_school_student_id    RENAME TO idx_grades_old_school_student_id;
ALTER INDEX idx_grades_chg_id               RENAME TO idx_grades_old_chg_id;
ALTER SEQUENCE grades_id_seq                RENAME TO grades_old_id_seq;

ALTER TABLE attendance_p RENAME TO attendance;
ALTER TABLE grades_p RENAME TO grades;

ALTER INDEX idx_attendance_p_school_id       RENAME TO idx_attendance_school_id;
ALTER INDEX idx_attendance_p_school_student  RENAME TO idx_attendance_school_student;
ALTER INDEX idx_attendance_p_school_class    RENAME TO idx_attendance_school_class;
ALTER INDEX idx_attendance_p_school_class_date RENAME TO idx_attendance_school_class_date;
ALTER INDEX idx_attendance_p_created_at      RENAME TO idx_attendance_created_at;
ALTER INDEX idx_attendance_p_updated_at      RENAME TO idx_attendance_updated_at;
ALTER INDEX idx_attendance_p_school_date_id  RENAME TO idx_attendance_school_date_id;
ALTER INDEX idx_attendance_p_student_date_id RENAME TO idx_attendance_student_date_id;
ALTER INDEX idx_attendance_p_chg_id          RENAME TO idx_attendance_chg_id;
ALTER INDEX idx_attendance_p_id              RENAME TO idx_attendance_id;
ALTER SEQUENCE attendance_p_id_seq           RENAME TO attendance_id_seq;

ALTER INDEX idx_grades_p_school_id           RENAME TO idx_grades_school_id;
ALTER INDEX idx_grades_p_school_student      RENAME TO idx_grades_school_student;
ALTER INDEX idx_grades_p_school_student_subject RENAME TO idx_grades_school_student_subject;
ALTER INDEX idx_grades_p_school_class        RENAME TO idx_grades_school_class;
ALTER INDEX idx_grades_p_created_at          RENAME TO idx_grades_created_at;
ALTER INDEX idx_grades_p_updated_at          RENAME TO idx_grades_updated_at;
ALTER INDEX idx_grades_p_school_id_id        RENAME TO idx_grades_school_id_id;
ALTER INDEX idx_grades_p_school_student_id   RENAME TO idx_grades_school_student_id;
ALTER INDEX idx_grades_p_chg_id              RENAME TO idx_grades_chg_id;
ALTER INDEX idx_grades_p_id                  RENAME TO idx_grades_id;
ALTER SEQUENCE grades_p_id_seq               RENAME TO grades_id_seq;

COMMIT;
