-- Payesh migration 009: partition grades + attendance (Wave 10 — Database Scale)
-- Immutable forward migration. Rollback: 009_partition_grades_attendance.down.sql
--
-- WHY: grades ≈ 288M rows/yr and attendance ≈ 50M rows/yr (docs/CAPACITY_MODEL.md)
--   are the largest per-school transactional tables and time-oriented. RANGE
--   partitioning on created_at (yearly + DEFAULT) bounds every index and lets
--   retention become DETACH/ARCHIVE instead of million-row DELETEs. Full design
--   and the blocker analysis: docs/WAVE10_DB_SCALE.md §3.
--
-- BLOCKER FIX (Phase A — app side, already merged): persistOp now uses
--   UPDATE-then-INSERT for tables listed in PAYESH_PARTITIONED_TABLES, because
--   ON CONFLICT (id) cannot target the new PK (id, created_at) and the
--   (id, created_at) form silently breaks idempotency. Enable the env var for
--   these two tables when this migration is applied:
--     PAYESH_PARTITIONED_TABLES=grades,attendance
--
-- STRUCTURE — the four zero-downtime phases, as executable statements:
--   Phase B (build):   new *_p partitioned tables + yearly partitions + DEFAULT
--                      + all indexes (temp *_p_* names) + FKs + chg triggers
--                      + batched copy (id-range, 50k) + identity setval
--   Phase C (swap):    one transaction — rename old tables to *_old, old
--                      indexes/sequences to *_old_*, new ones to final names
--   Phase D (verify + drop): NOT in this file — run tests/partitioning.js,
--                      keep *_old for the bake period, then DROP manually
--                      (runbook: docs/WAVE10_DB_SCALE.md §7).
--   TWO TRANSACTIONS (staging finding, 2026-09-12): the long build+copy
--   transaction takes NO exclusive lock on the live tables (readers and
--   writers keep working); the short swap transaction (LOCK + catchup +
--   renames + COMMIT) is the only locking window. A concurrent-write probe
--   on 1.8M rows showed the single-transaction form stalls traffic for the
--   whole commit (~24s reads / ~42s writes) AND strands rows written during
--   the copy — the swap transaction now (a) re-copies the delta under
--   ACCESS EXCLUSIVE locks via a (id, created_at, chg_id) anti-join upsert
--   (chg_id from 008 marks every change), and (b) commits in ~a second.
--   Hard DELETEs during the window would resurrect — freeze them (soft
--   delete/tombstone is the app rule anyway).
--
-- DATA RULES:
--   * rows with NULL created_at land at the epoch partition via
--     COALESCE(created_at, updated_at, epoch) — retained verbatim otherwise;
--     the new column is NOT NULL DEFAULT now() so app inserts are always
--     partitionable.
--   * chg_id (008) and version (004) columns are carried over verbatim.
--   * id uniqueness is no longer constraint-enforced (partitioned PK is
--     (id, created_at)); it is preserved by the identity sequence + the
--     app's UPDATE-then-INSERT upsert + the non-unique (id) index.
--
-- RERUN POLICY (idempotency):
--   * Statements are individually guarded (IF [NOT] EXISTS) and the copy
--     blocks skip themselves when *_p already holds rows — so a rerun after
--     a PARTIAL failure (crash before the swap) is safe.
--   * A rerun AFTER a completed swap is intentionally rejected: the swap
--     guard raises because *_old exists (leftover from the first run).
--     Resolve via 009.down (full rollback) or drop the *_old remnants
--     manually — never re-copy over a live swapped table.
BEGIN;

-- ═══════════════ Phase B — attendance ═══════════════
CREATE TABLE IF NOT EXISTS attendance_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exit_at" TIMESTAMPTZ,
  "exit_minutes" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "late_at" TIMESTAMPTZ,
  "late_minutes" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "taken_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at),
  CONSTRAINT fk_attendance_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM attendance;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'attendance_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF attendance_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('attendance_default') IS NULL THEN
    CREATE TABLE attendance_default PARTITION OF attendance_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_attendance_p_school_id       ON attendance_p (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_student  ON attendance_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class    ON attendance_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class_date ON attendance_p (school_id, class_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_p_created_at      ON attendance_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_p_updated_at      ON attendance_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_date_id  ON attendance_p (school_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_student_date_id ON attendance_p (student_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_chg_id          ON attendance_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_id              ON attendance_p (id);

DROP TRIGGER IF EXISTS trg_attendance_chg ON attendance_p;
CREATE TRIGGER trg_attendance_chg BEFORE INSERT OR UPDATE ON attendance_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

/* تریگر حینِ کپی خاموش است (یافتهٔ استیجینگ ۲۰۲۶-۰۹-۱۲): payesh_chg_bump
   غیرمشروط است و کپی را هم nextval می‌زد — chg_id سطرهای کپی‌شده عوض می‌شد
   (نمونهٔ اندازه‌گیری: 500007 → 13000626)، ضدالحاقِ کچ‌آپِ فازِ C همهٔ جدول را
   «تغییرکرده» می‌دید و کلِ آن را زیرِ قفلِ انحصاری آپسرت می‌کرد (~۴۹s روی
   600k سطر؛ روی 50M فاجعه). با تریگرِ خاموش، کپی chg_id را عیناً حفظ
   می‌کند و کچ‌آپ فقط سرگردان‌های حقیقی را می‌گیرد. */
ALTER TABLE attendance_p DISABLE TRIGGER trg_attendance_chg;

DO $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT;
  batch CONSTANT BIGINT := 50000;
BEGIN
  /* rerun-safety: اگر کپیِ قبلی انجام شده، دوباره درج نکن (PK می‌شکند) */
  IF NOT EXISTS (SELECT 1 FROM attendance_p LIMIT 1) THEN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM attendance;
  lo := minid;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO attendance_p ("class_id", "created_at", "date", "exit_at", "exit_minutes", "id",
                              "late_at", "late_minutes", "note", "school_id", "source", "status",
                              "student_id", "taken_at", "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exit_at", "exit_minutes", "id", "late_at", "late_minutes", "note", "school_id", "source",
           "status", "student_id", "taken_at", "updated_at", "version", "chg_id"
    FROM attendance WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
  END LOOP;
  END IF;
END $$;

ALTER TABLE attendance_p ENABLE TRIGGER trg_attendance_chg;

SELECT setval(pg_get_serial_sequence('attendance_p', 'id'),
              COALESCE((SELECT MAX(id) FROM attendance_p), 0) + 1, false);

-- ═══════════════ Phase B — grades ═══════════════
CREATE TABLE IF NOT EXISTS grades_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exam_type" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "kind" VARCHAR(255),
  "max_score" VARCHAR(255),
  "school_id" INTEGER,
  "score" NUMERIC(12, 2),
  "source" VARCHAR(255),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "teacher_id" INTEGER,
  "term" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at),
  CONSTRAINT fk_grades_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM grades;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'grades_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF grades_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('grades_default') IS NULL THEN
    CREATE TABLE grades_default PARTITION OF grades_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_grades_p_school_id        ON grades_p (school_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student   ON grades_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_subject ON grades_p (school_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_class     ON grades_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_created_at       ON grades_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_updated_at       ON grades_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_id_id     ON grades_p (school_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_id ON grades_p (school_id, student_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_chg_id           ON grades_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_id               ON grades_p (id);

DROP TRIGGER IF EXISTS trg_grades_chg ON grades_p;
CREATE TRIGGER trg_grades_chg BEFORE INSERT OR UPDATE ON grades_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

/* همان یافتهٔ attendance: تریگر حینِ کپی خاموش تا chg_id حفظ شود. */
ALTER TABLE grades_p DISABLE TRIGGER trg_grades_chg;

DO $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT;
  batch CONSTANT BIGINT := 50000;
BEGIN
  /* rerun-safety: اگر کپیِ قبلی انجام شده، دوباره درج نکن (PK می‌شکند) */
  IF NOT EXISTS (SELECT 1 FROM grades_p LIMIT 1) THEN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM grades;
  lo := minid;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO grades_p ("class_id", "created_at", "date", "exam_type", "id",
                          "kind", "max_score", "school_id", "score", "source",
                          "student_id", "subject_id", "teacher_id", "term",
                          "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exam_type", "id", "kind", "max_score", "school_id",
           "score", "source", "student_id", "subject_id", "teacher_id", "term",
           "updated_at", "version", "chg_id"
    FROM grades WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
  END LOOP;
  END IF;
END $$;

ALTER TABLE grades_p ENABLE TRIGGER trg_grades_chg;

SELECT setval(pg_get_serial_sequence('grades_p', 'id'),
              COALESCE((SELECT MAX(id) FROM grades_p), 0) + 1, false);

-- ═══════════════ Phase C — swap (جدول‌ها، ایندکس‌ها، سکوئنس‌ها) ═══════════════
-- دو تراکنش (یافتهٔ استیجینگ ۲۰۲۶-۰۹-۱۲): تراکنشِ بلندِ ساخت+کپی هیچ قفلِ
-- انحصاری روی جدولِ زنده نمی‌گیرد؛ پنجرهٔ قفل فقط تراکنشِ دوم است — و چون
-- این تراکنشِ کوچک است، کامیتش هم کوتاه است. در حالتِ تک‌تراکنشِ قبلی،
-- پنجرهٔ قفل تا کامیتِ ۱.۲M سطری طول می‌کشید (اندازه‌گیری‌شده: ~۲۴s خواندن).
COMMIT;

/* آمارِ پلن‌ساز قبل از پنجرهٔ قفل (یافتهٔ استیجینگ): جدولِ تازه‌کپی‌شده بدونِ
   ANALYZE است و کچ‌آپِ ضدالحاقی به‌جای Hash Anti-Join ممکن است Nested-Loop
   بگیرد — پنجرهٔ قفل به‌جای ~۱s تا ~۶۷s طول می‌کشید. ANALYZE فقط
   ShareUpdateExclusive می‌گیرد و ترافیک را نمی‌بندد. */
ANALYZE attendance_p;
ANALYZE grades_p;

/* پنجرهٔ کوتاه: قفلِ انحصاری هر دو جدول زنده — نوبت‌گیری با ترافیکِ در حالِ
   اجرا اما بدون گرسنگی (صفِ قفل FIFO است). */
BEGIN;
LOCK TABLE attendance IN ACCESS EXCLUSIVE MODE;
LOCK TABLE grades IN ACCESS EXCLUSIVE MODE;

/* ── کچ‌آپِ نوشته‌های حینِ کپی (چرا لازم است؟) ──
   کپیِ Phase A/B با snapshot عبارت‌خودش کار می‌کند؛ هر درج/به‌روزرسانی‌ای که
   بینِ آن و اینجا روی جدولِ زنده بنشیند، فقط در هیپِ قدیمی است و بعد از
   swap در *_old اسیر می‌شد (اندازه‌گیریِ استیجینگ: با ترافیکِ 250ms، ۱۵ درج
   + ۱۵ به‌روزرسانی اسیر شد). اینجا، زیرِ قفلِ انحصاری و با snapshot تازهٔ
   هر عبارت (READ COMMITTED)، هر سطرِ «جدید یا با chg_id تازه» آپsert
   می‌شود: ضدالحاقِ (id, created_at) با شرطِ تازگیِ chg_id — سطرِ old فقط
   وقتی ادغام می‌شود که نو نداشته باشیم یا chg_id نو کهنه‌تر از old باشد
   (سکوئنسِ سراسری = ترتیبِ کاملِ نوشتن‌ها ⇒ last-writer-wins). شرطِ تساوی
   خطرناک بود: نوشتهٔ تازهٔ پس از swap روی جدولِ نو را نسخهٔ کهنهٔ old
   بازنویسی می‌کرد (یافتهٔ استیجینگ). حذفِ سخت (hard DELETE) حینِ پنجره
   سمتِ اپ نادر/ممنوع است (حذفِ نرم/سنگ‌قبر قاعده است) — چنین سطری
   بازمی‌گردد؛ در پنجرهٔ نگهداری فریز کنید اگر حذفِ سخت لازم است. */
INSERT INTO attendance_p ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                          "id", "late_at", "late_minutes", "note", "school_id",
                          "source", "status", "student_id", "taken_at",
                          "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
       o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
FROM attendance o
WHERE NOT EXISTS (SELECT 1 FROM attendance_p p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
  "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
  "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
  "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
  "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

INSERT INTO grades_p ("class_id", "created_at", "date", "exam_type", "id",
                      "kind", "max_score", "school_id", "score", "source",
                      "student_id", "subject_id", "teacher_id", "term",
                      "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exam_type", o."id", o."kind", o."max_score", o."school_id",
       o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
       o."updated_at", o."version", o."chg_id"
FROM grades o
WHERE NOT EXISTS (SELECT 1 FROM grades_p p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
  "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
  "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
  "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

DO $$
BEGIN
  IF EXISTS (SELECT FROM pg_class WHERE relname = 'attendance_old')
     OR EXISTS (SELECT FROM pg_class WHERE relname = 'grades_old') THEN
    RAISE EXCEPTION 'partition swap: *_old already exists — previous swap not cleaned up';
  END IF;
END $$;

ALTER TABLE attendance RENAME TO attendance_old;
ALTER TABLE grades RENAME TO grades_old;

ALTER INDEX idx_attendance_school_id        RENAME TO idx_attendance_old_school_id;
ALTER INDEX idx_attendance_school_student   RENAME TO idx_attendance_old_school_student;
ALTER INDEX idx_attendance_school_class     RENAME TO idx_attendance_old_school_class;
ALTER INDEX idx_attendance_school_class_date RENAME TO idx_attendance_old_school_class_date;
ALTER INDEX idx_attendance_created_at       RENAME TO idx_attendance_old_created_at;
ALTER INDEX idx_attendance_updated_at       RENAME TO idx_attendance_old_updated_at;
ALTER INDEX idx_attendance_school_date_id   RENAME TO idx_attendance_old_school_date_id;
ALTER INDEX idx_attendance_student_date_id  RENAME TO idx_attendance_old_student_date_id;
ALTER INDEX idx_attendance_chg_id           RENAME TO idx_attendance_old_chg_id;
ALTER SEQUENCE attendance_id_seq            RENAME TO attendance_old_id_seq;

ALTER INDEX idx_grades_school_id            RENAME TO idx_grades_old_school_id;
ALTER INDEX idx_grades_school_student       RENAME TO idx_grades_old_school_student;
ALTER INDEX idx_grades_school_student_subject RENAME TO idx_grades_old_school_student_subject;
ALTER INDEX idx_grades_school_class         RENAME TO idx_grades_old_school_class;
ALTER INDEX idx_grades_created_at           RENAME TO idx_grades_old_created_at;
ALTER INDEX idx_grades_updated_at           RENAME TO idx_grades_old_updated_at;
ALTER INDEX idx_grades_school_id_id         RENAME TO idx_grades_old_school_id_id;
ALTER INDEX idx_grades_school_student_id    RENAME TO idx_grades_old_school_student_id;
ALTER INDEX idx_grades_chg_id               RENAME TO idx_grades_old_chg_id;
ALTER SEQUENCE grades_id_seq                RENAME TO grades_old_id_seq;

ALTER TABLE attendance_p RENAME TO attendance;
ALTER TABLE grades_p RENAME TO grades;

ALTER INDEX idx_attendance_p_school_id       RENAME TO idx_attendance_school_id;
ALTER INDEX idx_attendance_p_school_student  RENAME TO idx_attendance_school_student;
ALTER INDEX idx_attendance_p_school_class    RENAME TO idx_attendance_school_class;
ALTER INDEX idx_attendance_p_school_class_date RENAME TO idx_attendance_school_class_date;
ALTER INDEX idx_attendance_p_created_at      RENAME TO idx_attendance_created_at;
ALTER INDEX idx_attendance_p_updated_at      RENAME TO idx_attendance_updated_at;
ALTER INDEX idx_attendance_p_school_date_id  RENAME TO idx_attendance_school_date_id;
ALTER INDEX idx_attendance_p_student_date_id RENAME TO idx_attendance_student_date_id;
ALTER INDEX idx_attendance_p_chg_id          RENAME TO idx_attendance_chg_id;
ALTER INDEX idx_attendance_p_id              RENAME TO idx_attendance_id;
ALTER SEQUENCE attendance_p_id_seq           RENAME TO attendance_id_seq;

ALTER INDEX idx_grades_p_school_id           RENAME TO idx_grades_school_id;
ALTER INDEX idx_grades_p_school_student      RENAME TO idx_grades_school_student;
ALTER INDEX idx_grades_p_school_student_subject RENAME TO idx_grades_school_student_subject;
ALTER INDEX idx_grades_p_school_class        RENAME TO idx_grades_school_class;
ALTER INDEX idx_grades_p_created_at          RENAME TO idx_grades_created_at;
ALTER INDEX idx_grades_p_updated_at          RENAME TO idx_grades_updated_at;
ALTER INDEX idx_grades_p_school_id_id        RENAME TO idx_grades_school_id_id;
ALTER INDEX idx_grades_p_school_student_id   RENAME TO idx_grades_school_student_id;
ALTER INDEX idx_grades_p_chg_id              RENAME TO idx_grades_chg_id;
ALTER INDEX idx_grades_p_id                  RENAME TO idx_grades_id;
ALTER SEQUENCE grades_p_id_seq               RENAME TO grades_id_seq;

COMMIT;

/* ═══════════════ Phase D — stray-merge (پس از کامیتِ swap؛ idempotent) ═══════════════
   نویسنده‌ای که عبارتش دقیقاً حینِ پنجرهٔ قفل بلاک شده بود، پس از بیداری روی
   OID قدیمی (اکنون *_old) اجرا می‌شود — چون تحلیلِ نام پیش از بلاک رخ داده.
   همین ادغامِ ضدالحاقی سطرهایش را برمی‌گرداند؛ دوباره‌اجرا بی‌اثر است.
   دو پاسِ پشت‌سرهم اجرا می‌شود (بیداریِ نویسنده‌های بلاک و کامیتِشان
   میکروثانیه است؛ پاسِ دوم قطعی می‌گیرد). راستی‌آزماییِ پس از مهاجرت:
   SELECT count(*) FROM grades_old o WHERE NOT EXISTS (SELECT 1 FROM grades n
   WHERE n.id=o.id AND n.created_at=o.created_at AND n.chg_id >= o.chg_id);  ⇒ 0 */
-- STRAY-MERGE:BEGIN
INSERT INTO attendance ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                          "id", "late_at", "late_minutes", "note", "school_id",
                          "source", "status", "student_id", "taken_at",
                          "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
       o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
FROM attendance_old o
WHERE NOT EXISTS (SELECT 1 FROM attendance p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
  "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
  "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
  "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
  "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

INSERT INTO grades ("class_id", "created_at", "date", "exam_type", "id",
                      "kind", "max_score", "school_id", "score", "source",
                      "student_id", "subject_id", "teacher_id", "term",
                      "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exam_type", o."id", o."kind", o."max_score", o."school_id",
       o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
       o."updated_at", o."version", o."chg_id"
FROM grades_old o
WHERE NOT EXISTS (SELECT 1 FROM grades p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
  "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
  "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
  "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

/* پاسِ دوم: نویسنده‌های بلاک‌شدهٔ لحظهٔ swap در لحظهٔ رهاشدنِ قفل بیدار
   می‌شوند و در میکروثانیه کامیت می‌کنند — پاسِ اول ممکن است هم‌زمانِ
   بیداری‌شان باشد و پاسِ دوم آن‌ها را قطعی بگیرد. دوباره‌اجرا بی‌اثر است. */

INSERT INTO attendance ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                          "id", "late_at", "late_minutes", "note", "school_id",
                          "source", "status", "student_id", "taken_at",
                          "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
       o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
FROM attendance_old o
WHERE NOT EXISTS (SELECT 1 FROM attendance p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
  "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
  "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
  "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
  "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

INSERT INTO grades ("class_id", "created_at", "date", "exam_type", "id",
                      "kind", "max_score", "school_id", "score", "source",
                      "student_id", "subject_id", "teacher_id", "term",
                      "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exam_type", o."id", o."kind", o."max_score", o."school_id",
       o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
       o."updated_at", o."version", o."chg_id"
FROM grades_old o
WHERE NOT EXISTS (SELECT 1 FROM grades p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
  "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
  "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
  "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";
-- STRAY-MERGE:END
