-- Payesh migration 009: partition grades + attendance (Wave 10 — Database Scale)
-- Immutable forward migration. Rollback: 009_partition_grades_attendance.down.sql
--
-- WHY: grades ≈ 288M rows/yr and attendance ≈ 50M rows/yr (docs/CAPACITY_MODEL.md)
--   are the largest per-school transactional tables and time-oriented. RANGE
--   partitioning on created_at (yearly + DEFAULT) bounds every index and lets
--   retention become DETACH/ARCHIVE instead of million-row DELETEs. Full design
--   and the blocker analysis: docs/WAVE10_DB_SCALE.md §3.
--
-- BLOCKER FIX (Phase A — app side, already merged): persistOp now uses
--   UPDATE-then-INSERT for tables listed in PAYESH_PARTITIONED_TABLES, because
--   ON CONFLICT (id) cannot target the new PK (id, created_at) and the
--   (id, created_at) form silently breaks idempotency. Enable the env var for
--   these two tables when this migration is applied:
--     PAYESH_PARTITIONED_TABLES=grades,attendance
--
-- STRUCTURE — the four zero-downtime phases, as executable statements:
--   Phase B (build):   new *_p partitioned tables + yearly partitions + DEFAULT
--                      + all indexes (temp *_p_* names) + FKs + chg triggers
--                      + batched copy (id-range, 50k) + identity setval
--   Phase C (swap):    one transaction — rename old tables to *_old, old
--                      indexes/sequences to *_old_*, new ones to final names
--   Phase D (verify + drop): NOT in this file — run tests/partitioning.js,
--                      keep *_old for the bake period, then DROP manually
--                      (runbook: docs/WAVE10_DB_SCALE.md §7).
--   TWO TRANSACTIONS (staging finding, 2026-09-12): the long build+copy
--   transaction takes NO exclusive lock on the live tables (readers and
--   writers keep working); the short swap transaction (LOCK + catchup +
--   renames + COMMIT) is the only locking window. A concurrent-write probe
--   on 1.8M rows showed the single-transaction form stalls traffic for the
--   whole commit (~24s reads / ~42s writes) AND strands rows written during
--   the copy — the swap transaction now (a) re-copies the delta under
--   ACCESS EXCLUSIVE locks via a (id, created_at, chg_id) anti-join upsert
--   (chg_id from 008 marks every change), and (b) commits in ~a second.
--   Hard DELETEs during the window would resurrect — freeze them (soft
--   delete/tombstone is the app rule anyway).
--
-- DATA RULES:
--   * rows with NULL created_at land at the epoch partition via
--     COALESCE(created_at, updated_at, epoch) — retained verbatim otherwise;
--     the new column is NOT NULL DEFAULT now() so app inserts are always
--     partitionable.
--   * chg_id (008) and version (004) columns are carried over verbatim.
--   * id uniqueness is no longer constraint-enforced (partitioned PK is
--     (id, created_at)); it is preserved by the identity sequence + the
--     app's UPDATE-then-INSERT upsert + the non-unique (id) index.
--
-- RERUN POLICY (idempotency):
--   * Statements are individually guarded (IF [NOT] EXISTS) and the copy
--     blocks skip themselves when *_p already holds rows — so a rerun after
--     a PARTIAL failure (crash before the swap) is safe.
--   * A rerun AFTER a completed swap is intentionally rejected: the swap
--     guard raises because *_old exists (leftover from the first run).
--     Resolve via 009.down (full rollback) or drop the *_old remnants
--     manually — never re-copy over a live swapped table.
--   * کپی با PROCEDURE های chunk-commit اجرا می‌شود (هر ۲M سطر COMMIT —
--     یافتهٔ مانورِ ۲۵M: تک‌تراکنش ۱.۳GB حافظه می‌بلعید) و از MAX(id)
--     ازسرگیری می‌کند؛ عبارت‌هایِ فازِ B هرکدام تراکنشِ خودشان را دارند.

-- ═══════════════ Phase B — attendance ═══════════════
-- Idempotent re-run protocol (Chat 2 remediation): when the partition swap is
-- already in place, this migration declares ALREADY_APPLIED instead of failing
-- half-way. The Node runner (tools/seed-relational-small.js) understands this
-- sentinel and tolerates it like `already exists`. A psql RE-run intentionally
-- errors with the same clear message (first-time runs are unaffected).
DO $guard$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname IN ('attendance','grades') AND relkind = 'p') THEN
    RAISE EXCEPTION 'ALREADY_APPLIED: migration 012 partition swap is already in place';
  END IF;
END
$guard$;

CREATE TABLE IF NOT EXISTS attendance_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exit_at" TIMESTAMPTZ,
  "exit_minutes" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "late_at" TIMESTAMPTZ,
  "late_minutes" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "taken_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at)
  /* FK عمداً اینجا نیست (یافتهٔ مانورِ ۲۵M سطر، ۲۰۲۶-۰۹-۱۲): FKِ داخلِ
     CREATE داخلِ تراکنشِ کپی، SHARE ROW EXCLUSIVE رویِ جدولِ والد
     (users/schools/…) تا کامیتِ کپی نگه می‌دارد ⇒ نوشتنِ رویِ والد برایِ
     کلِ مدتِ کپی بلاک می‌شد — در ۲۵M سطر: دقیقه‌ها. FKها با ALTER رویِ
     جدولِ خالی ساخته می‌شوند (بخشِ grades پایین‌تر). */
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM attendance;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'attendance_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF attendance_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('attendance_default') IS NULL THEN
    CREATE TABLE attendance_default PARTITION OF attendance_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_attendance_p_school_id       ON attendance_p (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_student  ON attendance_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class    ON attendance_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_class_date ON attendance_p (school_id, class_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_p_created_at      ON attendance_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_p_updated_at      ON attendance_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_attendance_p_school_date_id  ON attendance_p (school_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_student_date_id ON attendance_p (student_id, date DESC, id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_chg_id          ON attendance_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_attendance_p_id              ON attendance_p (id);

DROP TRIGGER IF EXISTS trg_attendance_chg ON attendance_p;
CREATE TRIGGER trg_attendance_chg BEFORE INSERT OR UPDATE ON attendance_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

/* تریگر حینِ کپی خاموش است (یافتهٔ استیجینگ ۲۰۲۶-۰۹-۱۲): payesh_chg_bump
   غیرمشروط است و کپی را هم nextval می‌زد — chg_id سطرهای کپی‌شده عوض می‌شد
   (نمونهٔ اندازه‌گیری: 500007 → 13000626)، ضدالحاقِ کچ‌آپِ فازِ C همهٔ جدول را
   «تغییرکرده» می‌دید و کلِ آن را زیرِ قفلِ انحصاری آپسرت می‌کرد (~۴۹s روی
   600k سطر؛ روی 50M فاجعه). با تریگرِ خاموش، کپی chg_id را عیناً حفظ
   می‌کند و کچ‌آپ فقط سرگردان‌های حقیقی را می‌گیرد. */
/* ═══ FK رویِ جدولِ خالی، قبل از کپی (یافتهٔ مانورِ ۲۵M سطر، ۲۰۲۶-۰۹-۱۲) ═══
   نسخهٔ اولیهٔ این مهاجرت FK را داخلِ CREATE TABLE می‌ساخت داخلِ همان
   تراکنشِ کپی ⇒ قفلِ SHARE ROW EXCLUSIVE رویِ جدول‌هایِ والد (users/
   schools/classes/subjects) تا کامیتِ کپی نگه داشته می‌شد ⇒ هر نوشتنِ رویِ
   والد (ساختِ کاربر/کلاس/…) برایِ کلِ مدتِ کپی بلاک بود — در ۲۵M سطر:
   دقیقه‌ها. NOT VALID هم رویِ جدولِ partitioned مجاز نیست (محدودیتِ PG 17).
   الگویِ درست: ADD CONSTRAINT رویِ جدولِ خالی (اعتبارسنجی آنی، قفلِ والد
   میلی‌ثانیه‌ای) و بعد کپی — چکِ FK سطربه‌سطر حینِ کپی انجام می‌شود و
   قفلِ سطریِ key-share با نوشتنِ سطرهایِ نوِ والد تعارض ندارد. */
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_school' AND conrelid = 'attendance_p'::regclass) THEN
    EXECUTE 'ALTER TABLE attendance_p ADD CONSTRAINT fk_attendance_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
  END IF;
END $$;

ALTER TABLE attendance_p DISABLE TRIGGER trg_attendance_chg;

/* ── نشانگرِ chg آغازِ کپی (یافتهٔ مانورِ ۲۵M: پنجرهٔ swap ~۳۶s) ──
   کچ‌آپِ فازِ C زیرِ ACCESS EXCLUSIVE فقط باید سطرهایی را ببیند که بعد از
   آغازِ کپی تغییر کرده‌اند — نه کلِ جدول را. هر نوشتهٔ آینده chg_id تازه‌ای
   از سکوئنسِ سراسری می‌گیرد که از بیشینهٔ فعلی بزرگ‌تر است؛ مرزِ w0 یک‌بار
   ثبت می‌شود (ON CONFLICT DO NOTHING ⇒ رانِ ازسرگیری‌شده پس از کرش، مرزِ
   اصلی را حفظ می‌کند — مرزِ دیرتر ناامن بود: نوشته‌های بینِ دو ران گم
   می‌شدند) و کچ‌آپِ فازِ C با ایندکسِ chg_id فقط بالایِ مرز را اسکن
   می‌کند: پنجرهٔ قفل با تعدادِ سرگردان‌ها مقیاس می‌یابد، نه با اندازهٔ
   جدول. سطرهای chg_id NULL (که نباید وجود داشته باشند) محافظانهً
   کاندیدا می‌شوند. */
CREATE TABLE IF NOT EXISTS mig009_w0 (id INT PRIMARY KEY, w0 BIGINT NOT NULL, at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO mig009_w0 (id, w0)
SELECT 1, GREATEST(COALESCE((SELECT MAX(chg_id) FROM grades), 0),
                   COALESCE((SELECT MAX(chg_id) FROM attendance), 0))
ON CONFLICT (id) DO NOTHING;

/* کپیِ chunk-commit (یافتهٔ مانورِ ۲۵M سطر، ۲۰۲۶-۰۹-۱۲): کپیِ تک‌تراکنشه
   به‌ازایِ هر سطر ~۵۰B حافظهٔ bookkeeping انباشته می‌کند — در ۲۵M سطر =
   1.3GB و OOM-kill رویِ میزبانِ 2GB. اینجا هر ۳ دستهٔ ۵۰k (=۱۵۰k سطر ≈
   ۷.۵MB حافظه) COMMIT می‌شود و از MAX(id) ازسرگیری می‌شود: کرشِ وسطِ کپی
   ⇒ رانِ بعدی از مرزِ چانکِ کامیت‌شده ادامه می‌دهد (تستِ L11). */
CREATE OR REPLACE PROCEDURE payesh_copy_attendance_009()
LANGUAGE plpgsql AS $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT; nb BIGINT := 0;
  batch CONSTANT BIGINT := 50000;
  per_commit CONSTANT BIGINT := 3; /* ×۵۰k = ۱۵۰k سطر ⇒ ~۷.۵MB حافظه/چانک */
BEGIN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM attendance;
  SELECT GREATEST(minid, COALESCE((SELECT MAX(id) FROM attendance_p), 0) + 1) INTO lo;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO attendance_p ("class_id", "created_at", "date", "exit_at", "exit_minutes", "id",
                              "late_at", "late_minutes", "note", "school_id", "source", "status",
                              "student_id", "taken_at", "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exit_at", "exit_minutes", "id", "late_at", "late_minutes", "note", "school_id", "source",
           "status", "student_id", "taken_at", "updated_at", "version", "chg_id"
    FROM attendance WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
    nb := nb + 1;
    IF nb % per_commit = 0 THEN
      RAISE NOTICE 'copy attendance: تا id %', hi2;
      COMMIT;
    END IF;
  END LOOP;
  COMMIT;
END $$;

CALL payesh_copy_attendance_009();
DROP PROCEDURE payesh_copy_attendance_009();

ALTER TABLE attendance_p ENABLE TRIGGER trg_attendance_chg;

SELECT setval(pg_get_serial_sequence('attendance_p', 'id'),
              COALESCE((SELECT MAX(id) FROM attendance_p), 0) + 1, false);

-- ═══════════════ Phase B — grades ═══════════════
CREATE TABLE IF NOT EXISTS grades_p (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "date" VARCHAR(50),
  "exam_type" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "kind" VARCHAR(255),
  "max_score" VARCHAR(255),
  "school_id" INTEGER,
  "score" NUMERIC(12, 2),
  "source" VARCHAR(255),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "teacher_id" INTEGER,
  "term" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "version" INTEGER NOT NULL DEFAULT 1,
  "chg_id" BIGINT,
  PRIMARY KEY (id, created_at)
  /* FKها عمداً اینجا نیستند — یافتهٔ مانورِ ۲۵M: قفلِ SHARE ROW EXCLUSIVE
     رویِ جدول‌هایِ والد تا کامیتِ کپی. با ALTER رویِ جدولِ خالی ساخته
     می‌شوند (بلافاصله بالاتر). */
) PARTITION BY RANGE (created_at);

DO $$
DECLARE
  lo INT; hi INT; y INT; nm TEXT;
BEGIN
  SELECT LEAST(EXTRACT(YEAR FROM COALESCE(MIN(created_at), now()))::INT,
               EXTRACT(YEAR FROM now())::INT - 1)
    INTO lo FROM grades;
  hi := EXTRACT(YEAR FROM now())::INT + 1;
  FOR y IN lo..hi LOOP
    nm := 'grades_y' || y;
    IF NOT EXISTS (SELECT FROM pg_class WHERE relname = nm) THEN
      EXECUTE format('CREATE TABLE %I PARTITION OF grades_p FOR VALUES FROM (%L) TO (%L)',
                     nm, make_date(y, 1, 1), make_date(y + 1, 1, 1));
    END IF;
  END LOOP;
  IF to_regclass('grades_default') IS NULL THEN
    CREATE TABLE grades_default PARTITION OF grades_p DEFAULT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_grades_p_school_id        ON grades_p (school_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student   ON grades_p (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_subject ON grades_p (school_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_class     ON grades_p (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_created_at       ON grades_p (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_updated_at       ON grades_p (updated_at);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_id_id     ON grades_p (school_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_school_student_id ON grades_p (school_id, student_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_grades_p_chg_id           ON grades_p (chg_id);
CREATE INDEX IF NOT EXISTS idx_grades_p_id               ON grades_p (id);

DROP TRIGGER IF EXISTS trg_grades_chg ON grades_p;
CREATE TRIGGER trg_grades_chg BEFORE INSERT OR UPDATE ON grades_p
  FOR EACH ROW EXECUTE FUNCTION payesh_chg_bump();

/* همان یافتهٔ attendance: تریگر حینِ کپی خاموش تا chg_id حفظ شود. */
DO $$
DECLARE
  fk RECORD;
BEGIN
  FOR fk IN SELECT * FROM (VALUES
    ('fk_grades_school',  'ALTER TABLE grades_p ADD CONSTRAINT fk_grades_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED'),
    ('fk_grades_student', 'ALTER TABLE grades_p ADD CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED'),
    ('fk_grades_class',   'ALTER TABLE grades_p ADD CONSTRAINT fk_grades_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED'),
    ('fk_grades_subject', 'ALTER TABLE grades_p ADD CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED'),
    ('fk_grades_teacher', 'ALTER TABLE grades_p ADD CONSTRAINT fk_grades_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED')
  ) AS t(name, ddl)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = fk.name AND conrelid = 'grades_p'::regclass) THEN
      EXECUTE fk.ddl;
    END IF;
  END LOOP;
END $$;

ALTER TABLE grades_p DISABLE TRIGGER trg_grades_chg;

CREATE OR REPLACE PROCEDURE payesh_copy_grades_009()
LANGUAGE plpgsql AS $$
DECLARE
  minid BIGINT; maxid BIGINT; lo BIGINT; hi2 BIGINT; nb BIGINT := 0;
  batch CONSTANT BIGINT := 50000;
  per_commit CONSTANT BIGINT := 3; /* ×۵۰k = ۱۵۰k سطر ⇒ ~۷.۵MB حافظه/چانک */
BEGIN
  SELECT COALESCE(MIN(id), 0), COALESCE(MAX(id), 0) INTO minid, maxid FROM grades;
  SELECT GREATEST(minid, COALESCE((SELECT MAX(id) FROM grades_p), 0) + 1) INTO lo;
  WHILE lo <= maxid LOOP
    hi2 := LEAST(lo + batch, maxid);
    INSERT INTO grades_p ("class_id", "created_at", "date", "exam_type", "id",
                          "kind", "max_score", "school_id", "score", "source",
                          "student_id", "subject_id", "teacher_id", "term",
                          "updated_at", "version", "chg_id")
    SELECT "class_id", COALESCE("created_at", "updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), "date",
           "exam_type", "id", "kind", "max_score", "school_id",
           "score", "source", "student_id", "subject_id", "teacher_id", "term",
           "updated_at", "version", "chg_id"
    FROM grades WHERE id >= lo AND id <= hi2;
    lo := hi2 + 1;
    nb := nb + 1;
    IF nb % per_commit = 0 THEN
      RAISE NOTICE 'copy grades: تا id %', hi2;
      COMMIT;
    END IF;
  END LOOP;
  COMMIT;
END $$;

CALL payesh_copy_grades_009();
DROP PROCEDURE payesh_copy_grades_009();

ALTER TABLE grades_p ENABLE TRIGGER trg_grades_chg;

SELECT setval(pg_get_serial_sequence('grades_p', 'id'),
              COALESCE((SELECT MAX(id) FROM grades_p), 0) + 1, false);

/* آمارِ پلن‌ساز قبل از پنجرهٔ قفل (یافتهٔ استیجینگ): جدولِ تازه‌کپی‌شده بدونِ
   ANALYZE است و کچ‌آپِ ضدالحاقی به‌جای Hash Anti-Join ممکن است Nested-Loop
   بگیرد — پنجرهٔ قفل به‌جای ~۱s تا ~۶۷s طول می‌کشید. ANALYZE فقط
   ShareUpdateExclusive می‌گیرد و ترافیک را نمی‌بندد. */
ANALYZE attendance_p;
ANALYZE grades_p;

-- ═══════════════ Phase C — swap (جدول‌ها، ایندکس‌ها، سکوئنس‌ها) ═══════════════
-- تنها تراکنشِ قفل‌دار (یافتهٔ استیجینگ ۲۰۲۶-۰۹-۱۲): کپی با چانک‌هایِ
-- COMMIT شده بیرون از هر قفلِ انحصاری انجام شده؛ پنجرهٔ قفل فقط این
-- تراکنشِ کوچک است (LOCK + کچ‌آپ + rename) و کامیتش کوتاه. در حالتِ
-- تک‌تراکنشِ اولیه، پنجرهٔ قفل تا کامیتِ ۱.۲M سطری طول می‌کشید (~۲۴s خواندن).

/* پنجرهٔ کوتاه: قفلِ انحصاری هر دو جدول زنده — نوبت‌گیری با ترافیکِ در حالِ
   اجرا اما بدون گرسنگی (صفِ قفل FIFO است). */

/* مرزِ w0 به‌صورتِ ثابتِ زمانِ پلان (یافتهٔ رانِ چهارمِ مانورِ ۲۵M):
   همین پیشیکیت با زیرپلانِ اسکالری مثل (SELECT w0 FROM mig009_w0 …)
   بی‌اثر بود — مقدارِ زیرپلان در زمانِ پلان مجهول است ⇒ تخمینِ پیش‌فرضِ
   میلیون‌ها سطر (واقعیت: ~هزار) ⇒ planner به‌جای Nested-Loopِ ایندکسی،
   Hash Right Anti-Join می‌گیرد و کلِ جدولِ نو (۲۵M سطر، همهٔ پارتیشن‌ها)
   را زیرِ قفل Seq-Scan + Hash می‌کند — پنجرهٔ ۳۸.۸s با وجودِ ایندکسِ
   کاملاً سالم. اینجا مرز داخل DO-block از mig009_w0 خوانده و به‌صورتِ لیترالِ زمانِ پلان
   (format→%s) جایگذاری می‌شود — بدونِ هیچ متاکامندِ psql ⇒ تخمینِ دقیق ⇒ Bitmap Index Scan +
   Nested-Loop (EXPLAIN: هزینهٔ ~۳۴× کمتر). مقدار از نشانگرِ یک‌سطریِ
   بالای فایل می‌آید و بینِ این خواندن و تراکنشِ زیر تغییر نمی‌کند. */
-- P2 (Chat 2 remediation): psql-gset meta-command removed — the marker value is
-- planted as a plan-time literal through DO/dynamic-SQL blocks below (format→%s),
-- so this migration runs with ANY standard SQL client (psql AND the pg driver).
BEGIN;
LOCK TABLE attendance IN ACCESS EXCLUSIVE MODE;
LOCK TABLE grades IN ACCESS EXCLUSIVE MODE;

/* ── کچ‌آپِ نوشته‌های حینِ کپی (چرا لازم است؟) ──
   کپیِ Phase A/B با snapshot عبارت‌خودش کار می‌کند؛ هر درج/به‌روزرسانی‌ای که
   بینِ آن و اینجا روی جدولِ زنده بنشیند، فقط در هیپِ قدیمی است و بعد از
   swap در *_old اسیر می‌شد (اندازه‌گیریِ استیجینگ: با ترافیکِ 250ms، ۱۵ درج
   + ۱۵ به‌روزرسانی اسیر شد). اینجا، زیرِ قفلِ انحصاری و با snapshot تازهٔ
   هر عبارت (READ COMMITTED)، هر سطرِ «جدید یا با chg_id تازه» آپsert
   می‌شود: ضدالحاقِ (id, created_at) با شرطِ تازگیِ chg_id — سطرِ old فقط
   وقتی ادغام می‌شود که نو نداشته باشیم یا chg_id نو کهنه‌تر از old باشد
   (سکوئنسِ سراسری = ترتیبِ کاملِ نوشتن‌ها ⇒ last-writer-wins). شرطِ تساوی
   خطرناک بود: نوشتهٔ تازهٔ پس از swap روی جدولِ نو را نسخهٔ کهنهٔ old
   بازنویسی می‌کرد (یافتهٔ استیجینگ). حذفِ سخت (hard DELETE) حینِ پنجره
   سمتِ اپ نادر/ممنوع است (حذفِ نرم/سنگ‌قبر قاعده است) — چنین سطری
   بازمی‌گردد؛ در پنجرهٔ نگهداری فریز کنید اگر حذفِ سخت لازم است.
   ── پیشیکیتِ chg (یافتهٔ مانورِ ۲۵M): قبلاً این ضدالحاق کلِ جدولِ قدیمی
   را زیرِ قفل اسکن می‌کرد — در ۲۵M سطر پنجرهٔ swap ~۳۶s شد. حالا فقط
   سطرهایِ «بعد از آغازِ کپی تغییرکرده» (chg_id > w0؛ ثبتِ w0 در بالای
   فایل) کاندیدایند و اسکن با ایندکسِ chg_id انجام می‌شود ⇒ پنجرهٔ قفل
   با تعدادِ سرگردان‌ها مقیاس می‌یابد، نه با اندازهٔ جدول. صحت: هر نوشتهٔ
   پس از ثبتِ w0 chg تازه > w0 دارد (سکوئنسِ سراسری) و نوشتهٔ پیش از آن
   دیگر تغییر نمی‌کند ⇒ کپیِ نهاییِ همان سطر حکمفرماست.
   سطرهایِ chg_id NULL (به‌حکمِ ۰۰8 نباید وجود داشته باشند) در این اسکنِ
   ایندکسی نمی‌آیند — تورِ ایمنیِ آن‌ها فازِ D است (اسکنِ کاملِ بدونِ قفل
   بعد از swap؛ ضدالحاقِ آن، سطرِ NULL را هم می‌گیرد). عمداً بدونِ
   «OR IS NULL»: همان OR اسکنِ ایندکسی را به Seq Scanِ کامل تبدیل
   می‌کرد (تأییدِ EXPLAIN — یافتهٔ رانِ سومِ مانورِ ۲۵M). رانِ چهارم:
   حتی پیشیکیتِ ایندکسیِ سالم، با زیرپلانِ مجهول‌مقدار Hash Anti-Joinِ
   کلِ جدولِ نو را می‌ساخت — مرز باید ثابتِ زمانِ پلان باشد (DO-block بالا). */
DO $swap$
DECLARE
  w0 BIGINT;
BEGIN
  SELECT v.w0 INTO w0 FROM mig009_w0 v WHERE v.id = 1;
  IF w0 IS NULL THEN
    RAISE EXCEPTION 'partition swap: marker row mig009_w0(id=1) is missing';
  END IF;
  /* معنای psql-gsetِ قدیم: مرز به‌صورتِ لیترالِ زمانِ پلان جایگذاری می‌شود؛
     DO تراکنشِ تازه نمی‌سازد — داخلِ همان تراکنشِ قفل‌دار اجرا می‌شود. */
  EXECUTE format($ins$
    INSERT INTO attendance_p ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                              "id", "late_at", "late_minutes", "note", "school_id",
                              "source", "status", "student_id", "taken_at",
                              "updated_at", "version", "chg_id")
    SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
           o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
           o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
    FROM attendance o
    WHERE o.chg_id > %s
      AND NOT EXISTS (SELECT 1 FROM attendance_p p
                      WHERE p.id = o.id
                        AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                        AND p.chg_id >= o.chg_id)
    ON CONFLICT (id, created_at) DO UPDATE SET
      "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
      "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
      "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
      "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
      "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
      "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id"
  $ins$, w0);
END
$swap$;;

DO $swap$
DECLARE
  w0 BIGINT;
BEGIN
  SELECT v.w0 INTO w0 FROM mig009_w0 v WHERE v.id = 1;
  IF w0 IS NULL THEN
    RAISE EXCEPTION 'partition swap: marker row mig009_w0(id=1) is missing';
  END IF;
  /* معنای psql-gsetِ قدیم: مرز به‌صورتِ لیترالِ زمانِ پلان جایگذاری می‌شود؛
     DO تراکنشِ تازه نمی‌سازد — داخلِ همان تراکنشِ قفل‌دار اجرا می‌شود. */
  EXECUTE format($ins$
    INSERT INTO grades_p ("class_id", "created_at", "date", "exam_type", "id",
                          "kind", "max_score", "school_id", "score", "source",
                          "student_id", "subject_id", "teacher_id", "term",
                          "updated_at", "version", "chg_id")
    SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
           o."exam_type", o."id", o."kind", o."max_score", o."school_id",
           o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
           o."updated_at", o."version", o."chg_id"
    FROM grades o
    WHERE o.chg_id > %s
      AND NOT EXISTS (SELECT 1 FROM grades_p p
                      WHERE p.id = o.id
                        AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                        AND p.chg_id >= o.chg_id)
    ON CONFLICT (id, created_at) DO UPDATE SET
      "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
      "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
      "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
      "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
      "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id"
  $ins$, w0);
END
$swap$;;

DO $$
BEGIN
  IF EXISTS (SELECT FROM pg_class WHERE relname = 'attendance_old')
     OR EXISTS (SELECT FROM pg_class WHERE relname = 'grades_old') THEN
    RAISE EXCEPTION 'partition swap: *_old already exists — previous swap not cleaned up';
  END IF;
END $$;

ALTER TABLE attendance RENAME TO attendance_old;
ALTER TABLE grades RENAME TO grades_old;

ALTER INDEX idx_attendance_school_id        RENAME TO idx_attendance_old_school_id;
ALTER INDEX idx_attendance_school_student   RENAME TO idx_attendance_old_school_student;
ALTER INDEX idx_attendance_school_class     RENAME TO idx_attendance_old_school_class;
ALTER INDEX idx_attendance_school_class_date RENAME TO idx_attendance_old_school_class_date;
ALTER INDEX idx_attendance_created_at       RENAME TO idx_attendance_old_created_at;
ALTER INDEX idx_attendance_updated_at       RENAME TO idx_attendance_old_updated_at;
ALTER INDEX idx_attendance_school_date_id   RENAME TO idx_attendance_old_school_date_id;
ALTER INDEX idx_attendance_student_date_id  RENAME TO idx_attendance_old_student_date_id;
ALTER INDEX idx_attendance_chg_id           RENAME TO idx_attendance_old_chg_id;
ALTER SEQUENCE attendance_id_seq            RENAME TO attendance_old_id_seq;

ALTER INDEX idx_grades_school_id            RENAME TO idx_grades_old_school_id;
ALTER INDEX idx_grades_school_student       RENAME TO idx_grades_old_school_student;
ALTER INDEX idx_grades_school_student_subject RENAME TO idx_grades_old_school_student_subject;
ALTER INDEX idx_grades_school_class         RENAME TO idx_grades_old_school_class;
ALTER INDEX idx_grades_created_at           RENAME TO idx_grades_old_created_at;
ALTER INDEX idx_grades_updated_at           RENAME TO idx_grades_old_updated_at;
ALTER INDEX idx_grades_school_id_id         RENAME TO idx_grades_old_school_id_id;
ALTER INDEX idx_grades_school_student_id    RENAME TO idx_grades_old_school_student_id;
ALTER INDEX idx_grades_chg_id               RENAME TO idx_grades_old_chg_id;
ALTER SEQUENCE grades_id_seq                RENAME TO grades_old_id_seq;

ALTER TABLE attendance_p RENAME TO attendance;
ALTER TABLE grades_p RENAME TO grades;

ALTER INDEX idx_attendance_p_school_id       RENAME TO idx_attendance_school_id;
ALTER INDEX idx_attendance_p_school_student  RENAME TO idx_attendance_school_student;
ALTER INDEX idx_attendance_p_school_class    RENAME TO idx_attendance_school_class;
ALTER INDEX idx_attendance_p_school_class_date RENAME TO idx_attendance_school_class_date;
ALTER INDEX idx_attendance_p_created_at      RENAME TO idx_attendance_created_at;
ALTER INDEX idx_attendance_p_updated_at      RENAME TO idx_attendance_updated_at;
ALTER INDEX idx_attendance_p_school_date_id  RENAME TO idx_attendance_school_date_id;
ALTER INDEX idx_attendance_p_student_date_id RENAME TO idx_attendance_student_date_id;
ALTER INDEX idx_attendance_p_chg_id          RENAME TO idx_attendance_chg_id;
ALTER INDEX idx_attendance_p_id              RENAME TO idx_attendance_id;
ALTER SEQUENCE attendance_p_id_seq           RENAME TO attendance_id_seq;

ALTER INDEX idx_grades_p_school_id           RENAME TO idx_grades_school_id;
ALTER INDEX idx_grades_p_school_student      RENAME TO idx_grades_school_student;
ALTER INDEX idx_grades_p_school_student_subject RENAME TO idx_grades_school_student_subject;
ALTER INDEX idx_grades_p_school_class        RENAME TO idx_grades_school_class;
ALTER INDEX idx_grades_p_created_at          RENAME TO idx_grades_created_at;
ALTER INDEX idx_grades_p_updated_at          RENAME TO idx_grades_updated_at;
ALTER INDEX idx_grades_p_school_id_id        RENAME TO idx_grades_school_id_id;
ALTER INDEX idx_grades_p_school_student_id   RENAME TO idx_grades_school_student_id;
ALTER INDEX idx_grades_p_chg_id              RENAME TO idx_grades_chg_id;
ALTER INDEX idx_grades_p_id                  RENAME TO idx_grades_id;
ALTER SEQUENCE grades_p_id_seq               RENAME TO grades_id_seq;

COMMIT;

/* ═══════════════ Phase D — stray-merge (پس از کامیتِ swap؛ idempotent) ═══════════════
   نویسنده‌ای که عبارتش دقیقاً حینِ پنجرهٔ قفل بلاک شده بود، پس از بیداری روی
   OID قدیمی (اکنون *_old) اجرا می‌شود — چون تحلیلِ نام پیش از بلاک رخ داده.
   همین ادغامِ ضدالحاقی سطرهایش را برمی‌گرداند؛ دوباره‌اجرا بی‌اثر است.
   دو پاسِ پشت‌سرهم اجرا می‌شود (بیداریِ نویسنده‌های بلاک و کامیتِشان
   میکروثانیه است؛ پاسِ دوم قطعی می‌گیرد). راستی‌آزماییِ پس از مهاجرت:
   SELECT count(*) FROM grades_old o WHERE NOT EXISTS (SELECT 1 FROM grades n
   WHERE n.id=o.id AND n.created_at=o.created_at AND n.chg_id >= o.chg_id);  ⇒ 0 */
-- STRAY-MERGE:BEGIN
INSERT INTO attendance ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                          "id", "late_at", "late_minutes", "note", "school_id",
                          "source", "status", "student_id", "taken_at",
                          "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
       o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
FROM attendance_old o
WHERE NOT EXISTS (SELECT 1 FROM attendance p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
  "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
  "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
  "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
  "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

INSERT INTO grades ("class_id", "created_at", "date", "exam_type", "id",
                      "kind", "max_score", "school_id", "score", "source",
                      "student_id", "subject_id", "teacher_id", "term",
                      "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exam_type", o."id", o."kind", o."max_score", o."school_id",
       o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
       o."updated_at", o."version", o."chg_id"
FROM grades_old o
WHERE NOT EXISTS (SELECT 1 FROM grades p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
  "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
  "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
  "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

/* پاسِ دوم: نویسنده‌های بلاک‌شدهٔ لحظهٔ swap در لحظهٔ رهاشدنِ قفل بیدار
   می‌شوند و در میکروثانیه کامیت می‌کنند — پاسِ اول ممکن است هم‌زمانِ
   بیداری‌شان باشد و پاسِ دوم آن‌ها را قطعی بگیرد. دوباره‌اجرا بی‌اثر است. */

INSERT INTO attendance ("class_id", "created_at", "date", "exit_at", "exit_minutes",
                          "id", "late_at", "late_minutes", "note", "school_id",
                          "source", "status", "student_id", "taken_at",
                          "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exit_at", o."exit_minutes", o."id", o."late_at", o."late_minutes", o."note", o."school_id",
       o."source", o."status", o."student_id", o."taken_at", o."updated_at", o."version", o."chg_id"
FROM attendance_old o
WHERE NOT EXISTS (SELECT 1 FROM attendance p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exit_at" = EXCLUDED."exit_at",
  "exit_minutes" = EXCLUDED."exit_minutes", "late_at" = EXCLUDED."late_at",
  "late_minutes" = EXCLUDED."late_minutes", "note" = EXCLUDED."note",
  "school_id" = EXCLUDED."school_id", "source" = EXCLUDED."source", "status" = EXCLUDED."status",
  "student_id" = EXCLUDED."student_id", "taken_at" = EXCLUDED."taken_at",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";

INSERT INTO grades ("class_id", "created_at", "date", "exam_type", "id",
                      "kind", "max_score", "school_id", "score", "source",
                      "student_id", "subject_id", "teacher_id", "term",
                      "updated_at", "version", "chg_id")
SELECT o."class_id", COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00'), o."date",
       o."exam_type", o."id", o."kind", o."max_score", o."school_id",
       o."score", o."source", o."student_id", o."subject_id", o."teacher_id", o."term",
       o."updated_at", o."version", o."chg_id"
FROM grades_old o
WHERE NOT EXISTS (SELECT 1 FROM grades p
                  WHERE p.id = o.id
                    AND p.created_at = COALESCE(o."created_at", o."updated_at", TIMESTAMPTZ '1970-01-01 00:00:00+00')
                    AND p.chg_id >= o.chg_id)
ON CONFLICT (id, created_at) DO UPDATE SET
  "class_id" = EXCLUDED."class_id", "date" = EXCLUDED."date", "exam_type" = EXCLUDED."exam_type",
  "kind" = EXCLUDED."kind", "max_score" = EXCLUDED."max_score", "school_id" = EXCLUDED."school_id",
  "score" = EXCLUDED."score", "source" = EXCLUDED."source", "student_id" = EXCLUDED."student_id",
  "subject_id" = EXCLUDED."subject_id", "teacher_id" = EXCLUDED."teacher_id", "term" = EXCLUDED."term",
  "updated_at" = EXCLUDED."updated_at", "version" = EXCLUDED."version", "chg_id" = EXCLUDED."chg_id";
-- STRAY-MERGE:END

/* نشانگرِ w0 عمداً می‌ماند (یک سطرِ audit: مرزِ chg و زمانِ آغازِ کپی) —
   ماندنش ازسرگیریِ بعد ازِ هر کرشی را هم ایمن‌تر می‌کند و rerun بعد از
   موفقیتِ swap به‌هرحال توسطِ گاردِ swap رد می‌شود. حذفِ نشانگر در ۰۰9.down
   انجام می‌شود (قراردادِ مخزن: حذفِ جدول در مهاجرتِ forward ممنوع است). */
