-- ═══════════════════════════════════════════════════════════════════
-- migrations/013_universal_occ_and_sequences.sql
-- Wave 26 / Phase 5 Step 08 (P2-NI-06)
-- Universal Optimistic Concurrency Control (OCC) & Persistent Conflicts
-- Fully compatible with Migrations 001-012 (Zero-Collision Forward & Rollback)
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- 1. Persistent sync_conflicts (Single Source of Truth in PostgreSQL).
-- P0-BUG-02 fix (Chat 2 remediation, 2026-09-19; merged with the parallel
-- phase-2 remediation of this same blocker): migration 001 already creates
-- sync_conflicts with the arbitration shape. The old parallel CREATE TABLE
-- guarded only by IF NOT EXISTS meant the 001 table always won and
-- idx_sync_conflicts_user then failed on a clean chain. Fix: additive ALTERs
-- only — the union of BOTH remediations' columns, never a parallel shape.
-- Works on: fresh chain (001 created the table) and bare edge cases.
CREATE TABLE IF NOT EXISTS sync_conflicts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection" VARCHAR(128) NOT NULL,
  "record_id" INTEGER,
  "school_id" INTEGER,
  "base_version" INTEGER,
  "server_version" INTEGER,
  "server_state" JSONB,
  "incoming" JSONB,
  "status" VARCHAR(32) NOT NULL DEFAULT 'open',
  "winner" VARCHAR(32),
  "reason" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "resolved_at" TIMESTAMPTZ,
  "resolved_by" INTEGER
);

-- 1b. Phase-5 universal-OCC additive columns (union of both remediations).
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS client_uid VARCHAR(128);
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS client_data JSONB;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS server_data JSONB;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS incoming_version INTEGER;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS current_version INTEGER;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS resolved_data JSONB;
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS resolution_strategy VARCHAR(32) NOT NULL DEFAULT 'server_wins';
-- P0 (audit 4.2): server/sync.js stamps every conflict row with updated_at and
-- server/conflicts.js re-stamps it on resolution — the column must exist or the
-- atomic PG mirror batch (persistOpsBatch) fails the whole request with 503.
ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_sync_conflicts_school ON sync_conflicts (school_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_user ON sync_conflicts (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_coll_rec ON sync_conflicts (collection, record_id);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_status_created ON sync_conflicts (status, created_at DESC);

-- 2. Add 'version' column to all application tables if not already present
-- and ensure atomic sequence-backed IDs
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'announcements', 'app_settings', 'assets', 'assoc_minutes', 'attendance',
    'attendance_modes', 'bell_schedules', 'bus_events', 'bus_followups', 'bus_locations',
    'bus_needs', 'bus_routes', 'bus_students', 'calendar', 'certificates',
    'class_subject_members', 'classes', 'corrections', 'counselor_msgs', 'counselor_refs',
    'counties', 'discipline', 'districts', 'dojo_types', 'donations',
    'dorm_assignments', 'dorm_meals', 'dorm_rooms', 'enrollments', 'exam_duties',
    'exam_terms', 'exams', 'grades', 'hw_assignments', 'hw_submissions',
    'installments', 'internships', 'leaves', 'lib_books', 'lib_loans',
    'makeup_classes', 'meeting_slots', 'messages', 'nid_conflicts', 'notifications',
    'notify_queue', 'nudges', 'offices', 'parent_links', 'parent_subscriptions',
    'parent_verifications', 'pre_enrollments', 'preapps', 'provinces', 'reexams',
    'report_logs', 'safety_drills', 'schedule', 'scholarships', 'school_years',
    'schools', 'sedascores', 'sms_log', 'sms_wallet', 'staff_attendance',
    'student_archive', 'student_transfers', 'subjects', 'subscription_payments', 'substitutions',
    'summer_classes', 'support_tickets', 'teacher_evaluations', 'teacher_notes', 'teacher_schools',
    'teacher_sms', 'training_courses', 'transactions', 'transfer_requests', 'tuition_plans',
    'tuitions', 'users', 'vclass_attendance', 'vclass_links', 'vclass_questions',
    'vclass_sessions', 'visitors'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = tbl) THEN
      IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = tbl AND column_name = 'version') THEN
        EXECUTE format('ALTER TABLE public.%I ADD COLUMN version INTEGER NOT NULL DEFAULT 1;', tbl);
      END IF;
    END IF;
  END LOOP;
END $$;

COMMIT;
