/* ═══════════════════════════════════════════════════════════════════
   server/ids.js — P0-16: تولید شناسهٔ بدون‌برخورد
   ───────────────────────────────────────────────────────────────────
   ● ردیف‌های فعالِ پستگرس: دنبالهٔ `payesh_<col>_id_seq` با nextval —
     هر نمونه عدد خودش را می‌گیرد؛ بوت‌استرپِ دنباله زیرِ قفلِ مشاوره‌ای
     (advisory lock) انجام می‌شود تا دو نمونه همزمان دنباله نسازند و
     `setval` فقط رو به جلو حرکت می‌کند.
   ● بدون پستگرس (حالت جی‌سون): تا پی۰-۱۳ تضمین تک‌نمونه‌ای است، اما
     مکس+۱ باز هم زیرِ میوتکسِ فرایندی + قفل توزیع‌شده اجرا می‌شود تا
     درخواست‌های همزمانِ میان‌بر (روی awaitها) هرگز عدد تکراری نبینند.
   ● فضای نام: دانش‌آموزان و کاربران یک فضا دارند ('users') — همان آرایهٔ
     مشترک منبع است.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';
const crypto = require('crypto');

const NAMESPACES = new Set(['attendance', 'classes', 'grades', 'users']);

function createIds({ db, cache }){
  const bootstrapped = new Set(); /* دنباله‌های هم‌ترازشده در این فرایند */
  const chains = new Map();       /* میوتکس فرایندی به‌ازای هر فضانام */

  const localMax = (list) => {
    let m = 0;
    for(const r of (list || [])){
      const n = Number(r && r.id);
      if(Number.isFinite(n) && n > m) m = n;
    }
    return m;
  };

  const seqName = (col) => 'payesh_' + col + '_id_seq';
  const advisoryKey = (seq) =>
    crypto.createHash('sha256').update(seq).digest().readInt32BE(0);

  const bootstrapSeq = async (col, seq, list) => {
    if(bootstrapped.has(col)) return;
    const key = advisoryKey(seq);
    try{
      await db.query('SELECT pg_advisory_lock($1)', [key]);
      await db.query('CREATE SEQUENCE IF NOT EXISTS ' + seq);
      const cur = await db.query('SELECT last_value FROM ' + seq);
      const last = Number((cur.rows[0] || {}).last_value || 0);
      const m = localMax(list);
      if(m > last) await db.query('SELECT setval($1, $2)', [seq, m]); /* فقط رو به جلو */
      bootstrapped.add(col);
    }catch(e){ /* نبود دسترسی: لایهٔ بعدی تصمیم می‌گیرد */
    }finally{
      try{ await db.query('SELECT pg_advisory_unlock($1)', [key]); }catch(e){}
    }
  };

  const pgNext = async (col, list) => {
    /* Wave 2: در PostgreSQL منبع شناسه خود جدول است
       (GENERATED BY DEFAULT AS IDENTITY). ابتدا sequence وابسته به ستون id
       را از catalog می‌گیریم؛ فقط برای schemaهای قدیمی به sequence اختصاصی
       payesh_* برمی‌گردیم. */
    try{
      const seqRes = await db.query('SELECT pg_get_serial_sequence($1, $2) AS seq', [col, 'id']);
      const ownedSeq = seqRes && seqRes.rows && seqRes.rows[0] && seqRes.rows[0].seq;
      if(ownedSeq){
        const r = await db.query('SELECT nextval($1)', [ownedSeq]);
        return Number(r.rows[0].nextval);
      }
    }catch(e){}
    const seq = seqName(col);
    try{
      const r = await db.query('SELECT nextval($1)', [seq]);
      return Number(r.rows[0].nextval);
    }catch(e){
      await bootstrapSeq(col, seq, list);
      const r = await db.query('SELECT nextval($1)', [seq]);
      return Number(r.rows[0].nextval);
    }
  };

  /* مکس+۱ محافظت‌شده: میوتکس فرایندی + قفل توزیع‌شده (اگر باشد) */
  const guardedMaxPlusOne = async (col, list) => {
    let token = null;
    if(cache){
      try{ token = await cache.acquireLock('ids:' + col, 5); }catch(e){}
    }
    try{
      return localMax(list) + 1;
    }finally{
      if(cache && token){ try{ await cache.releaseLock('ids:' + col, token); }catch(e){} }
    }
  };

  /**
   * @param {string} collection — فضانام: attendance | classes | grades | users
   * @param {Array}  list — آرایهٔ منبع برای محاسبهٔ بیشینهٔ محلی
   * @returns {Promise<number>} شناسهٔ یکتا
   */
  async function nextId(collection, list){
    const col = NAMESPACES.has(collection) ? collection : 'users';
    /* سریالی‌سازی فرایندی: هیچ دو درخواستی همزمان وارد بحرانی نمی‌شوند */
    const prev = chains.get(col) || Promise.resolve();
    let release;
    const gate = new Promise(res => { release = res; });
    chains.set(col, prev.then(() => gate));
    await prev;
    try{
      if(db && typeof db.isPostgres === 'function' && db.isPostgres()){
        try{ return await pgNext(col, list); }catch(e){ /* افتاد به محافظ محلی */ }
      }
      return await guardedMaxPlusOne(col, list);
    }finally{
      release();
    }
  }

  return { nextId };
}

module.exports = { createIds };
