/* ═══════════════════════════════════════════════════════════════════
   server/ids.js — P0-16: تولید شناسهٔ بدون‌برخورد
   ───────────────────────────────────────────────────────────────────
   ● ردیف‌های فعالِ پستگرس: دنبالهٔ `payesh_<col>_id_seq` با nextval —
     هر نمونه عدد خودش را می‌گیرد؛ بوت‌استرپِ دنباله زیرِ قفلِ مشاوره‌ای
     (advisory lock) انجام می‌شود تا دو نمونه همزمان دنباله نسازند و
     `setval` فقط رو به جلو حرکت می‌کند.
   ● بدون پستگرس (حالت جی‌سون): تا پی۰-۱۳ تضمین تک‌نمونه‌ای است، اما
     مکس+۱ باز هم زیرِ میوتکسِ فرایندی + قفل توزیع‌شده اجرا می‌شود تا
     درخواست‌های همزمانِ میان‌بر (روی awaitها) هرگز عدد تکراری نبینند.
   ● فضای نام: دانش‌آموزان و کاربران یک فضا دارند ('users') — همان آرایهٔ
     مشترک منبع است.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';
const crypto = require('crypto');

/* فضانام‌های حالتِ حافظه‌ای: دانش‌آموزان و کاربران یک آرایه دارند ('users'). */
const NAMESPACES = new Set(['attendance', 'classes', 'grades', 'users']);
/* A-AUTHZ-DUR-01 (Arena-2 adversarial audit): «students» نمایِ جدولِ users است —
   در مسیرِ پستگرس هم باید همان دنبالهٔ users را بگیرد. */
const PG_TABLE_ALIAS = { students: 'users' };

function createIds({ db, cache }){
  const bootstrapped = new Set(); /* دنباله‌های هم‌ترازشده در این فرایند */
  const aligned = new Set();      /* A-AUTHZ-DUR-01: دنباله‌های هم‌راز با MAX(id) */
  const chains = new Map();       /* میوتکس فرایندی به‌ازای هر فضانام */

  const localMax = (list) => {
    let m = 0;
    for(const r of (list || [])){
      const n = Number(r && r.id);
      if(Number.isFinite(n) && n > m) m = n;
    }
    return m;
  };

  const seqName = (col) => 'payesh_' + col + '_id_seq';
  const advisoryKey = (seq) =>
    crypto.createHash('sha256').update(seq).digest().readInt32BE(0);

  /* A-AUTHZ-DUR-01 — هم‌ترازیِ دنبالهٔ مالک با بیشینهٔ شناسه‌های موجود.
     ستون‌های GENERATED BY DEFAULT AS IDENTITY با درجِ صریحِ شناسه
     (بازیابی/بذر/مهاجرت) جلو نمی‌آیند؛ اگر دنباله عقب بماند، نخستین
     درج‌های همگام‌سازی شناسه‌های اشغال‌شده می‌گیرند و مسیرِ
     «ON CONFLICT (id) DO UPDATE» رکوردِ دیگری را بی‌صدا بازنویسی می‌کند.
     نخستین مصرفِ هر جدول در این فرایند: زیرِ قفلِ مشاوره‌ای، فقط رو به
     جلو، setval به بیشینهٔ واقعیِ جدول. خطا = ادامه با رفتارِ پیشین
     (لایه‌های بعدی آزمون می‌شوند) ولی هرگز سکوتِ بازنویسی نمی‌سازد. */
  const alignOwnedSeq = async (table, seq) => {
    const key = table + '|' + seq;
    if(aligned.has(key)) return;
    const lock = advisoryKey(seq + ':align');
    try{
      await db.query('SELECT pg_advisory_lock($1)', [lock]);
      const mx = await db.query('SELECT COALESCE(MAX(id), 0) AS m FROM "' + String(table).replace(/"/g, '') + '"');
      const m = Number((mx.rows[0] || {}).m || 0);
      const st = await db.query('SELECT last_value, is_called FROM ' + seq);
      const lv = Number((st.rows[0] || {}).last_value || 0);
      const called = !!(st.rows[0] || {}).is_called;
      const eff = called ? lv : lv - 1;
      if(m > eff) await db.query('SELECT setval($1, $2)', [seq, m]); /* فقط رو به جلو */
      aligned.add(key);
    }catch(e){ /* جدول/دنبالهٔ ناموجود — مسیرِ بعدی تصمیم می‌گیرد */ }
    finally{
      try{ await db.query('SELECT pg_advisory_unlock($1)', [lock]); }catch(e){}
    }
  };

  const bootstrapSeq = async (col, seq, list) => {
    if(bootstrapped.has(col)) return;
    const key = advisoryKey(seq);
    try{
      await db.query('SELECT pg_advisory_lock($1)', [key]);
      await db.query('CREATE SEQUENCE IF NOT EXISTS ' + seq);
      const cur = await db.query('SELECT last_value FROM ' + seq);
      const last = Number((cur.rows[0] || {}).last_value || 0);
      const m = localMax(list);
      if(m > last) await db.query('SELECT setval($1, $2)', [seq, m]); /* فقط رو به جلو */
      bootstrapped.add(col);
    }catch(e){ /* نبود دسترسی: لایهٔ بعدی تصمیم می‌گیرد */
    }finally{
      try{ await db.query('SELECT pg_advisory_unlock($1)', [key]); }catch(e){}
    }
  };

  const pgNext = async (col, list) => {
    /* Wave 2: در PostgreSQL منبع شناسه خود جدول است
       (GENERATED BY DEFAULT AS IDENTITY). ابتدا sequence وابسته به ستون id
       را از catalog می‌گیریم؛ فقط برای schemaهای قدیمی به sequence اختصاصی
       payesh_* برمی‌گردیم.
       A-AUTHZ-DUR-01: هر جدول دنبالهٔ خودش را می‌گیرد — بازنگاشتِ همهٔ
       مجموعه‌ها به فضانامِ 'users' (رفتارِ پیشین) شناسه‌های جدولِ دیگر را
       به این مجموعه می‌داد و با شناسه‌های موجود برخورد می‌ساخت. 'students'
       همچنان نامِ مستعارِ جدولِ users است (PG_TABLE_ALIAS). */
    const table = PG_TABLE_ALIAS[col] || col;
    try{
      const seqRes = await db.query('SELECT pg_get_serial_sequence($1, $2) AS seq', [table, 'id']);
      const ownedSeq = seqRes && seqRes.rows && seqRes.rows[0] && seqRes.rows[0].seq;
      if(ownedSeq){
        await alignOwnedSeq(table, ownedSeq);
        const r = await db.query('SELECT nextval($1)', [ownedSeq]);
        return Number(r.rows[0].nextval);
      }
    }catch(e){}
    const seq = seqName(table);
    try{
      const r = await db.query('SELECT nextval($1)', [seq]);
      return Number(r.rows[0].nextval);
    }catch(e){
      await bootstrapSeq(table, seq, list);
      const r = await db.query('SELECT nextval($1)', [seq]);
      return Number(r.rows[0].nextval);
    }
  };

  /* مکس+۱ محافظت‌شده: میوتکس فرایندی + قفل توزیع‌شده (اگر باشد) */
  const guardedMaxPlusOne = async (col, list) => {
    let token = null;
    if(cache){
      try{ token = await cache.acquireLock('ids:' + col, 5); }catch(e){}
    }
    try{
      return localMax(list) + 1;
    }finally{
      if(cache && token){ try{ await cache.releaseLock('ids:' + col, token); }catch(e){} }
    }
  };

  /**
   * @param {string} collection — فضانام: attendance | classes | grades | users
   * @param {Array}  list — آرایهٔ منبع برای محاسبهٔ بیشینهٔ محلی
   * @returns {Promise<number>} شناسهٔ یکتا
   */
  async function nextId(collection, list){
    const col = NAMESPACES.has(collection) ? collection : 'users';
    /* سریالی‌سازی فرایندی: هیچ دو درخواستی همزمان وارد بحرانی نمی‌شوند */
    const prev = chains.get(col) || Promise.resolve();
    let release;
    const gate = new Promise(res => { release = res; });
    chains.set(col, prev.then(() => gate));
    await prev;
    try{
      const isProd = process.env.NODE_ENV === 'production' || process.env.PAYESH_ENV === 'production';
      if(db && typeof db.isPostgres === 'function' && db.isPostgres()){
        try{
          /* A-AUTHZ-DUR-01: نامِ واقعیِ مجموعه به مسیرِ پستگرس می‌رود تا هر
             جدول دنبالهٔ مالکِ خودش را بگیرد (بازنگاشتِ فضانام فقط برای
             حالتِ حافظه‌ای است). */
          return await pgNext(collection, list);
        }catch(e){
          if(isProd){
            const err = new Error(`FATAL_ID_GENERATION_FAILURE: PostgreSQL identity sequence failure in production: ${e.message}`);
            err.code = 'PG_SEQUENCE_FATAL';
            throw err;
          }
        }
      } else if (isProd && (!db || typeof db.memoryFallbackAllowed !== 'function' || !db.memoryFallbackAllowed())) {
        const err = new Error('FATAL_ID_GENERATION_FAILURE: Production environment forbids in-memory localMax fallback; PostgreSQL is required');
        err.code = 'PG_SEQUENCE_REQUIRED';
        throw err;
      }
      return await guardedMaxPlusOne(col, list);
    }finally{
      release();
    }
  }

  return { nextId };
}

module.exports = { createIds };
