-- ═══════════════════════════════════════════════════════════════════
-- Payesh PostgreSQL Relational Schema (80 Collections)
-- Auto-generated from authz/model.json
-- ═══════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "btree_gist";

-- Internal synchronization & session management tables
CREATE TABLE IF NOT EXISTS server_processed_uids (
  uid VARCHAR(128) PRIMARY KEY,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS server_revoked_jti (
  jti VARCHAR(128) PRIMARY KEY,
  revoked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS server_auth_codes (
  phone VARCHAR(20) PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  national_id VARCHAR(10),
  user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Transactional outbox (wave 8)
CREATE TABLE IF NOT EXISTS server_outbox (
  id BIGINT PRIMARY KEY,
  type VARCHAR(64) NOT NULL,
  collection VARCHAR(64),
  record_id BIGINT,
  actor_id BIGINT,
  version INTEGER,
  payload JSONB,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  retry_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_server_outbox_status ON server_outbox (status);

-- Table: server_tombstones (بازیابی‌شده پس از ادغام — `server/syncdelta.js` به آن وابسته است؛ در بازتولید اسکیمای بالادست حذف شده بود)
CREATE TABLE IF NOT EXISTS server_tombstones (
  id BIGSERIAL PRIMARY KEY,
  "collection" VARCHAR(64) NOT NULL,
  record_id INTEGER NOT NULL,
  school_id INTEGER,
  deleted_by INTEGER,
  deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reason VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_server_tombstones_deleted_at ON server_tombstones (deleted_at);
CREATE INDEX IF NOT EXISTS idx_server_tombstones_school_deleted_at ON server_tombstones (school_id, deleted_at);

-- Table: announcements
CREATE TABLE IF NOT EXISTS announcements (
  "audience" VARCHAR(255),
  "author_id" INTEGER,
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "office_id" INTEGER,
  "pinned" VARCHAR(255),
  "school_id" INTEGER,
  "severity" VARCHAR(255),
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_announcements_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_announcements_school_id ON announcements (school_id);
CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON announcements (created_at DESC);

-- Table: app_settings
CREATE TABLE IF NOT EXISTS app_settings (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_app_settings_created_at ON app_settings (created_at DESC);

-- Table: assets
CREATE TABLE IF NOT EXISTS assets (
  "category" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location" VARCHAR(255),
  "name" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_assets_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_assets_school_id ON assets (school_id);
CREATE INDEX IF NOT EXISTS idx_assets_created_at ON assets (created_at DESC);

-- Table: assoc_minutes
CREATE TABLE IF NOT EXISTS assoc_minutes (
  "archived" VARCHAR(255),
  "attendees" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meeting_date" VARCHAR(50),
  "meeting_type" VARCHAR(255),
  "resolutions" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_assoc_minutes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_assoc_minutes_school_id ON assoc_minutes (school_id);
CREATE INDEX IF NOT EXISTS idx_assoc_minutes_created_at ON assoc_minutes (created_at DESC);

-- Table: attendance
CREATE TABLE IF NOT EXISTS attendance (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "exit_at" TIMESTAMPTZ,
  "exit_minutes" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "late_at" TIMESTAMPTZ,
  "late_minutes" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "taken_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_attendance_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_attendance_school_id ON attendance (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_school_student ON attendance (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_school_class ON attendance (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_created_at ON attendance (created_at DESC);

-- Table: attendance_modes
CREATE TABLE IF NOT EXISTS attendance_modes (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mode" VARCHAR(255),
  "school_id" INTEGER,
  "set_at" TIMESTAMPTZ,
  "set_by" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_attendance_modes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_attendance_modes_school_id ON attendance_modes (school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_modes_created_at ON attendance_modes (created_at DESC);

-- Table: bell_schedules
CREATE TABLE IF NOT EXISTS bell_schedules (
  "created_at" TIMESTAMPTZ,
  "days" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_bell_schedules_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_bell_schedules_school_id ON bell_schedules (school_id);
CREATE INDEX IF NOT EXISTS idx_bell_schedules_created_at ON bell_schedules (created_at DESC);

-- Table: bus_events
CREATE TABLE IF NOT EXISTS bus_events (
  "at" TIMESTAMPTZ,
  "by" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "route_id" INTEGER,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "student_id" INTEGER,
  "type" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_bus_events_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_bus_events_school_id ON bus_events (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_events_school_student ON bus_events (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_events_created_at ON bus_events (created_at DESC);

-- Table: bus_followups
CREATE TABLE IF NOT EXISTS bus_followups (
  "close_note" VARCHAR(255),
  "closed_at" TIMESTAMPTZ,
  "closed_by" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "route_id" INTEGER,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_bus_followups_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_bus_followups_school_id ON bus_followups (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_followups_school_student ON bus_followups (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_followups_created_at ON bus_followups (created_at DESC);

-- Table: bus_locations
CREATE TABLE IF NOT EXISTS bus_locations (
  "acc" VARCHAR(255),
  "by" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lat" VARCHAR(255),
  "lng" VARCHAR(255),
  "off" VARCHAR(255),
  "pos" VARCHAR(255),
  "recorded_at" TIMESTAMPTZ,
  "route_id" INTEGER,
  "source" VARCHAR(255),
  "speed" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bus_locations_created_at ON bus_locations (created_at DESC);

-- Table: bus_needs
CREATE TABLE IF NOT EXISTS bus_needs (
  "answer" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "school_id" INTEGER,
  "set_at" TIMESTAMPTZ,
  "set_by" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_bus_needs_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_bus_needs_school_id ON bus_needs (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_needs_school_student ON bus_needs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_bus_needs_created_at ON bus_needs (created_at DESC);

-- Table: bus_routes
CREATE TABLE IF NOT EXISTS bus_routes (
  "created_at" TIMESTAMPTZ,
  "driver_id" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "points" VARCHAR(255),
  "school_id" INTEGER,
  "stops" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_bus_routes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_bus_routes_school_id ON bus_routes (school_id);
CREATE INDEX IF NOT EXISTS idx_bus_routes_created_at ON bus_routes (created_at DESC);

-- Table: bus_students
CREATE TABLE IF NOT EXISTS bus_students (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "route_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bus_students_created_at ON bus_students (created_at DESC);

-- Table: calendar
CREATE TABLE IF NOT EXISTS calendar (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "school_id" INTEGER,
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_calendar_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_calendar_school_id ON calendar (school_id);
CREATE INDEX IF NOT EXISTS idx_calendar_created_at ON calendar (created_at DESC);

-- Table: certificates
CREATE TABLE IF NOT EXISTS certificates (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "issued_at" TIMESTAMPTZ,
  "issued_by" VARCHAR(255),
  "school_id" INTEGER,
  "student_id" INTEGER,
  "type" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "year" VARCHAR(50),
  CONSTRAINT fk_certificates_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_certificates_school_id ON certificates (school_id);
CREATE INDEX IF NOT EXISTS idx_certificates_school_student ON certificates (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_certificates_created_at ON certificates (created_at DESC);

-- Table: class_subject_members
CREATE TABLE IF NOT EXISTS class_subject_members (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_class_subject_members_created_at ON class_subject_members (created_at DESC);

-- Table: classes
CREATE TABLE IF NOT EXISTS classes (
  "capacity" INTEGER,
  "class_mode" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "field" VARCHAR(255),
  "grade" INTEGER,
  "grade_level" VARCHAR(255),
  "homeroom_teacher_id" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mode" VARCHAR(255),
  "name" VARCHAR(255),
  "room" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_classes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT chk_classes_capacity CHECK (capacity > 0)
);

CREATE INDEX IF NOT EXISTS idx_classes_school_id ON classes (school_id);
CREATE INDEX IF NOT EXISTS idx_classes_created_at ON classes (created_at DESC);

-- Table: corrections
CREATE TABLE IF NOT EXISTS corrections (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "message" VARCHAR(255),
  "parent_id" INTEGER,
  "parent_nid" VARCHAR(255),
  "resolved_at" TIMESTAMPTZ,
  "response" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_corrections_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_corrections_school_id ON corrections (school_id);
CREATE INDEX IF NOT EXISTS idx_corrections_school_student ON corrections (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_corrections_created_at ON corrections (created_at DESC);

-- Table: counselor_msgs
CREATE TABLE IF NOT EXISTS counselor_msgs (
  "author_id" INTEGER,
  "author_role" VARCHAR(255),
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_counselor_msgs_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_counselor_msgs_school_id ON counselor_msgs (school_id);
CREATE INDEX IF NOT EXISTS idx_counselor_msgs_school_student ON counselor_msgs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_msgs_created_at ON counselor_msgs (created_at DESC);

-- Table: counselor_refs
CREATE TABLE IF NOT EXISTS counselor_refs (
  "breach_key" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "handled_at" TIMESTAMPTZ,
  "handled_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "pattern" VARCHAR(255),
  "reason" VARCHAR(255),
  "referred_at" TIMESTAMPTZ,
  "referred_by" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_counselor_refs_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_counselor_refs_school_id ON counselor_refs (school_id);
CREATE INDEX IF NOT EXISTS idx_counselor_refs_school_student ON counselor_refs (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_refs_created_at ON counselor_refs (created_at DESC);

-- Table: counties
CREATE TABLE IF NOT EXISTS counties (
  "code" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "province_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_counties_created_at ON counties (created_at DESC);

-- Table: discipline
CREATE TABLE IF NOT EXISTS discipline (
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "date" VARCHAR(50),
  "description" TEXT,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "points" VARCHAR(255),
  "school_id" INTEGER,
  "student_id" INTEGER,
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_discipline_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_discipline_school_id ON discipline (school_id);
CREATE INDEX IF NOT EXISTS idx_discipline_school_student ON discipline (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_discipline_created_at ON discipline (created_at DESC);

-- Table: districts
CREATE TABLE IF NOT EXISTS districts (
  "county_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "name" VARCHAR(255),
  "province_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "village" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_districts_created_at ON districts (created_at DESC);

-- Table: donations
CREATE TABLE IF NOT EXISTS donations (
  "amount" NUMERIC(14, 2),
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "description" TEXT,
  "donor_name" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registered_by" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_donations_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_donations_school_id ON donations (school_id);
CREATE INDEX IF NOT EXISTS idx_donations_created_at ON donations (created_at DESC);

-- Table: dojo_types
CREATE TABLE IF NOT EXISTS dojo_types (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "delta" VARCHAR(255),
  "icon" VARCHAR(255),
  "label" VARCHAR(255),
  "order" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_dojo_types_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_dojo_types_school_id ON dojo_types (school_id);
CREATE INDEX IF NOT EXISTS idx_dojo_types_created_at ON dojo_types (created_at DESC);

-- Table: dorm_assignments
CREATE TABLE IF NOT EXISTS dorm_assignments (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "room_id" INTEGER,
  "school_id" INTEGER,
  "since" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_dorm_assignments_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_dorm_assignments_school_id ON dorm_assignments (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_assignments_school_student ON dorm_assignments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_dorm_assignments_created_at ON dorm_assignments (created_at DESC);

-- Table: dorm_meals
CREATE TABLE IF NOT EXISTS dorm_meals (
  "created_at" TIMESTAMPTZ,
  "day" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "menu" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_dorm_meals_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_dorm_meals_school_id ON dorm_meals (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_meals_created_at ON dorm_meals (created_at DESC);

-- Table: dorm_rooms
CREATE TABLE IF NOT EXISTS dorm_rooms (
  "capacity" INTEGER,
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_dorm_rooms_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_dorm_rooms_school_id ON dorm_rooms (school_id);
CREATE INDEX IF NOT EXISTS idx_dorm_rooms_created_at ON dorm_rooms (created_at DESC);

-- Table: enrollments
CREATE TABLE IF NOT EXISTS enrollments (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "year" INTEGER,
  CONSTRAINT fk_enrollments_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT uq_enrollments_student_year UNIQUE (student_id, year)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_school_id ON enrollments (school_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_school_student ON enrollments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_school_class ON enrollments (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_created_at ON enrollments (created_at DESC);

-- Table: exam_duties
CREATE TABLE IF NOT EXISTS exam_duties (
  "created_at" TIMESTAMPTZ,
  "exam_id" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" VARCHAR(255),
  "school_id" INTEGER,
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_exam_duties_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_exam_duties_school_id ON exam_duties (school_id);
CREATE INDEX IF NOT EXISTS idx_exam_duties_created_at ON exam_duties (created_at DESC);

-- Table: exam_terms
CREATE TABLE IF NOT EXISTS exam_terms (
  "created_at" TIMESTAMPTZ,
  "end_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "school_id" INTEGER,
  "start_date" VARCHAR(50),
  "status" VARCHAR(255),
  "term" VARCHAR(255),
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_exam_terms_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_exam_terms_school_id ON exam_terms (school_id);
CREATE INDEX IF NOT EXISTS idx_exam_terms_created_at ON exam_terms (created_at DESC);

-- Table: exams
CREATE TABLE IF NOT EXISTS exams (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "duration" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "max_score" VARCHAR(255),
  "room" VARCHAR(255),
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "start_time" VARCHAR(255),
  "subject_id" INTEGER,
  "term_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_exams_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_exams_school_id ON exams (school_id);
CREATE INDEX IF NOT EXISTS idx_exams_school_class ON exams (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_exams_created_at ON exams (created_at DESC);

-- Table: grades
CREATE TABLE IF NOT EXISTS grades (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "exam_type" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_vocational" VARCHAR(255),
  "kind" VARCHAR(255),
  "max_score" VARCHAR(255),
  "practical_score" VARCHAR(255),
  "school_id" INTEGER,
  "score" NUMERIC(12, 2),
  "source" VARCHAR(255),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "teacher_id" INTEGER,
  "term" VARCHAR(255),
  "theoretical_score" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_grades_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_grades_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_grades_school_id ON grades (school_id);
CREATE INDEX IF NOT EXISTS idx_grades_school_student ON grades (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_grades_school_class ON grades (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_grades_created_at ON grades (created_at DESC);

-- Table: hw_assignments
CREATE TABLE IF NOT EXISTS hw_assignments (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "description" TEXT,
  "due_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locked" VARCHAR(255),
  "school_id" INTEGER,
  "subject_id" INTEGER,
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "window_close" VARCHAR(255),
  "window_open" VARCHAR(255),
  CONSTRAINT fk_hw_assignments_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_hw_assignments_school_id ON hw_assignments (school_id);
CREATE INDEX IF NOT EXISTS idx_hw_assignments_school_class ON hw_assignments (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_hw_assignments_created_at ON hw_assignments (created_at DESC);

-- Table: hw_submissions
CREATE TABLE IF NOT EXISTS hw_submissions (
  "annotated_key" VARCHAR(255),
  "assignment_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "file_key" VARCHAR(255),
  "file_name" VARCHAR(255),
  "graded_at" TIMESTAMPTZ,
  "graded_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mime" VARCHAR(255),
  "score" NUMERIC(12, 2),
  "size" VARCHAR(255),
  "student_id" INTEGER,
  "submitted_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_hw_submissions_created_at ON hw_submissions (created_at DESC);

-- Table: installments
CREATE TABLE IF NOT EXISTS installments (
  "amount" NUMERIC(12, 2),
  "created_at" TIMESTAMPTZ,
  "due" VARCHAR(255),
  "due_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "method" VARCHAR(255),
  "paid" VARCHAR(255),
  "paid_amount" VARCHAR(255),
  "paid_at" TIMESTAMPTZ,
  "ref_id" INTEGER,
  "reminded_at" TIMESTAMPTZ,
  "school_id" INTEGER,
  "seq" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "tuition_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_installments_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_installments_school_id ON installments (school_id);
CREATE INDEX IF NOT EXISTS idx_installments_school_student ON installments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_installments_created_at ON installments (created_at DESC);

-- Table: internships
CREATE TABLE IF NOT EXISTS internships (
  "approved_at" TIMESTAMPTZ,
  "approved_by" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "date" VARCHAR(50),
  "hours" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_internships_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_internships_school_id ON internships (school_id);
CREATE INDEX IF NOT EXISTS idx_internships_school_student ON internships (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_internships_created_at ON internships (created_at DESC);

-- Table: leaves
CREATE TABLE IF NOT EXISTS leaves (
  "created_at" TIMESTAMPTZ,
  "from_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "reason" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "to_date" VARCHAR(50),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_leaves_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_leaves_school_id ON leaves (school_id);
CREATE INDEX IF NOT EXISTS idx_leaves_school_student ON leaves (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_leaves_created_at ON leaves (created_at DESC);

-- Table: lib_books
CREATE TABLE IF NOT EXISTS lib_books (
  "author" VARCHAR(255),
  "code" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "serial" VARCHAR(255),
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_lib_books_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_lib_books_school_id ON lib_books (school_id);
CREATE INDEX IF NOT EXISTS idx_lib_books_created_at ON lib_books (created_at DESC);

-- Table: lib_loans
CREATE TABLE IF NOT EXISTS lib_loans (
  "book_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "due_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loan_at" TIMESTAMPTZ,
  "registered_by" VARCHAR(255),
  "returned_at" TIMESTAMPTZ,
  "school_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_lib_loans_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_lib_loans_school_id ON lib_loans (school_id);
CREATE INDEX IF NOT EXISTS idx_lib_loans_school_student ON lib_loans (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_lib_loans_created_at ON lib_loans (created_at DESC);

-- Table: makeup_classes
CREATE TABLE IF NOT EXISTS makeup_classes (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_makeup_classes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_makeup_classes_school_id ON makeup_classes (school_id);
CREATE INDEX IF NOT EXISTS idx_makeup_classes_created_at ON makeup_classes (created_at DESC);

-- Table: meeting_slots
CREATE TABLE IF NOT EXISTS meeting_slots (
  "booked_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "duration" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location" VARCHAR(255),
  "note" TEXT,
  "parent_id" INTEGER,
  "school_id" INTEGER,
  "start_time" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_meeting_slots_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_meeting_slots_school_id ON meeting_slots (school_id);
CREATE INDEX IF NOT EXISTS idx_meeting_slots_school_student ON meeting_slots (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_meeting_slots_created_at ON meeting_slots (created_at DESC);

-- Table: messages
CREATE TABLE IF NOT EXISTS messages (
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "from_id" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "to_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_messages_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_messages_school_id ON messages (school_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at DESC);

-- Table: nid_conflicts
CREATE TABLE IF NOT EXISTS nid_conflicts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "full_name" VARCHAR(255),
  "national_id" VARCHAR(10),
  "other_school_id" INTEGER,
  "other_student_id" INTEGER,
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_nid_conflicts_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_nid_conflicts_school_id ON nid_conflicts (school_id);
CREATE INDEX IF NOT EXISTS idx_nid_conflicts_school_nid ON nid_conflicts (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_nid_conflicts_created_at ON nid_conflicts (created_at DESC);

-- Table: notifications
CREATE TABLE IF NOT EXISTS notifications (
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "link" VARCHAR(255),
  "read" INTEGER,
  "ref" VARCHAR(255),
  "role" VARCHAR(255),
  "school_id" INTEGER,
  "title" VARCHAR(255),
  "type" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "user_id" INTEGER,
  CONSTRAINT fk_notifications_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_notifications_school_id ON notifications (school_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);

-- Table: notify_queue
CREATE TABLE IF NOT EXISTS notify_queue (
  "auto" VARCHAR(255),
  "body" TEXT,
  "class_id" INTEGER,
  "correction_of" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "decided_at" TIMESTAMPTZ,
  "decided_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "parent_ids" VARCHAR(255),
  "parts" VARCHAR(255),
  "school_id" INTEGER,
  "source_hash" VARCHAR(255),
  "source_ref" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_notify_queue_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_notify_queue_school_id ON notify_queue (school_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_school_student ON notify_queue (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_school_class ON notify_queue (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_notify_queue_created_at ON notify_queue (created_at DESC);

-- Table: nudges
CREATE TABLE IF NOT EXISTS nudges (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "date" VARCHAR(50),
  "period" VARCHAR(255),
  "replied_at" TIMESTAMPTZ,
  "reply" VARCHAR(255),
  "school_id" INTEGER,
  "sms_sent" VARCHAR(255),
  "status" VARCHAR(255),
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_nudges_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_nudges_school_id ON nudges (school_id);
CREATE INDEX IF NOT EXISTS idx_nudges_school_class ON nudges (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_nudges_created_at ON nudges (created_at DESC);

-- Table: offices
CREATE TABLE IF NOT EXISTS offices (
  "active" BOOLEAN,
  "county_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "district_id" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" VARCHAR(255),
  "name" VARCHAR(255),
  "province_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "user_id" INTEGER
);

CREATE INDEX IF NOT EXISTS idx_offices_created_at ON offices (created_at DESC);

-- Table: parent_links
CREATE TABLE IF NOT EXISTS parent_links (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" INTEGER,
  "relation" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_parent_links_created_at ON parent_links (created_at DESC);

-- Table: parent_subscriptions
CREATE TABLE IF NOT EXISTS parent_subscriptions (
  "amount" NUMERIC(12, 2),
  "created_at" TIMESTAMPTZ,
  "end_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paid_at" TIMESTAMPTZ,
  "plan" VARCHAR(255),
  "ref_id" INTEGER,
  "start_date" VARCHAR(50),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "user_id" INTEGER
);

CREATE INDEX IF NOT EXISTS idx_parent_subscriptions_created_at ON parent_subscriptions (created_at DESC);

-- Table: parent_verifications
CREATE TABLE IF NOT EXISTS parent_verifications (
  "confirmed" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "parent_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_parent_verifications_created_at ON parent_verifications (created_at DESC);

-- Table: pre_enrollments
CREATE TABLE IF NOT EXISTS pre_enrollments (
  "created_at" TIMESTAMPTZ,
  "field" VARCHAR(255),
  "full_name" VARCHAR(255),
  "grade" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "national_id" VARCHAR(10),
  "note" TEXT,
  "phone" VARCHAR(20),
  "school_id" INTEGER,
  "source" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "year_code" VARCHAR(255),
  CONSTRAINT fk_pre_enrollments_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_id ON pre_enrollments (school_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_nid ON pre_enrollments (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_school_student ON pre_enrollments (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_pre_enrollments_created_at ON pre_enrollments (created_at DESC);

-- Table: preapps
CREATE TABLE IF NOT EXISTS preapps (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "note" TEXT,
  "phone" VARCHAR(20),
  "school_id" INTEGER,
  "stage" VARCHAR(255),
  "stage_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_preapps_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_preapps_school_id ON preapps (school_id);
CREATE INDEX IF NOT EXISTS idx_preapps_created_at ON preapps (created_at DESC);

-- Table: provinces
CREATE TABLE IF NOT EXISTS provinces (
  "code" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_provinces_created_at ON provinces (created_at DESC);

-- Table: reexams
CREATE TABLE IF NOT EXISTS reexams (
  "created_at" TIMESTAMPTZ,
  "exam_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "new_score" VARCHAR(255),
  "original_score" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_reexams_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_reexams_school_id ON reexams (school_id);
CREATE INDEX IF NOT EXISTS idx_reexams_school_student ON reexams (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_reexams_created_at ON reexams (created_at DESC);

-- Table: report_logs
CREATE TABLE IF NOT EXISTS report_logs (
  "created_at" TIMESTAMPTZ,
  "format" VARCHAR(255),
  "generated_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(255),
  "meta" JSONB,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_report_logs_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_report_logs_school_id ON report_logs (school_id);
CREATE INDEX IF NOT EXISTS idx_report_logs_created_at ON report_logs (created_at DESC);

-- Table: safety_drills
CREATE TABLE IF NOT EXISTS safety_drills (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" TEXT,
  "participant_count_staff" INTEGER,
  "participant_count_students" INTEGER,
  "registered_by" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_safety_drills_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_safety_drills_school_id ON safety_drills (school_id);
CREATE INDEX IF NOT EXISTS idx_safety_drills_created_at ON safety_drills (created_at DESC);

-- Table: schedule
CREATE TABLE IF NOT EXISTS schedule (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "day" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "period" VARCHAR(255),
  "school_id" INTEGER,
  "subject_id" INTEGER,
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_schedule_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT uq_schedule_teacher_slot UNIQUE (teacher_id, day, period)
);

CREATE INDEX IF NOT EXISTS idx_schedule_school_id ON schedule (school_id);
CREATE INDEX IF NOT EXISTS idx_schedule_school_class ON schedule (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_schedule_created_at ON schedule (created_at DESC);

-- Table: scholarships
CREATE TABLE IF NOT EXISTS scholarships (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_scholarships_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_scholarships_school_id ON scholarships (school_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_school_student ON scholarships (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_created_at ON scholarships (created_at DESC);

-- Table: school_years
CREATE TABLE IF NOT EXISTS school_years (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "closed" VARCHAR(255),
  "closed_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ,
  "placement" VARCHAR(255),
  "placement_year" VARCHAR(255),
  "promoted" VARCHAR(255),
  "reminded_at" TIMESTAMPTZ,
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "year_code" VARCHAR(255),
  CONSTRAINT fk_school_years_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_school_years_school_id ON school_years (school_id);
CREATE INDEX IF NOT EXISTS idx_school_years_created_at ON school_years (created_at DESC);

-- Table: schools
CREATE TABLE IF NOT EXISTS schools (
  "active" BOOLEAN,
  "active_year_code" VARCHAR(255),
  "address" VARCHAR(255),
  "area_kind" VARCHAR(255),
  "boom_goals" VARCHAR(255),
  "branches" VARCHAR(255),
  "capabilities" JSONB,
  "capacity" INTEGER,
  "city" VARCHAR(255),
  "code" VARCHAR(255),
  "county_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "district_id" INTEGER,
  "fields" VARCHAR(255),
  "gender" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "landline" VARCHAR(255),
  "level" VARCHAR(255),
  "name" VARCHAR(255),
  "notify_rules" VARCHAR(255),
  "organization_id" INTEGER,
  "phone" VARCHAR(20),
  "place_rules" VARCHAR(255),
  "province_id" INTEGER,
  "public_goals" VARCHAR(255),
  "school_type" VARCHAR(255),
  "shift" VARCHAR(255),
  "type" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "work_days" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_schools_created_at ON schools (created_at DESC);

-- Table: sedascores
CREATE TABLE IF NOT EXISTS sedascores (
  "created_at" TIMESTAMPTZ,
  "entered_by" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "school_id" INTEGER,
  "score" NUMERIC(12, 2),
  "student_id" INTEGER,
  "subject_id" INTEGER,
  "term" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_sedascores_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_sedascores_school_id ON sedascores (school_id);
CREATE INDEX IF NOT EXISTS idx_sedascores_school_student ON sedascores (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_sedascores_created_at ON sedascores (created_at DESC);

-- Table: sms_log
CREATE TABLE IF NOT EXISTS sms_log (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "parts" VARCHAR(255),
  "phone" VARCHAR(20),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "user_id" INTEGER,
  CONSTRAINT fk_sms_log_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_sms_log_school_id ON sms_log (school_id);
CREATE INDEX IF NOT EXISTS idx_sms_log_created_at ON sms_log (created_at DESC);

-- Table: sms_wallet
CREATE TABLE IF NOT EXISTS sms_wallet (
  "balance" NUMERIC(12, 2),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_sms_wallet_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_sms_wallet_school_id ON sms_wallet (school_id);
CREATE INDEX IF NOT EXISTS idx_sms_wallet_created_at ON sms_wallet (created_at DESC);

-- Table: staff_attendance
CREATE TABLE IF NOT EXISTS staff_attendance (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" TEXT,
  "registered_by" VARCHAR(255),
  "school_id" INTEGER,
  "staff_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_staff_attendance_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_staff_attendance_school_id ON staff_attendance (school_id);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_created_at ON staff_attendance (created_at DESC);

-- Table: student_archive
CREATE TABLE IF NOT EXISTS student_archive (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "archived_at" TIMESTAMPTZ,
  "attendance_rate" VARCHAR(255),
  "avg_score" VARCHAR(255),
  "class_name" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "discipline_points" VARCHAR(255),
  "field" VARCHAR(255),
  "full_name" VARCHAR(255),
  "grade_level" VARCHAR(255),
  "name" VARCHAR(255),
  "national_id" VARCHAR(10),
  "school_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "year_code" VARCHAR(255),
  CONSTRAINT fk_student_archive_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_student_archive_school_id ON student_archive (school_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_school_nid ON student_archive (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_school_student ON student_archive (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_student_archive_created_at ON student_archive (created_at DESC);

-- Table: student_transfers
CREATE TABLE IF NOT EXISTS student_transfers (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "from_grade" VARCHAR(255),
  "from_school_id" INTEGER,
  "moved_attendance" VARCHAR(255),
  "moved_discipline" VARCHAR(255),
  "moved_grades" VARCHAR(255),
  "reason" VARCHAR(255),
  "student_id" INTEGER,
  "to_grade" VARCHAR(255),
  "to_school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "year_code" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_student_transfers_created_at ON student_transfers (created_at DESC);

-- Table: subjects
CREATE TABLE IF NOT EXISTS subjects (
  "code" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "field" VARCHAR(255),
  "grade" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "school_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "weekly_hours" VARCHAR(255),
  CONSTRAINT fk_subjects_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_subjects_school_id ON subjects (school_id);
CREATE INDEX IF NOT EXISTS idx_subjects_created_at ON subjects (created_at DESC);

-- Table: subscription_payments
CREATE TABLE IF NOT EXISTS subscription_payments (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" NUMERIC(12, 2),
  "created_at" TIMESTAMPTZ,
  "method" VARCHAR(255),
  "months" VARCHAR(255),
  "paid_at" TIMESTAMPTZ,
  "plan" VARCHAR(255),
  "ref_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "user_id" INTEGER
);

CREATE INDEX IF NOT EXISTS idx_subscription_payments_created_at ON subscription_payments (created_at DESC);

-- Table: substitutions
CREATE TABLE IF NOT EXISTS substitutions (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schedule_id" INTEGER,
  "school_id" INTEGER,
  "sub_teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_substitutions_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_substitutions_school_id ON substitutions (school_id);
CREATE INDEX IF NOT EXISTS idx_substitutions_created_at ON substitutions (created_at DESC);

-- Table: summer_classes
CREATE TABLE IF NOT EXISTS summer_classes (
  "created_at" TIMESTAMPTZ,
  "end_date" VARCHAR(50),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "note" TEXT,
  "school_id" INTEGER,
  "start_date" VARCHAR(50),
  "student_ids" VARCHAR(255),
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_summer_classes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_summer_classes_school_id ON summer_classes (school_id);
CREATE INDEX IF NOT EXISTS idx_summer_classes_created_at ON summer_classes (created_at DESC);

-- Table: support_tickets
CREATE TABLE IF NOT EXISTS support_tickets (
  "created_at" TIMESTAMPTZ,
  "description" TEXT,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "priority" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_support_tickets_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_school_id ON support_tickets (school_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_created_at ON support_tickets (created_at DESC);

-- Table: teacher_evaluations
CREATE TABLE IF NOT EXISTS teacher_evaluations (
  "created_at" TIMESTAMPTZ,
  "criteria" JSONB,
  "feedback" TEXT,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "teacher_id" INTEGER,
  CONSTRAINT fk_teacher_evaluations_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_teacher_evaluations_school_id ON teacher_evaluations (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_evaluations_created_at ON teacher_evaluations (created_at DESC);

-- Table: teacher_notes
CREATE TABLE IF NOT EXISTS teacher_notes (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "school_id" INTEGER,
  "student_id" INTEGER,
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_teacher_notes_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_teacher_notes_school_id ON teacher_notes (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_notes_school_student ON teacher_notes (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_teacher_notes_created_at ON teacher_notes (created_at DESC);

-- Table: teacher_schools
CREATE TABLE IF NOT EXISTS teacher_schools (
  "active" BOOLEAN,
  "created_at" TIMESTAMPTZ,
  "employment" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  "weekly_quota" VARCHAR(255),
  CONSTRAINT fk_teacher_schools_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_teacher_schools_school_id ON teacher_schools (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_schools_created_at ON teacher_schools (created_at DESC);

-- Table: teacher_sms
CREATE TABLE IF NOT EXISTS teacher_sms (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "phone" VARCHAR(20),
  "school_id" INTEGER,
  "source_ref" VARCHAR(255),
  "status" VARCHAR(255),
  "teacher_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_teacher_sms_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_teacher_sms_school_id ON teacher_sms (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_sms_created_at ON teacher_sms (created_at DESC);

-- Table: training_courses
CREATE TABLE IF NOT EXISTS training_courses (
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "hours" INTEGER,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" INTEGER,
  "staff_id" INTEGER,
  "status" VARCHAR(255),
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_training_courses_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_training_courses_school_id ON training_courses (school_id);
CREATE INDEX IF NOT EXISTS idx_training_courses_created_at ON training_courses (created_at DESC);

-- Table: transactions
CREATE TABLE IF NOT EXISTS transactions (
  "amount" NUMERIC(12, 2),
  "by" VARCHAR(255),
  "category" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "date" VARCHAR(50),
  "description" TEXT,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "installment_id" INTEGER,
  "kind" VARCHAR(255),
  "school_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_transactions_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_transactions_school_id ON transactions (school_id);
CREATE INDEX IF NOT EXISTS idx_transactions_school_student ON transactions (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions (created_at DESC);

-- Table: transfer_requests
CREATE TABLE IF NOT EXISTS transfer_requests (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "from_school_id" INTEGER,
  "national_id" VARCHAR(10),
  "note" TEXT,
  "requested_by" VARCHAR(255),
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "to_school_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transfer_requests_created_at ON transfer_requests (created_at DESC);

-- Table: tuition_plans
CREATE TABLE IF NOT EXISTS tuition_plans (
  "active" BOOLEAN,
  "amount" NUMERIC(12, 2),
  "created_at" TIMESTAMPTZ,
  "first_due" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "installments" VARCHAR(255),
  "interval_days" VARCHAR(255),
  "school_id" INTEGER,
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_tuition_plans_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_tuition_plans_school_id ON tuition_plans (school_id);
CREATE INDEX IF NOT EXISTS idx_tuition_plans_created_at ON tuition_plans (created_at DESC);

-- Table: tuitions
CREATE TABLE IF NOT EXISTS tuitions (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "discount" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paid" VARCHAR(255),
  "payable" VARCHAR(255),
  "plan_id" INTEGER,
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "student_id" INTEGER,
  "total" NUMERIC(12, 2),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_tuitions_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_tuitions_school_id ON tuitions (school_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_school_student ON tuitions (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_school_class ON tuitions (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_tuitions_created_at ON tuitions (created_at DESC);

-- Table: users
CREATE TABLE IF NOT EXISTS users (
  "active" BOOLEAN,
  "birth_date" VARCHAR(50),
  "created_at" TIMESTAMPTZ,
  "degree" VARCHAR(255),
  "dropped_out_at" TIMESTAMPTZ,
  "dropped_out_by" VARCHAR(255),
  "dropped_out_note" VARCHAR(255),
  "dropped_out_reason" VARCHAR(255),
  "entry_gpa" VARCHAR(255),
  "father_nid" VARCHAR(10),
  "field" VARCHAR(255),
  "full_name" VARCHAR(255),
  "gender" VARCHAR(255),
  "grade_level" VARCHAR(255),
  "graduated_year" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "iep_notes" TEXT,
  "iep_staff" VARCHAR(255),
  "iep_updated" VARCHAR(255),
  "job" VARCHAR(255),
  "mother_nid" VARCHAR(10),
  "national_id" VARCHAR(10),
  "office_id" INTEGER,
  "phone" VARCHAR(20),
  "returned_at" TIMESTAMPTZ,
  "returned_by" VARCHAR(255),
  "role" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "subject" VARCHAR(255),
  "subject_id" INTEGER,
  "title" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "username" VARCHAR(255),
  CONSTRAINT fk_users_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT chk_users_status CHECK (status IN ('active', 'dropped_out', 'graduated', 'awaiting_transfer'))
);

CREATE INDEX IF NOT EXISTS idx_users_school_id ON users (school_id);
CREATE INDEX IF NOT EXISTS idx_users_school_nid ON users (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at DESC);

-- Table: vclass_attendance
CREATE TABLE IF NOT EXISTS vclass_attendance (
  "by" VARCHAR(255),
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "joined_at" TIMESTAMPTZ,
  "left_at" TIMESTAMPTZ,
  "session_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_vclass_attendance_created_at ON vclass_attendance (created_at DESC);

-- Table: vclass_links
CREATE TABLE IF NOT EXISTS vclass_links (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ,
  "session_id" INTEGER,
  "student_id" INTEGER,
  "token" VARCHAR(255),
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_vclass_links_created_at ON vclass_links (created_at DESC);

-- Table: vclass_questions
CREATE TABLE IF NOT EXISTS vclass_questions (
  "answer" VARCHAR(255),
  "answered_at" TIMESTAMPTZ,
  "answered_by" VARCHAR(255),
  "body" TEXT,
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" INTEGER,
  "student_id" INTEGER,
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_vclass_questions_created_at ON vclass_questions (created_at DESC);

-- Table: vclass_sessions
CREATE TABLE IF NOT EXISTS vclass_sessions (
  "class_id" INTEGER,
  "created_at" TIMESTAMPTZ,
  "created_by" VARCHAR(255),
  "description" TEXT,
  "file_key" VARCHAR(255),
  "file_name" VARCHAR(255),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mime" VARCHAR(255),
  "school_id" INTEGER,
  "shad_time" VARCHAR(255),
  "shad_url" VARCHAR(255),
  "size" VARCHAR(255),
  "title" VARCHAR(255),
  "type" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_vclass_sessions_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_vclass_sessions_school_id ON vclass_sessions (school_id);
CREATE INDEX IF NOT EXISTS idx_vclass_sessions_school_class ON vclass_sessions (school_id, class_id);
CREATE INDEX IF NOT EXISTS idx_vclass_sessions_created_at ON vclass_sessions (created_at DESC);

-- Table: visitors
CREATE TABLE IF NOT EXISTS visitors (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "in_at" TIMESTAMPTZ,
  "name" VARCHAR(255),
  "national_id" VARCHAR(10),
  "out_at" TIMESTAMPTZ,
  "phone" VARCHAR(20),
  "purpose" VARCHAR(255),
  "registered_by" VARCHAR(255),
  "school_id" INTEGER,
  "status" VARCHAR(255),
  "updated_at" TIMESTAMPTZ,
  "visiting_person" VARCHAR(255),
  CONSTRAINT fk_visitors_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_visitors_school_id ON visitors (school_id);
CREATE INDEX IF NOT EXISTS idx_visitors_school_nid ON visitors (school_id, national_id);
CREATE INDEX IF NOT EXISTS idx_visitors_created_at ON visitors (created_at DESC);

-- Table: staff_posts
CREATE TABLE IF NOT EXISTS staff_posts (
  "created_at" TIMESTAMPTZ,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "required" VARCHAR(255),
  "school_id" INTEGER,
  "subject_id" INTEGER,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT fk_staff_posts_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_staff_posts_school_id ON staff_posts (school_id);
CREATE INDEX IF NOT EXISTS idx_staff_posts_created_at ON staff_posts (created_at DESC);

-- Table: sync_conflicts (server-managed conflict preservation)
CREATE TABLE IF NOT EXISTS sync_conflicts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection" VARCHAR(128) NOT NULL,
  "record_id" INTEGER,
  "school_id" INTEGER,
  "base_version" INTEGER,
  "server_version" INTEGER,
  "server_state" JSONB,
  "incoming" JSONB,
  "status" VARCHAR(32) NOT NULL DEFAULT 'open',
  "winner" VARCHAR(32),
  "reason" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "resolved_at" TIMESTAMPTZ,
  "resolved_by" INTEGER,
  CONSTRAINT fk_sync_conflicts_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT chk_sync_conflicts_status CHECK (status IN ('open', 'resolved')),
  CONSTRAINT chk_sync_conflicts_winner CHECK (winner IS NULL OR winner IN ('incoming', 'server'))
);

-- Specialized Performance Composite Indexes
CREATE INDEX IF NOT EXISTS idx_users_school_role ON users (school_id, role);
CREATE INDEX IF NOT EXISTS idx_attendance_school_class_date ON attendance (school_id, class_id, date);
CREATE INDEX IF NOT EXISTS idx_grades_school_student_subject ON grades (school_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_schedule_school_teacher_day ON schedule (school_id, teacher_id, day);
CREATE INDEX IF NOT EXISTS idx_parent_links_parent_student ON parent_links (parent_id, student_id);
CREATE INDEX IF NOT EXISTS idx_messages_to_from ON messages (to_id, from_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, read);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_school_status ON sync_conflicts (school_id, status);
CREATE INDEX IF NOT EXISTS idx_schools_capabilities ON schools USING GIN (capabilities);

BEGIN;

COMMIT;
