#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   tools/migrate-to-pg.js — PostgreSQL Data Migration & DDL Generator
   -------------------------------------------------------------------
   Phase 2: Migration from server/data/payesh.json to PostgreSQL
   - Maps all 80 collections from authz/model.json to relational tables.
   - Generates production-grade DDL schema with constraints & indexes.
   - Converts JSON store records into parameterized bulk SQL inserts.
   - Direct execution mode with PostgreSQL pg.Pool if DATABASE_URL is set.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const MODEL_FILE = path.join(ROOT_DIR, 'authz', 'model.json');
const STORE_FILE = process.env.PAYESH_STORE || path.join(ROOT_DIR, 'server', 'data', 'payesh.json');
const SCHEMA_FILE = path.join(ROOT_DIR, 'server', 'schema.sql');

/* Load Data Model */
if (!fs.existsSync(MODEL_FILE)) {
  console.error('Error: authz/model.json not found at ' + MODEL_FILE);
  process.exit(1);
}
const model = JSON.parse(fs.readFileSync(MODEL_FILE, 'utf8'));
const collections = model.collections || {};
const VERSION_TRACKED = { grades: 1, attendance: 1, discipline: 1, schools: 1, classes: 1, subjects: 1, users: 1, enrollments: 1, schedule: 1 };
function managedFields(col, fields) {
  const out = (fields || []).slice();
  if (VERSION_TRACKED[col]) {
    if (!out.includes('version')) out.push('version');
    if (!out.includes('version_vector')) out.push('version_vector');
  }
  return out;
}

/* Chat 2 remediation: non-fatal data warnings collected during SQL generation */
const migrationWarnings = [];
/* Chat 2 remediation: DDL was inferred WITHOUT data samples (all unspecified
   fields => VARCHAR(255)), so one 300-char demo note aborted --execute with
   "value too long for type character varying(255)". generateMigrationSQL now
   snapshots real samples from the store FIRST and getColumnType consults them,
   making schema inference consistent with the values it will insert. */
const COLUMN_SAMPLES = {};
function snapshotColumnSamples(store) {
  for (const col of Object.keys(collections)) {
    const rows = Array.isArray(store[col]) ? store[col] : [];
    const def = collections[col];
    const fields = managedFields(col, def.fields || []);
    for (const f of fields) {
      let sample;
      for (const r of rows.slice(0, 200)) {
        const v = r ? r[f] : undefined;
        if (v === undefined || v === null) continue;
        if (typeof v === 'string' && v.length > 255) { sample = v; break; }  /* worst case wins */
        if (sample === undefined) sample = v;
      }
      if (sample !== undefined) COLUMN_SAMPLES[col + '.' + f] = sample;
    }
  }
}

/* Infer optimal column types for PostgreSQL */
function getColumnType(colName, fieldName, sampleVal) {
  if (sampleVal === undefined) sampleVal = COLUMN_SAMPLES[colName + '.' + fieldName];
  if (fieldName === 'id') return 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
  /* Devin-R2/R3: استثناهای مدل داده (پارامتر colName تا امروز استفاده نمی‌شد) —
     yearCode رشتهٔ «۱۴۰۴-۱۴۰۵» می‌سازد پس year گواهی VARCHAR است؛
     سقف اعتبارسنجی مبلغ کمک (۱۰^۱۰) در NUMERIC(12,2) جا نمی‌شود. */
  if (colName === 'certificates' && fieldName === 'year') return 'VARCHAR(50)';
  if (colName === 'donations' && fieldName === 'amount') return 'NUMERIC(14, 2)';
  if (colName === 'training_courses' && fieldName === 'hours') return 'INTEGER';
  if (colName === 'safety_drills' && (fieldName === 'participant_count_staff' || fieldName === 'participant_count_students')) return 'INTEGER';
  if (fieldName === 'national_id' || fieldName === 'father_nid' || fieldName === 'mother_nid') return 'VARCHAR(10)';
  if (fieldName === 'phone' || fieldName === 'mobile' || fieldName === 'tel') return 'VARCHAR(20)';
  if (fieldName === 'postal_code') return 'VARCHAR(10)';
  if (fieldName.endsWith('_id') || fieldName === 'school_id' || fieldName === 'user_id' || 
      fieldName === 'student_id' || fieldName === 'teacher_id' || fieldName === 'parent_id' || 
      fieldName === 'class_id' || fieldName === 'subject_id' || fieldName === 'office_id') {
    return 'INTEGER';
  }
  if (fieldName === 'version_vector' || fieldName === 'base_vector' || fieldName === 'server_vector' ||
      (colName === 'summer_classes' && fieldName === 'schedule') ||
      (colName === 'summer_enrollments' && fieldName === 'attendance') ||
      (colName === 'summer_classes' && fieldName === 'student_ids')) return 'JSONB';
  if (fieldName === 'version' || fieldName === 'base_version' || fieldName === 'server_version' || 
      fieldName === 'grade' || fieldName === 'capacity' || fieldName === 'units' || 
      fieldName === 'year' || fieldName === 'read' || fieldName === 'late' || fieldName === 'count') {
    return 'INTEGER';
  }
  if (fieldName === 'active' || fieldName === 'is_active' || fieldName === 'passed' || fieldName === 'verified' || fieldName === 'read') {
    return 'BOOLEAN';
  }
  if (fieldName === 'score' || fieldName === 'amount' || fieldName === 'price' || 
      fieldName === 'balance' || fieldName === 'total' || fieldName === 'fee' || 
      fieldName === 'gpa' || fieldName === 'rate') {
    return 'NUMERIC(12, 2)';
  }
  if (fieldName.endsWith('_at') || fieldName === 'created_at' || fieldName === 'updated_at' || fieldName === 'at') {
    return 'TIMESTAMPTZ';
  }
  if (fieldName.endsWith('_date') || fieldName === 'date' || fieldName === 'birth_date' || fieldName === 'from_date' || fieldName === 'to_date') {
    return 'VARCHAR(50)';
  }
  if (fieldName === 'capabilities' || fieldName === 'data' || fieldName === 'meta' || 
      fieldName === 'settings' || fieldName === 'incoming' || fieldName === 'server_state' || 
      fieldName === 'items' || fieldName === 'options' || fieldName === 'extra' ||
      fieldName === 'criteria') {
    return 'JSONB';
  }
  if (fieldName === 'body' || fieldName === 'text' || fieldName === 'note' || 
      fieldName === 'notes' || fieldName === 'description' || fieldName === 'summary' || 
      fieldName === 'details' || fieldName === 'iep_notes' || fieldName === 'feedback') {
    return 'TEXT';
  }

  // Type inference based on sample value
  if (sampleVal !== undefined && sampleVal !== null) {
    if (typeof sampleVal === 'boolean') return 'BOOLEAN';
    if (typeof sampleVal === 'number') {
      return Number.isInteger(sampleVal) ? 'INTEGER' : 'NUMERIC(12, 2)';
    }
    if (typeof sampleVal === 'object') return 'JSONB';
    if (typeof sampleVal === 'string' && sampleVal.length > 255) return 'TEXT';
  }

  return 'VARCHAR(255)';
}

/* Escape SQL literals */
function escapeSqlVal(val, type) {
  if (val === undefined || val === null) return 'NULL';
  if (type === 'BOOLEAN') return val ? 'TRUE' : 'FALSE';
  if (type === 'INTEGER') {
    const n = parseInt(val, 10);
    return isNaN(n) ? 'NULL' : String(n);
  }
  if (type.startsWith('NUMERIC')) {
    const n = parseFloat(val);
    return isNaN(n) ? 'NULL' : String(n);
  }
  if (type === 'JSONB') {
    const jsonStr = typeof val === 'string' ? val : JSON.stringify(val);
    return "'" + jsonStr.replace(/'/g, "''") + "'::jsonb";
  }
  if (type === 'TIMESTAMPTZ') {
    /* Chat 2 remediation: demo/real stores carry non-ISO strings in time-ish
       fields (Jalali dates, free text). One unparseable literal used to abort
       the WHOLE --execute run with DateTimeParseError. Unparseable values now
       degrade to NULL and are counted in the migration warnings summary. */
    const raw = (typeof val === 'number') ? new Date(val).toISOString() : String(val);
    if (isNaN(Date.parse(raw))) {
      migrationWarnings.push('unparseable timestamptz value → NULL: ' + raw.slice(0, 60));
      return 'NULL';
    }
    const st = raw.replace(/'/g, "''");
    return "'" + st + "'::timestamptz";
  }
  // Default string
  const str = typeof val === 'object' ? JSON.stringify(val) : String(val);
  return "'" + str.replace(/'/g, "''") + "'";
}

/* Generate full DDL Schema for all 80 tables */
function generateDDL() {
  const ddl = [];
  ddl.push('-- ═══════════════════════════════════════════════════════════════════');
  ddl.push('-- Payesh PostgreSQL Relational Schema (80 Collections)');
  ddl.push('-- Auto-generated from authz/model.json');
  ddl.push('-- ═══════════════════════════════════════════════════════════════════\n');
  ddl.push('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
  ddl.push('CREATE EXTENSION IF NOT EXISTS "btree_gist";\n');

  // Metadata / internal state tables
  ddl.push('-- Internal synchronization & session management tables');
  ddl.push(`CREATE TABLE IF NOT EXISTS server_processed_uids (
  uid VARCHAR(128) PRIMARY KEY,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS server_revoked_jti (
  jti VARCHAR(128) PRIMARY KEY,
  revoked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS server_auth_codes (
  phone VARCHAR(20) PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  national_id VARCHAR(10),
  user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
`);

  /* ویو ۸ — صندوق رویدادهای برون‌مرزی (آینهٔ پستگرس؛ منبع حقیقت اسنپ‌شات است) */
  ddl.push(`-- Transactional outbox (wave 8)
CREATE TABLE IF NOT EXISTS server_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   /* 014 parity: default id like the migration chain's BIGSERIAL */
  type VARCHAR(64) NOT NULL,
  collection VARCHAR(64),
  record_id BIGINT,
  actor_id BIGINT,
  version INTEGER,
  payload JSONB,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  retry_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  processing_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_server_outbox_status ON server_outbox (status);

-- Dead-letter queue (wave 27 / migration 014 parity) — the worker routes
-- poison pills here; without this table moveToDlq fails (reproduced live).
CREATE TABLE IF NOT EXISTS server_outbox_dlq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outbox_id BIGINT NOT NULL,
  type VARCHAR(64) NOT NULL,
  collection VARCHAR(64) NOT NULL,
  record_id BIGINT,
  actor_id BIGINT,
  version INT,
  payload JSONB,
  error_message TEXT NOT NULL,
  retry_count INT NOT NULL DEFAULT 5,
  failed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_server_outbox_dlq_time ON server_outbox_dlq (failed_at DESC);
CREATE INDEX IF NOT EXISTS idx_server_outbox_dlq_type ON server_outbox_dlq (type, collection);
`);

  const colNames = Object.keys(collections);
  /* P0-BUG-03 fix (Chat 2 remediation, 2026-09-19): FK constraints are collected
     and emitted in a SECOND phase, after every table exists. Inline FKs made the
     generated DDL order-dependent (announcements → schools failed when
     announcements was generated first) and `--execute` died on a clean database
     with `relation "..." does not exist` before creating anything. */
  const fkStatements = [];
  for (const col of colNames) {
    const def = collections[col];
    const fields = managedFields(col, def.fields || []);
    
    // Ensure 'id' exists
    const allFields = fields.includes('id') ? fields : ['id', ...fields];
    
    ddl.push(`-- Table: ${col}`);
    ddl.push(`CREATE TABLE IF NOT EXISTS ${col} (`);
    
    const colDefs = [];
    for (const f of allFields) {
      const type = getColumnType(col, f);
      colDefs.push(`  "${f}" ${type}`);
    }

    // Foreign keys are DEFERRED to phase 2 (see fkStatements) — never inline.
    if (col !== 'schools' && allFields.includes('school_id')) {
      fkStatements.push(`ALTER TABLE ${col} ADD CONSTRAINT fk_${col}_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED`);
    }

    /* P1-13 (تمامیت داده، مقیاس ملی): اینوارینت‌های کسب‌وکار در سطح دیتابیس.
       هر قید فقط وقتی صادر می‌شود که ستون‌هایش در مدل باشند (محافظت در برابر رانش مدل). */
    if (col === 'classes' && allFields.includes('capacity')) {
      colDefs.push('  CONSTRAINT chk_classes_capacity CHECK (capacity > 0)');
    }
    if (col === 'enrollments' && allFields.includes('student_id') && allFields.includes('year')) {
      /* یک دانش‌آموز، یک ثبت‌نام در هر سال. نکته: NULLها در UNIQUE پستگرس تداخل ندارند
         (فعلاً year خالی است پس قید روی دادهٔ امروز خنثی است)؛ انتقالِ هم‌سال با دو سطرِ
         باز باید در سطح اپ بسته شود (سطرِ پیشین بسته/حذف شود). */
      colDefs.push('  CONSTRAINT uq_enrollments_student_year UNIQUE (student_id, year)');
    }
    if (col === 'schedule' && allFields.includes('teacher_id') && allFields.includes('day') && allFields.includes('period')) {
      colDefs.push('  CONSTRAINT uq_schedule_teacher_slot UNIQUE (teacher_id, day, period)');
    }
    if (col === 'users' && allFields.includes('status')) {
      /* enum دقیقاً از server/validate.js (STATUS_ENUMS.users) — مقدار چهارم awaiting_transfer است نه transferred */
      colDefs.push("  CONSTRAINT chk_users_status CHECK (status IN ('active', 'dropped_out', 'graduated', 'awaiting_transfer'))");
    }
    if (col === 'grades') {
      if (allFields.includes('student_id')) fkStatements.push(`ALTER TABLE grades ADD CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED`);
      if (allFields.includes('class_id')) fkStatements.push(`ALTER TABLE grades ADD CONSTRAINT fk_grades_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED`);
      if (allFields.includes('subject_id')) fkStatements.push(`ALTER TABLE grades ADD CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED`);
      if (allFields.includes('teacher_id')) fkStatements.push(`ALTER TABLE grades ADD CONSTRAINT fk_grades_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED`);
    }

    ddl.push(colDefs.join(',\n'));
    ddl.push(');\n');

    // Add indexes
    if (allFields.includes('school_id')) {
      ddl.push(`CREATE INDEX IF NOT EXISTS idx_${col}_school_id ON ${col} (school_id);`);
    }
    if (allFields.includes('school_id') && allFields.includes('national_id')) {
      ddl.push(`CREATE INDEX IF NOT EXISTS idx_${col}_school_nid ON ${col} (school_id, national_id);`);
    }
    if (allFields.includes('school_id') && allFields.includes('student_id')) {
      ddl.push(`CREATE INDEX IF NOT EXISTS idx_${col}_school_student ON ${col} (school_id, student_id);`);
    }
    if (allFields.includes('school_id') && allFields.includes('class_id')) {
      ddl.push(`CREATE INDEX IF NOT EXISTS idx_${col}_school_class ON ${col} (school_id, class_id);`);
    }
    if (allFields.includes('created_at')) {
      ddl.push(`CREATE INDEX IF NOT EXISTS idx_${col}_created_at ON ${col} (created_at DESC);`);
    }
    ddl.push('');
  }

  // Internal conflict table (runtime-maintained; not a client-write collection)
  ddl.push(`-- Table: sync_conflicts (server-managed conflict preservation)
CREATE TABLE IF NOT EXISTS sync_conflicts (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection" VARCHAR(128) NOT NULL,
  "record_id" INTEGER,
  "school_id" INTEGER,
  "base_version" INTEGER,
  "server_version" INTEGER,
  "server_state" JSONB,
  "incoming" JSONB,
  "status" VARCHAR(32) NOT NULL DEFAULT 'open',
  "winner" VARCHAR(32),
  "reason" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "resolved_at" TIMESTAMPTZ,
  "resolved_by" INTEGER,
  CONSTRAINT fk_sync_conflicts_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT chk_sync_conflicts_status CHECK (status IN ('open', 'resolved')),
  CONSTRAINT chk_sync_conflicts_winner CHECK (winner IS NULL OR winner IN ('incoming', 'server'))
);
`);

  // Composite indexes & GIN indexes
  ddl.push('-- Specialized Performance Composite Indexes');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_users_school_role ON users (school_id, role);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_attendance_school_class_date ON attendance (school_id, class_id, date);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_grades_school_student_subject ON grades (school_id, student_id, subject_id);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_schedule_school_teacher_day ON schedule (school_id, teacher_id, day);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_parent_links_parent_student ON parent_links (parent_id, student_id);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_messages_to_from ON messages (to_id, from_id);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, read);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_sync_conflicts_school_status ON sync_conflicts (school_id, status);');
  ddl.push('CREATE INDEX IF NOT EXISTS idx_schools_capabilities ON schools USING GIN (capabilities);\n');

  /* ── Phase 2: FK constraints — emitted AFTER every table exists (P0-BUG-03).
     Idempotent: guarded by pg_constraint lookup (ADD CONSTRAINT has no IF NOT EXISTS). */
  if (fkStatements.length) {
    ddl.push('');
    ddl.push('-- ═══ Phase 2: FK constraints (all tables exist by now — order-independent) ═══');
    for (const fk of fkStatements) {
      const nm = (fk.match(/ADD CONSTRAINT\s+([a-zA-Z0-9_]+)/) || [])[1];
      if (!nm) continue;
      ddl.push(`DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${nm}') THEN
    ${fk};
  END IF;
END $$;`);
    }
  }

  return ddl.join('\n');
}

/* Generate Bulk Insert SQL from JSON store */
function generateMigrationSQL(store) {
  snapshotColumnSamples(store);
  const statements = [];
  statements.push(generateDDL());
  statements.push('BEGIN;\n');

  // Insert order prioritizing schools, then users, then others
  const allCols = Object.keys(collections);
  const orderedCols = ['schools', 'users', ...allCols.filter(c => c !== 'schools' && c !== 'users')];

  let totalRows = 0;

  for (const col of orderedCols) {
    const rows = Array.isArray(store[col]) ? store[col] : [];
    if (rows.length === 0) continue;

    const def = collections[col];
    const fields = managedFields(col, def.fields || Object.keys(rows[0] || {}));
    const colList = fields.map(f => `"${f}"`).join(', ');

    statements.push(`-- Inserting ${rows.length} rows into ${col}`);
    
    // Batch in chunks of 100 rows
    const chunkSize = 100;
    for (let i = 0; i < rows.length; i += chunkSize) {
      const chunk = rows.slice(i, i + chunkSize);
      const valuesRows = [];

      for (const row of chunk) {
        const valArr = fields.map(f => {
          const type = getColumnType(col, f, row[f]);
          return escapeSqlVal(row[f], type);
        });
        valuesRows.push(`  (${valArr.join(', ')})`);
      }

      const sql = `INSERT INTO ${col} (${colList})\nVALUES\n${valuesRows.join(',\n')}\nON CONFLICT (id) DO UPDATE SET\n` +
        fields.filter(f => f !== 'id').map(f => `  "${f}" = EXCLUDED."${f}"`).join(',\n') + ';';
      statements.push(sql);
    }
    statements.push('');
    totalRows += rows.length;
  }

  // Insert internal tracking state
  if (store.__processed_uids && typeof store.__processed_uids === 'object') {
    const uids = Object.entries(store.__processed_uids);
    if (uids.length > 0) {
      statements.push(`-- Inserting ${uids.length} processed uids`);
      for (const [uid, ts] of uids) {
        statements.push(`INSERT INTO server_processed_uids (uid, processed_at) VALUES ('${uid.replace(/'/g, "''")}', '${new Date(ts).toISOString()}') ON CONFLICT (uid) DO NOTHING;`);
      }
      statements.push('');
    }
  }

  statements.push('COMMIT;\n');
  /* Universal-OCC backfill (Phase-2 remediation, live finding): the migration
     chain's 013 gives every app table `version INTEGER NOT NULL DEFAULT 1` —
     a store-migrated database must satisfy the SAME contract, or every
     conditional OCC UPDATE (WHERE id=$1 AND version=$base) matches nothing
     (version IS NULL) and ALL writes 409 forever.
     Runs in its OWN transaction AFTER the data COMMIT: ALTER on a table that
     just had INSERTs in the same transaction fails with "pending trigger
     events" (reproduced live). */
  statements.push('BEGIN;\n');
  statements.push('-- Universal OCC contract: version column on every app table (parity with migration 013)');
  for (const col of Object.keys(collections)) {
    statements.push(`ALTER TABLE ${col} ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;`);
    statements.push(`UPDATE ${col} SET version = 1 WHERE version IS NULL;`);
  }
  /* 013 parity for sync_conflicts: a fresh bootstrap store ships an EMPTY
     sync_conflicts array, so the inferred shape lacks the phase-5 additive
     columns — and the first recorded conflict then fails with
     "column user_id does not exist" (reproduced live). */
  statements.push('-- Named shared outbox id sequence (parity with migration 004) — outbox.append does nextval(payesh_outbox_id_seq)');
  statements.push('CREATE SEQUENCE IF NOT EXISTS payesh_outbox_id_seq;');
  statements.push('-- sync_conflicts phase-5 additive columns (parity with migration 013)');
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS client_uid VARCHAR(128);`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS user_id BIGINT;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS client_data JSONB;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS server_data JSONB;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS incoming_version INTEGER;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS current_version INTEGER;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS resolved_data JSONB;`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS resolution_strategy VARCHAR(32) NOT NULL DEFAULT 'server_wins';`);
  statements.push(`ALTER TABLE sync_conflicts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;`);
  statements.push(`CREATE INDEX IF NOT EXISTS idx_sync_conflicts_user ON sync_conflicts (user_id, created_at);`);
  statements.push('');
  statements.push('COMMIT;\n');
  return { sql: statements.join('\n'), totalRows };
}

/* Direct Migration execution with PostgreSQL */
async function executeMigration(store) {
  let pg;
  try {
    pg = require('pg');
  } catch (e) {
    console.error('Error: pg driver is not installed. Please install pg (npm i pg) to execute direct migration.');
    process.exit(1);
  }

  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error('Error: DATABASE_URL environment variable is required for execution mode.');
    console.error('Example: DATABASE_URL=postgresql://user:pass@localhost:5432/payesh node tools/migrate-to-pg.js --execute');
    process.exit(1);
  }

  const pool = new pg.Pool({
    connectionString: databaseUrl,
    connectionTimeoutMillis: 5000
  });

  const client = await pool.connect();
  try {
    console.log('Connected to PostgreSQL database:', databaseUrl.replace(/:[^:@]+@/, ':***@'));
    console.log('Generating DDL and migration script...');
    const { sql, totalRows } = generateMigrationSQL(store);

    console.log(`Executing SQL migration (${totalRows} records across 80 collections)...`);
    await client.query(sql);
    console.log('Migration completed successfully!');
    if (migrationWarnings.length) {
      console.log(`Warnings (${migrationWarnings.length} values degraded to NULL):`);
      for (const w of migrationWarnings.slice(0, 10)) console.log('  - ' + w);
      if (migrationWarnings.length > 10) console.log('  ... and ' + (migrationWarnings.length - 10) + ' more');
    }

    // Validation
    console.log('\n--- Data Verification ---');
    for (const col of Object.keys(collections).slice(0, 10)) {
      const res = await client.query(`SELECT COUNT(*) FROM ${col}`);
      const count = parseInt(res.rows[0].count, 10);
      const expected = (store[col] || []).length;
      console.log(`Table ${col}: ${count} rows (source: ${expected}) -> ${count >= expected ? 'OK' : 'MISMATCH'}`);
    }
  } finally {
    client.release();
    await pool.end();
  }
}

/* CLI runner */
async function main() {
  const args = process.argv.slice(2);
  const isExecute = args.includes('--execute');
  const isSqlOnly = args.includes('--sql') || args.includes('--dump-sql');
  const isDryRun = args.includes('--dry-run');

  let store = {};
  if (fs.existsSync(STORE_FILE)) {
    store = JSON.parse(fs.readFileSync(STORE_FILE, 'utf8'));
  } else {
    console.log('Note: No store file found at ' + STORE_FILE + '. Generating schema DDL only.');
  }

  const { sql, totalRows } = generateMigrationSQL(store);

  /* P0-BUG-03 fix (side-effect guard): this tool used to OVERWRITE the tracked
     server/schema.sql on EVERY run — a crashed/failed --execute left the repo's
     schema file replaced by a huge generated artifact. Schema regeneration is
     now explicit: pass --write-schema (or have no schema.sql at all). */
  const wantSchemaWrite = args.includes('--write-schema') || !fs.existsSync(SCHEMA_FILE);
  if (wantSchemaWrite) {
    fs.writeFileSync(SCHEMA_FILE, sql, 'utf8');
    console.log(`[OK] PostgreSQL Schema and Migration DDL written to ${SCHEMA_FILE} (${sql.length} bytes)`);
  } else {
    console.log(`[skip] ${SCHEMA_FILE} left untouched (tracked file) — pass --write-schema to regenerate it`);
  }

  if (isExecute) {
    await executeMigration(store);
  } else {
    console.log(`[OK] Migration Plan & DDL ready for ${Object.keys(collections).length} tables and ${totalRows} data rows.`);
    console.log('To execute migration against PostgreSQL, run:');
    console.log('  DATABASE_URL=postgresql://user:pass@host:5432/dbname node tools/migrate-to-pg.js --execute');
  }
}

if (require.main === module) {
  main().catch(err => {
    console.error('Migration failed:', err);
    process.exit(1);
  });
}

module.exports = {
  generateDDL,
  generateMigrationSQL,
  getColumnType,
  escapeSqlVal
};
